'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblPreOrdenes_Cruzadas
    Public Property intID As Nullable(Of Integer)
    Public Property guidCruce As Nullable(Of System.Guid)
    Public Property intIDPreOrden As Nullable(Of Integer)
    Public Property logEsParcial As Nullable(Of Boolean)
    Public Property intNroParcial As Nullable(Of Integer)
    Public Property dblValorInicial As Nullable(Of Double)
    Public Property dblValorAnterior As Nullable(Of Double)
    Public Property dblValor As Nullable(Of Double)
    Public Property dtmFechaInversion As Nullable(Of Date)
    Public Property dtmFechaVigencia As Nullable(Of Date)
    Public Property intIDCodigoPersona As Nullable(Of Integer)
    Public Property strTipoPreOrden As String
    Public Property strTipoInversion As String
    Public Property intIDEntidad As Nullable(Of Integer)
    Public Property strInstrumento As String
    Public Property strIntencion As String
    Public Property dblPrecio As Nullable(Of Double)
    Public Property dblRentabilidadMinima As Nullable(Of Double)
    Public Property dblRentabilidadMaxima As Nullable(Of Double)
    Public Property strInstrucciones As String
    Public Property logActivo As Nullable(Of Boolean)
    Public Property strObservaciones As String
    Public Property strUsuario As String
    Public Property dtmFechaCreacion As Nullable(Of Date)
    Public Property dtmActualizacion As Nullable(Of Date)
    Public Property strUsuarioInsercion As String
    Public Property intIDPersona As Nullable(Of Integer)
    Public Property intIDComitente As String
    Public Property strNroDocumento As String
    Public Property strNombre As String
    Public Property strTipoProducto As String
    Public Property strIDReceptor As String

End Class
