'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblPreOrdenes_Visor
    Public Property intID As Nullable(Of Integer)
    Public Property intIDPreOrdenVisualizar As Nullable(Of Integer)
    Public Property strTipoPreOrden As String
    Public Property strDescripcionTipoPreOrden As String
    Public Property strTipoInversion As String
    Public Property strDescripcionTipoInversion As String
    Public Property strInstrumento As String
    Public Property dblValor As Nullable(Of Double)
    Public Property dblValorPendiente As Nullable(Of Double)
    Public Property logSeleccionado As Nullable(Of Boolean)

End Class
