'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblPreOrdenes_VisorCruces
    Public Property intID As Nullable(Of Integer)
    Public Property strTipoInversionCompra As String
    Public Property dblValorCruzado As Nullable(Of Double)
    Public Property intIDPreOrdenCompra As Nullable(Of Integer)
    Public Property strDescripcionTipoInversionCompra As String
    Public Property strInstrumentoCompra As String
    Public Property intIDPreOrdenVenta As Nullable(Of Integer)
    Public Property strTipoInversionVenta As String
    Public Property strDescripcionTipoInversionVenta As String
    Public Property strInstrumentoVenta As String
    Public Property dtmFechaCruce As Nullable(Of Date)
    Public Property strUsuario As String
    Public Property logTieneAsociacionCompra As Nullable(Of Boolean)
    Public Property logTieneAsociacionVenta As Nullable(Of Boolean)
    Public Property strTipoOrigenOrdenCompra As String
    Public Property intNroRegistroOrdenCompra As Nullable(Of Integer)
    Public Property strTipoOrigenOrdenVenta As String
    Public Property intNroRegistroOrdenVenta As Nullable(Of Integer)

End Class
