<?xml version="1.0" encoding="utf-8"?>
<Database Name="OYDPLUSYD_Gen_Net" EntityNamespace="OYDPLUSUtilidades" Class="OYDPLUSUtilidadesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="ItemCombosOYDPLUS">
    <Type Name="ItemComboOYDPLUS" Id="ID1">
      <Column Name="Categoria" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" CanBeNull="false" />
      <Column Name="intID" Type="System.Nullable(Of System.Int32)" CanBeNull="true" />
      <Column Name="Retorno" Type="System.String" CanBeNull="true" />
      <Column Name="IDDependencia1" Type="System.Nullable(Of System.Int32)" CanBeNull="true" />
      <Column Name="IDDependencia2" Type="System.Nullable(Of System.Int32)" CanBeNull="true" />
    </Type>
  </Table>
    <Table Name="" Member="tblSaldosCliente">
    <Type Name="tblSaldosCliente" Id="ID2">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigoOYD" Member="CodigoOYD" Type="System.String" DbType="Varchar(17) NOT NULL" CanBeNull="false" />
      <Column Name="strDescripcion" Member="Descripcion" Type="System.String" DbType="Varchar(100) NOT NULL" CanBeNull="false" />
      <Column Name="dblValor" Member="Valor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="logUsado" Member="Usado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="tblPortafolioCliente">
    <Type Name="tblPortafolioCliente" Id="ID3">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigoOYD" Member="CodigoOYD" Type="System.String" DbType="Varchar(17) NULL" CanBeNull="true" />
      <Column Name="strEspecie" Member="Especie" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Member="Cantidad" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strCustodia" Member="Custodia" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strCustodiaSecuencia" Member="CustodiaSecuencia" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strCentralDeposito" Member="CentralDeposito" Type="System.String" DbType="Varchar(4) NULL" CanBeNull="true" />
      <Column Name="strNombreCentralDeposito" Member="NombreCentralDeposito" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="strCuentaDeposito" Member="CuentaDeposito" Type="System.String" DbType="Varchar(25) NULL" CanBeNull="true" />
      <Column Name="strTipoOperacion" Member="TipoOperacion" Type="System.String" DbType="Varchar(4) NULL" CanBeNull="true" />
      <Column Name="strNombreTipoOperacion" Member="NombreTipoOperacion" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="dblPrecioCompra" Member="PrecioCompra" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="intIDLiquidacion" Member="IDLiquidacion" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="intParcial" Member="Parcial" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="dtmFechaLiquidacion" Member="FechaLiquidacion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strTipoLiquidacion" Member="TipoLiquidacion" Type="System.String" DbType="Varchar(10) NULL" CanBeNull="true" />
      <Column Name="strClaseLiquidacion" Member="ClaseLiquidacion" Type="System.String" DbType="Varchar(10) NULL" CanBeNull="true" />
      <Column Name="dtmFechaEmision" Member="FechaEmision" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="dtmFechaVencimiento" Member="FechaVencimiento" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strModalidad" Member="Modalidad" Type="System.String" DbType="Varchar(80) NULL" CanBeNull="true" />
      <Column Name="dblTasaFacial" Member="TasaFacial" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strIndicador" Member="Indicador" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="dblPuntosIndicador" Member="PuntosIndicador" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="logSeleccionada" Member="Seleccionada" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="strTipoTasa" Member="TipoTasa" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strDescripcionIndicador" Member="DescripcionIndicador" Type="System.String" DbType="Varchar(200) NULL" CanBeNull="true" />
      <Column Name="strDescripcionModalidad" Member="DescripcionModalidad" Type="System.String" DbType="Varchar(200) NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="tblOrdenesSAEAcciones">
    <Type Name="tblOrdenesSAEAcciones" Id="ID4">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigoReceptor" Member="CodigoReceptor" Type="System.String" DbType="Varchar(17) NOT NULL" CanBeNull="false" />
      <Column Name="dtmFechaReferencia" Member="FechaReferencia" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="intNroLiquidacion" Member="NroLiquidacion" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="strEspecie" Member="Especie" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="dblPrecio" Member="Precio" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Member="Cantidad" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strEjecucion" Member="Ejecucion" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strNombreEjecucion" Member="NombreEjecucion" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="dtmFechaHoraExpiracion" Member="FechaHoraExpiracion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="intCantidadVisible" Member="CantidadVisible" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="strDuracion" Member="Duracion" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strNombreDuracion" Member="NombreDuracion" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="strTipoProducto" Member="TipoProducto" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strNombreTipoProducto" Member="NombreTipoProducto" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="intIDOrdenOYD" Member="IDOrdenOYD" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="strDiasRepo" Member="DiasRepo" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strEstado" Member="Estado" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="logSeleccionada" Member="Seleccionada" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="strMensajes" Member="Mensajes" Type="System.String" DbType="varchar(200)" CanBeNull="true" />
      <Column Name="dtmFechaCumplimientoRepo" Member="dtmFechaCumplimientoRepo" Type="System.Nullable(Of Datetime)" DbType="Datetime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="tblOperacionesCumplir">
    <Type Name="tblOperacionesCumplir" Id="ID5">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigoOYD" Member="CodigoOYD" Type="System.String" DbType="Varchar(17) NULL" CanBeNull="true" />
      <Column Name="strEspecie" Member="Especie" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="intParcial" Member="Parcial" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="strNroOperacion" Member="NroOperacion" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strTipoSim" Member="rTipoSim" Type="System.String" DbType="Varchar(4) NULL" CanBeNull="true" />
      <Column Name="strTipoOperacion" Member="TipoOperacion" Type="System.String" DbType="Varchar(4) NULL" CanBeNull="true" />
      <Column Name="strNombreTipoOperacion" Member="NombreTipoOperacion" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Member="Cantidad" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dtmFechaLiquidacion" Member="FechaLiquidacion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="dtmFechaCumplimiento" Member="FechaCumplimiento" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="dblTotalLiquidacion" Member="TotalLiquidacion" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dblPrecioLiquidacion" Member="PrecioLiquidacion" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dblTasaEfectiva" Member="TasaEfectiva" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strCuentaDeposito" Member="CuentaDeposito" Type="System.String" DbType="Varchar(25) NULL" CanBeNull="true" />
      <Column Name="dtmFechaEmision" Member="FechaEmision" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="dtmFechaVencimiento" Member="FechaVencimiento" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strModalidad" Member="Modalidad" Type="System.String" DbType="Varchar(80) NULL" CanBeNull="true" />
      <Column Name="dblTasaFacial" Member="TasaFacial" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strIndicador" Member="Indicador" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strDescripcionIndicador" Member="DescripcionIndicador" Type="System.String" DbType="Varchar(200) NULL" CanBeNull="true" />
      <Column Name="dblPuntosIndicador" Member="PuntosIndicador" Type="System.Nullable(Of System.Double)" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strTipoTasaFija" Member="TipoTasaFija" Type="System.String" DbType="Varchar(4) NULL" CanBeNull="true" />
      <Column Name="logSeleccionada" Member="Seleccionada" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="tblRN_ContadorReglasAutorizacion">
    <Type Name="tblRN_ContadorReglasAutorizacion" Id="ID6">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strModulo" Member="Modulo" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="intIDNumeroUnico" Member="IDNumeroUnico" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="intIDDocumento" Member="IDDocumento" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="strReglaIncumplida" Member="ReglaIncumplida" Type="System.String" DbType="Varchar(500) NULL" CanBeNull="true" />
      <Column Name="strNombreNivelAprobacion" Member="NombreNivelAprobacion" Type="System.String" DbType="Varchar(200) NULL" CanBeNull="true" />
      <Column Name="strNombreEstado" Member="NombreEstado" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="strEstadoRegla" Member="EstadoRegla" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strCodigoNivelAprobacion" Member="CodigoNivelAprobacion" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strCodigoRegla" Member="CodigoRegla" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strComentarioAprobador" Member="ComentarioAprobador" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strUsuarioAprobador" Member="UsuarioAprobador" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="logErrorSistema" Member="OcurrioErrorSistema" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="strErrorSistema" Member="ErrorSistema" Type="System.String" DbType="Varchar(2) NULL" CanBeNull="true" />
      <Column Name="strDescripcionErrorSistema" Member="DescripcionErrorSistema" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="dtmFechaRegistro" Member="FechaRegistro" Type="System.DateTime" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="dtmActualizacion" Member="Actualizacion" Type="System.DateTime" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strDescripcionReglaIncumplida" Member="DescripcionReglaIncumplida" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strJustificacionUsuarioRegla" Member="JustificacionUsuarioRegla" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strInformacionAdicional" Member="InformacionAdicional" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="logMostrarInformacionAdicional" Member="MostrarInformacionAdicional" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="tblSaldosBancos">
    <Type Name="tblSaldosBancos" Id="ID7">
      <Column Name="intID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lngIdBanco" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="Varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="strNombreSucursal" Type="System.String" DbType="Varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="strNroCuenta" Type="System.String" DbType="Varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="curValor" Type="System.Double" DbType="money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="tblLiquidacionesCliente">
    <Type Name="tblLiquidacionesCliente" Id="ID8">
      <Column Name="intNroLiquidacion" Member="NroLiquidacion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="intParcial" Member="Parcial" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dtmFechaLiquidacion" Member="FechaLiquidacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dtmFechaCumplimiento" Member="FechaCumplimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="strClaseOrden" Member="ClaseOrden" Type="System.String" DbType="Varchar(2) NOT NULL" CanBeNull="false" />
      <Column Name="strNombreClaseOrden" Member="NombreClaseOrden" Type="System.String" DbType="Varchar(30) NULL" CanBeNull="true" />
      <Column Name="dblTotalLiquidacion" Member="TotalLiquidacion" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="logSeleccione" Member="Seleccione" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="tblOrdenesSAERentaFija">
    <Type Name="tblOrdenesSAERentaFija" Id="ID9">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigoReceptor" Member="CodigoReceptor" Type="System.String" DbType="Varchar(17) NOT NULL" CanBeNull="false" />
      <Column Name="dtmFechaReferencia" Member="FechaReferencia" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="intNroLiquidacion" Member="NroLiquidacion" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Member="Cantidad" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dtmFechaCumplimiento" Member="FechaCumplimiento" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="dblPrecio" Member="Precio" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="intDiasCumplimiento" Member="DiasCumplimiento" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="dblTasaNominal" Member="TasaNominal" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strEspecie" Member="Especie" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="dtmFechaEmision" Member="FechaEmision" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strISIN" Member="ISIN" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strTrader" Member="Trader" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strUBICACIONTITULO" Member="UBICACIONTITULO" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strRuedaNegocio" Member="RuedaNegocio" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="dblPrecioLimpio" Member="PrecioLimpio" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dblPrecioSucio" Member="PrecioSucio" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strCondicionesNegociacion" Member="CondicionesNegociacion" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strNombreCondicionesNegociacion" Member="NombreCondicionesNegociacion" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="strIndicador" Member="Indicador" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strNombreIndicador" Member="NombreIndicador" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="dblPuntosIndicador" Member="PuntosIndicador" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strModalidad" Member="Modalidad" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strNombreModalidad" Member="NombreModalidad" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="dtmFechaVencimiento" Member="FechaVencimiento" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="dblTasaInicial" Member="TasaInicial" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strTipoSimultanea" Member="TipoSimultanea" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="dblTasaRepoSimultanea" Member="TasaRepoSimultanea" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strEstadoTitulo" Member="EstadoTitulo" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strMercado" Member="Mercado" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="strClasificacion" Member="Clasificacion" Type="System.String" DbType="Varchar(60) NULL" CanBeNull="true" />
      <Column Name="logSeleccionada" Member="Seleccionada" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="strMensajes" Member="Mensajes" Type="System.String" DbType="varchar(200)" CanBeNull="true" />
      <Column Name="dtmFechaCumplimientoRepo" Member="dtmFechaCumplimientoRepo" Type="System.Nullable(Of Datetime)" DbType="Datetime" CanBeNull="true" />
      <Column Name="dblCantidadRepoSimultanea" Member="CantidadRepoSimultanea" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dblCantidadCaptacion" Member="CantidadCaptacion" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dblCantidadFutura" Member="CantidadFutura" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="OYDPLUS.tblControlProgramacion" Member="tblControlProgramacion">
    <Type Name="tblControlProgramacion" Id="ID10">
      <Column Name="intID" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="strModulo" Member="Modulo" Type="System.String" DbType="varchar(4) NULL" CanBeNull="false" />
      <Column Name="intIDNroDocumento" Member="IDNroDocumento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="logProgramacionActiva" Member="ProgramacionActiva" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="dtmUltimaFechaEjecucion" Member="UltimaFechaEjecucion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strTipoRecurrencia" Member="TipoRecurrencia" Type="System.String" DbType="varchar(4) NULL" CanBeNull="false" />
      <Column Name="logDiariaCadaDia" Member="DiariaCadaDia" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="intDiariaDias" Member="DiariaDias" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="intSemanalNroSemanas" Member="SemanalNroSemanas" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="strSemanalDiasSemana" Member="SemanalDiasSemana" Type="System.String" DbType="varchar(7) NULL" CanBeNull="false" />
      <Column Name="logMensualElDia" Member="MensualElDia" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="intMensualCadaDias" Member="MensualCadaDias" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="intMensualCadaMes" Member="MensualCadaMes" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="strMensualDias" Member="MensualDias" Type="System.String" DbType="varchar(4) NULL" CanBeNull="false" />
      <Column Name="strMensualTipoDia" Member="MensualTipoDia" Type="System.String" DbType="varchar(4) NULL" CanBeNull="false" />
      <Column Name="logAnualElDia" Member="AnualElDia" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="strAnualMeses" Member="AnualMeses" Type="System.String" DbType="varchar(15) NULL" CanBeNull="false" />
      <Column Name="intAnualDia" Member="AnualDia" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="strAnualDias" Member="AnualDias" Type="System.String" DbType="varchar(4) NULL" CanBeNull="false" />
      <Column Name="strAnualTipoDia" Member="AnualTipoDia" Type="System.String" DbType="varchar(4) NULL" CanBeNull="false" />
      <Column Name="dtmFechaInicio" Member="FechaInicio" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strModoFinalizacion" Member="ModoFinalizacion" Type="System.String" DbType="varchar(4) NULL" CanBeNull="false" />
      <Column Name="intRepeticiones" Member="Repeticiones" Type="System.Nullable(Of System.Int32)" DbType="Int NULL" CanBeNull="true" />
      <Column Name="dtmFechaFinalizacion" Member="FechaFinalizacion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="dtmActualzacion" Member="Actualzacion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="varchar(60) NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="OYDPLUS.tblControlProgramacionFechas" Member="tblControlProgramacionFechas">
    <Type Name="tblControlProgramacionFechas" Id="ID11">
      <Column Name="intID" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="intIDControlProgramacion" Member="IDControlProgramacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtmFecha" Member="Fecha" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="logProcesoEjecutado" Member="ProcesoEjecutado" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="logProgramacionActiva" Member="ProgramacionActiva" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="dtmActualzacion" Member="Actualzacion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="varchar(60) NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="OYDPLUS.tblControlProgramacionLog" Member="tblControlProgramacionLog">
    <Type Name="tblControlProgramacionLog" Id="ID12">
      <Column Name="intID" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="intIDControlProgramacionFechas" Member="IDControlProgramacionFechas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strMensaje" Member="Mensaje" Type="System.String" DbType="varchar(500) NULL" CanBeNull="false" />
      <Column Name="logExitoso" Member="Exitoso" Type="System.Boolean" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="dtmActualzacion" Member="Actualzacion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="varchar(60) NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="tblControlProgramacionGeneracionFechas">
    <Type Name="tblControlProgramacionGeneracionFechas" Id="ID13">
      <Column Name="intID" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dtmFecha" Member="Fecha" Type="System.Nullable(Of System.DateTime)" DbType="DateTime NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="OYDPLUS.tblValidacionEliminarRegistro" Member="ValidacionEliminarRegistro">
    <Type Name="ValidacionEliminarRegistro" Id="ID14">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="logPermitirRealizarAccion" Member="PermitirRealizarAccion" Type="System.Boolean" DbType="BIT NOT NULL" CanBeNull="false" />
      <Column Name="strMensaje" Member="Mensaje" Type="System.String" DbType="Varchar(500) NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="tblMensajes">
    <Type Name="tblMensajes" Id="ID15">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strTitulo" Member="Titulo" Type="System.String" DbType="Varchar(200) NULL" CanBeNull="false" />
      <Column Name="strValor" Member="Valor" Type="System.String" DbType="Varchar(200) NULL" CanBeNull="true" />
      <Column Name="strColor" Member="Color" Type="System.String" DbType="Varchar(80) NULL" CanBeNull="true" />
      <Column Name="strDescripcion" Member="Descripcion" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="OYDPLUS.tblConfiguracionesAdicionalesReceptor" Member="tblConfiguracionesAdicionalesReceptor">
    <Type Name="tblConfiguracionesAdicionalesReceptor" Id="ID16">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigoReceptor" Member="CodigoReceptor" Type="System.String" DbType="Varchar(4) NOT NULL" CanBeNull="false" />
      <Column Name="strTipoOrden" Member="TipoOrden" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="strExtensionDefecto" Member="ExtensionDefecto" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strTipoOrdenDefecto" Member="TipoOrdenDefecto" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="dtmActualizacion" Member="Actualizacion" Type="System.DateTime" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="OYDPLUS.tblParametrosReceptor" Member="tblParametrosReceptor">
    <Type Name="tblParametrosReceptor" Id="ID17">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigoReceptor" Member="CodigoReceptor" Type="System.String" DbType="Varchar(4) NOT NULL" CanBeNull="false" />
      <Column Name="strTopico" Member="Topico" Type="System.String" DbType="Varchar(20) NOT NULL" CanBeNull="false" />
      <Column Name="strValor" Member="Valor" Type="System.String" DbType="Varchar(80) NOT NULL" CanBeNull="false" />
      <Column Name="strDescripcion" Member="Descripcion" Type="System.String" DbType="Varchar(250) NOT NULL" CanBeNull="false" />
      <Column Name="intPrioridad" Member="Prioridad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtmActualizacion" Member="Actualizacion" Type="System.DateTime" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="tblReceptoresUsuario">
    <Type Name="tblReceptoresUsuario" Id="ID18">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigoReceptor" Member="CodigoReceptor" Type="System.String" DbType="Varchar(4) NOT NULL" CanBeNull="false" />
      <Column Name="strNombre" Member="Nombre" Type="System.String" DbType="Varchar(100) NOT NULL" CanBeNull="false" />
      <Column Name="intPrioridad" Member="Prioridad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="Varchar(100) NOT NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="CombosReceptor">
    <Type Name="CombosReceptor" Id="ID19">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Retorno" Type="System.String" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" CanBeNull="false" />
      <Column Name="Prioridad" Type="System.Nullable(Of System.Int32)" CanBeNull="true" />
      <Column Name="IntId" Type="System.Int32"   CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="OYDPLUS.tblEspeciesXTipoNegocio" Member="tblEspeciesXTipoNegocio">
    <Type Name="tblEspeciesXTipoNegocio" Id="ID20">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strTipoNegocio" Member="TipoNegocio" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="false" />
      <Column Name="strIDEspecie" Member="IDEspecie" Type="System.String" DbType="Varchar(15) NOT NULL" CanBeNull="false" />
      <Column Name="logManejaISIN" Member="ManejaISIN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="dblMaxCantidad" Member="MaxCantidad" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="OYDPLUS.tblTipoNegocioReceptor" Member="tblTipoNegocioReceptor">
    <Type Name="tblTipoNegocioReceptor" Id="ID21">
      <Column Name="intID" Member="ID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigoReceptor" Member="CodigoReceptor" Type="System.String" DbType="Varchar(4) NOT NULL" CanBeNull="false" />
      <Column Name="strCodigoTipoNegocio" Member="CodigoTipoNegocio" Type="System.String" DbType="Varchar(4) NOT NULL" CanBeNull="false" />
      <Column Name="strNombreTipoNegocio" Member="NombreTipoNegocio" Type="System.String" DbType="Varchar(100) NOT NULL" CanBeNull="false" />
      <Column Name="dblValorMaxnegociacion" Member="ValorMaxnegociacion" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="intPrioridad" Member="Prioridad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dblPorcentajeComision" Member="PorcentajeComision" Type="System.Double" DbType="Float NULL" CanBeNull="false" />
      <Column Name="dblValorComision" Member="ValorComision" Type="System.Double" DbType="Float NULL" CanBeNull="false" />
      <Column Name="dtmActualizacion" Member="Actualizacion" Type="System.DateTime" DbType="DateTime NULL" CanBeNull="true" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="ItemCombosSistemaExterno">
    <Type Name="ItemCombosSistemaExterno" Id="ID22">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Retorno" Type="System.String" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" CanBeNull="false" />
      <Column Name="Prioridad" Type="System.Nullable(Of System.Int32)" CanBeNull="true" />
      <Column Name="IDDependencia1" Type="System.Nullable(Of System.Int32)" CanBeNull="true" />
      <Column Name="IDDependencia2" Type="System.Nullable(Of System.Int32)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSSBMensajesProcesados" Member="MensajesProcesados">
    <Type Name="MensajesProcesados" Id="ID23">
      <Column Name="intID" Member="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="guidConversation" Member="IDConversacion" Storage="_IdConversacion" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="strNombreServicio" Member="NombreServicio" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="dtmActualizacion" Member="FechaActualizacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="strSistemaOrigen" Member="SistemaOrigen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="strSistemaDestino" Member="SistemaDestino" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="strAccion" Member="Accion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="strProcedimiento" Member="Procedimiento" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MessageBody" Member="Mensaje" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="intEstado" Member="Estado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>

  <Function Name="dbo.uspA2utils_CargarCombos" Method="uspA2utils_CargarCombos">
    <Parameter Name="pstrListaNombreCombos" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ConsultarSaldosCliente" Method="uspOyDNet_ConsultarSaldosCliente">
    <Parameter Name="pstrIDComitente" Type="System.String" DbType="VARCHAR(17)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <Parameter Name="pstrTipoProducto" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrCarteraColectivaFondos" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pintNroEncargoFondos" Type="System.String" DbType="VARCHAR(20)" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.uspOyDNet_ConsultarPortafolioCliente" Method="uspOyDNet_ConsultarPortafolioCliente">
    <Parameter Name="pstrTipoNegocio" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrIDComitente" Type="System.String" DbType="VARCHAR(17)" />
    <Parameter Name="pstrEspecie" Type="System.String" DbType="VARCHAR(25)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="OYDPLUSOrdenes.uspOyDNet_ConsultarOrdenesBolsaReceptor" Method="uspOyDNet_ConsultarOrdenesBolsaReceptorAcciones">
    <Parameter Name="pstrCodigoReceptor" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="VARCHAR(1)" />
    <Parameter Name="pstrOperacion" Type="System.String" DbType="VARCHAR(1)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <Parameter Name="pstrTipoNegocio" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrLiquidacionesHabilitar" Type="System.String" DbType="VARCHAR(MAX)" />
    <ElementType IdRef="ID4" />
  </Function>
  <!--Liquidaciones para Complementacion por Precio Promedio Carga Masiva JDOL20170309-->
  <Function Name="OYDPLUSOrdenes.uspOyDNet_ConsultarOrdenesBolsaReceptorAccionesPrecioPromedio" Method="uspOyDNet_ConsultarOrdenesBolsaReceptorAccionesPrecioPromedio">
    <Parameter Name="pstrOperacion" Type="System.String" DbType="VARCHAR(1)" />
    <Parameter Name="pstrEspecie" Type="System.String" DbType="VARCHAR(1)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID4" />
  </Function>
    <!--Complementacion por Precio Promedio Carga Masiva JDOL20170309-->
    <Function Name="OYDPLUSOrdenes.uspOyDNet_ConsultarOrdenesBolsaReceptor" Method="uspOyDNet_ConsultarOrdenesBolsaReceptorRentaFija">
    <Parameter Name="pstrCodigoReceptor" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="VARCHAR(1)" />
    <Parameter Name="pstrOperacion" Type="System.String" DbType="VARCHAR(1)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <Parameter Name="pstrTipoNegocio" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrLiquidacionesHabilitar" Type="System.String" DbType="VARCHAR(MAX)" />
    <ElementType IdRef="ID9" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ConsultarOperacionesXCumplir" Method="uspOyDNet_ConsultarOperacionesXCumplir">
    <Parameter Name="pstrTipoNegocio" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrTipoOperacion" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrIDComitente" Type="System.String" DbType="VARCHAR(17)" />
    <Parameter Name="pstrEspecie" Type="System.String" DbType="VARCHAR(25)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID5" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ConsultarEstadosDocumento" Method="uspOyDNet_ConsultarEstadosDocumento">
    <Parameter Name="pintNumeroUnico" Type="System.Int32" DbType="Int" />
    <Parameter Name="pintNumeroDocumento" Type="System.Int32" DbType="Int" />
    <Parameter Name="pstrModulo" Type="System.String" DbType="Varchar(30)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID6" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ControlProgramacion_ObtenerFechas" Method="uspOyDNet_ControlProgramacion_ObtenerFechas">
    <Parameter Name="pstrTipoRecurrencia" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="plogDiariaCadaDia" Type="System.Boolean" DbType="Bit"/>
    <Parameter Name="pintDiariaDias" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pintSemanalNroSemanas" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pstrSemanalDiasSemana" Type="System.String" DbType="Varchar(7)"/>
    <Parameter Name="plogMensualElDia" Type="System.Boolean" DbType="Bit"/>
    <Parameter Name="pintMensualCadaDias" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pintMensualCadaMes" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pstrMensualDias" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pstrMensualTipoDia" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="plogAnualElDia" Type="System.Boolean" DbType="Bit"/>
    <Parameter Name="pstrAnualMeses" Type="System.String" DbType="Varchar(15)"/>
    <Parameter Name="pintAnualDia" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pstrAnualDias" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pstrAnualTipoDia" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pdtmFechaInicio" Type="System.Nullable(Of System.DateTime)" DbType="DateTime"/>
    <Parameter Name="pstrModoFinalizacion" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pintRepeticiones" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pdtmFechaFinalizacion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime"/>
    <ElementType IdRef="ID13" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ControlProgramacion_Actualizar" Method="uspOyDNet_ControlProgramacion_Actualizar">
    <Parameter Name="pstrModulo" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pintIDNroDocumento" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pstrTipoRecurrencia" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="plogDiariaCadaDia" Type="System.Boolean" DbType="Bit"/>
    <Parameter Name="pintDiariaDias" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pintSemanalNroSemanas" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pstrSemanalDiasSemana" Type="System.String" DbType="Varchar(7)"/>
    <Parameter Name="plogMensualElDia" Type="System.Boolean" DbType="Bit"/>
    <Parameter Name="pintMensualCadaDias" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pintMensualCadaMes" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pstrMensualDias" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pstrMensualTipoDia" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="plogAnualElDia" Type="System.Boolean" DbType="Bit"/>
    <Parameter Name="pstrAnualMeses" Type="System.String" DbType="Varchar(15)"/>
    <Parameter Name="pintAnualDia" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pstrAnualDias" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pstrAnualTipoDia" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pdtmFechaInicio" Type="System.Nullable(Of System.DateTime)" DbType="DateTime"/>
    <Parameter Name="pstrModoFinalizacion" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pintRepeticiones" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pdtmFechaFinalizacion" Type="System.Nullable(Of System.DateTime)" DbType="DateTime"/>
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="Varchar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32"/>
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ControlProgramacion_Consultar" Method="uspOyDNet_ControlProgramacion_Consultar">
    <Parameter Name="pstrModulo" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pintIDNroDocumento" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="Varchar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID10" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ControlProgramacion_ConsultarFechas" Method="uspOyDNet_ControlProgramacion_ConsultarFechas">
    <Parameter Name="pintIDControlProgramacion" Type="System.Int32" DbType="Int"/>
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="Varchar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID11" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ControlProgramacion_ConsultarLog" Method="uspOyDNet_ControlProgramacion_ConsultarLog">
    <Parameter Name="pintIDFechaControlProgramacion" Type="System.Int32" DbType="Int"/>
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="Varchar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID12" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ControlProgramacion_Inactivar" Method="uspOyDNet_ControlProgramacion_Inactivar">
    <Parameter Name="pstrModulo" Type="System.String" DbType="Varchar(4)"/>
    <Parameter Name="pintIDNroDocumento" Type="System.Nullable(Of System.Int32)" DbType="Int"/>
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="Varchar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32"/>
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ControlProgramacion_InactivarFechas" Method="uspOyDNet_ControlProgramacion_InactivarFechas">
    <Parameter Name="pstrIDFechasInactivar" Type="System.String" DbType="Varchar(500)"/>
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="Varchar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32"/>
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_rptSaldosBancos_PLUS" Method="uspOyDNet_rptSaldosBancos_PLUS">
    <Parameter Name="pintBancoIni" Type="System.Int32" DbType="int" />
    <Parameter Name="pintBancoFin" Type="System.Int32" DbType="int" />
    <Parameter Name="pdtmFecha" Type="System.Datetime" DbType="datetime" />
    <Parameter Name="pintEstado" Type="System.Int32" DbType="smallint" />
    <Parameter Name="pstrLogUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="pstrMaquina" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrOpcion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrProceso" Type="System.String" DbType="VarChar(60)" />
    <ElementType IdRef="ID7" />
  </Function>
  <Function Name="OYDPLUSOrdenes.uspOyDNet_ConsultarLiquidacionesCliente" Method="uspOyDNet_ConsultarLiquidacionesCliente">
    <Parameter Name="pstrIDComitente" Type="System.String" DbType="Varchar(17)" />
    <Parameter Name="pstrTipoOperacion" Type="System.String" DbType="Varchar(2)" />
    <Parameter Name="pdtmFechaInicial" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pdtmFechaFinal" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID8" />
  </Function>
  <Function Name="dbo.uspOyDNet_Maestros_ValidarEliminarRegistro" Method="uspOyDNet_Maestros_ValidarEliminarRegistro">
    <Parameter Name="pstrTablas" Type="System.String" DbType="varchar(500)" />
    <Parameter Name="pstrCampos" Type="System.String" DbType="varchar(500)" />
    <Parameter Name="pstrValores" Type="System.String" DbType="varchar(500)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID14" />
  </Function>
  <Function Name="dbo.uspOyDNet_Maestros_ValidarDuplicidadRegistro" Method="uspOyDNet_Maestros_ValidarDuplicidadRegistro">
    <Parameter Name="pstrNombreTabla" Type="System.String" DbType="varchar(500)" />
    <Parameter Name="pstrCampos" Type="System.String" DbType="varchar(500)" />
    <Parameter Name="pstrValores" Type="System.String" DbType="varchar(500)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID14" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_CargarMensajeDinamico" Method="uspOyDNet_CargarMensajeDinamico">
    <Parameter Name="pstrOpcion" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrIDReceptor" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrIDCliente" Type="System.String" DbType="VARCHAR(17)" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="VARCHAR(25)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID15" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_CargarConfiguracionReceptor" Method="uspOyDNet_CargarConfiguracionReceptor">
    <Parameter Name="pstrIDReceptor" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID16" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_CargarParametrosReceptor" Method="uspOyDNet_CargarParametrosReceptor">
    <Parameter Name="pstrIDReceptor" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID17" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_CargarReceptoresUsuario" Method="uspOyDNet_CargarReceptoresUsuario">
    <Parameter Name="plogCargarReceptorActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="pstrUsuarioConsulta" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID18" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_CargarCombosReceptor" Method="uspOyDNet_CargarCombosReceptor">
    <Parameter Name="pstrIDReceptor" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID19" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_CargarEspeciesTipoNegocio" Method="uspOyDNet_CargarEspeciesTipoNegocio">
    <Parameter Name="pstrTipoNegocio" Type="System.String" DbType="VARCHAR(60)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID20" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_CargarTipoNegocioReceptor" Method="uspOyDNet_CargarTipoNegocioReceptor">
    <Parameter Name="pstrIDReceptor" Type="System.String" DbType="VARCHAR(4)" />
    <Parameter Name="pstrModulo" Type="System.String" DbType="VARCHAR(50)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID21" />
  </Function>
  <Function Name="dbo.uspSSBEnviarMensaje" Method="uspSSBEnviarMensaje">
    <Parameter Name="pstrMensaje" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="pguidConversacion" Type="System.Guid" DbType="UniqueIdentifier" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_RetornarListaInformacionDeXML" Method="RetornarInformacionCombosSistemaExterno">
    <Parameter Name="pstrTipo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pstrMensaje" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType IdRef="ID22" />
  </Function>
  <Function Name="OYDPLUS.uspOyDNet_ObtenerFechaServidor" Method="uspOyDNet_ObtenerFechaServidor">
    <Parameter Name="pdtmFechaHoraActual" Type="System.DateTime" DbType="DateTime" Direction="InOut" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(100)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <Return Type="System.Int32"/>
  </Function>
</Database>