'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_AprobacionPreordenesConsultar
    Public Property intIDOrden As Integer
    Public Property intConsecutivo As Nullable(Of Integer)
    Public Property intVersion As Nullable(Of Integer)
    Public Property intIDComitente As String
    Public Property strTipo As String
    Public Property dtmOrden As Nullable(Of Date)
    Public Property dtmVigenciaHasta As Nullable(Of Date)
    Public Property strEstado As String
    Public Property dtmEstado As Nullable(Of Date)
    Public Property strProducto As String
    Public Property strClasificacionNegocioNombre As String
    Public Property strTipoOperacionNombre As String
    Public Property intIDMoneda As Nullable(Of Integer)
    Public Property strTipoReferencia As String
    Public Property intIDFormulario As Nullable(Of Integer)
    Public Property intIDNumeral As Nullable(Of Integer)
    Public Property strMesa As String
    Public Property strObservaciones As String
    Public Property dblCantidad As Nullable(Of Double)
    Public Property dblPrecio As Nullable(Of Double)
    Public Property intIDMonedaIntermedia As Nullable(Of Integer)
    Public Property dblPrecioIntermedio As Nullable(Of Double)
    Public Property dblSpreadComision As Nullable(Of Double)
    Public Property dblValorBruto As Nullable(Of Double)
    Public Property dblValorNeto As Nullable(Of Double)
    Public Property dblValorTRM As Nullable(Of Double)
    Public Property dblPrecioMonedaNegociada As Nullable(Of Double)
    Public Property dblValorGMF As Nullable(Of Double)
    Public Property strFolio As String
    Public Property strSistemaOperacionNegociada As String
    Public Property strFolioSETFX As String
    Public Property dblPorcentajeReceptor As Nullable(Of Double)
    Public Property strIDReceptor As String
    Public Property strReceptorNombre As String
    Public Property strMonedaNombre As String
    Public Property strTipoReferenciaNombre As String
    Public Property strFormulario As String
    Public Property strNumeral As String
    Public Property strMesaNombre As String
    Public Property strMonedaIntermediaNombre As String
    Public Property strUsuarioCreacion As String
    Public Property dtmCreacion As Nullable(Of Date)
    Public Property dtmActualizacion As Nullable(Of Date)
    Public Property Aprobar As Nullable(Of Boolean)
    Public Property logDesaprobar As Nullable(Of Boolean)

End Class
