'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_OrdenesPendientesCumplir
    Public Property intIDOrden As Integer
    Public Property intConsecutivo As Long
    Public Property intVersion As Integer
    Public Property intIDComitente As String
    Public Property strTipo As String
    Public Property dtmOrden As Date
    Public Property dtmVigenciaHasta As Date
    Public Property strEstado As String
    Public Property dtmEstado As Date
    Public Property strProducto As String
    Public Property strClasificacionNegocio As String
    Public Property strTipoOperacionNombre As String
    Public Property strClasificacionNegocioNombre As String
    Public Property strUsuarioCreacion As String
    Public Property dtmCreacion As Date
    Public Property strUsuario As String
    Public Property dtmActualizacion As Date
    Public Property intIDMoneda As Integer
    Public Property strTipoReferencia As String
    Public Property intIDFormulario As Nullable(Of Integer)
    Public Property intIDNumeral As Nullable(Of Integer)
    Public Property strMesa As String
    Public Property strObservaciones As String
    Public Property dblCantidad As Double
    Public Property dblPrecio As Double
    Public Property intIDMonedaIntermedia As Integer
    Public Property dblPrecioIntermedio As Double
    Public Property dblSpreadComision As Double
    Public Property dblValorBruto As Double
    Public Property dblValorNeto As Double
    Public Property dblValorTRM As Double
    Public Property dblPrecioMonedaNegociada As Double
    Public Property dblValorGMF As Nullable(Of Double)
    Public Property strFolio As String
    Public Property strSistemaOperacionNegociada As String
    Public Property strFolioSETFX As String
    Public Property dblPorcentajeReceptor As Nullable(Of Double)
    Public Property strIDReceptor As String
    Public Property strReceptorNombre As String
    Public Property strMonedaNombre As String
    Public Property strTipoReferenciaNombre As String
    Public Property strFormulario As String
    Public Property strNumeral As String
    Public Property strMesaNombre As String
    Public Property strMonedaIntermediaNombre As String

End Class
