'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_MultimonedaCambioCruzado
    Public Property intIDParesDeDivisas As Integer
    Public Property logCambioCruzado As Nullable(Of Boolean)
    Public Property intIDMonedaOrigen As Nullable(Of Integer)
    Public Property intIDMonedaCambioCruzado As Nullable(Of Integer)
    Public Property numComisionMonedaOrigen As Decimal
    Public Property numComisionMonedaDestino As Decimal
    Public Property dblValor As Double
    Public Property dblValorUSD As Double

End Class
