'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblCierreDivisas
    Public Property intId As Integer
    Public Property dtmCierre As Date
    Public Property intIDMoneda As Integer
    Public Property strMesa As String
    Public Property dtmActualizacion As Nullable(Of Date)
    Public Property strUsuario As String
    Public Property logCierre As Boolean

End Class
