'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblValidacionesCargaOperaciones
    Public Property intIdValidacion As Integer
    Public Property strTipoMensaje As String
    Public Property strCodMensaje As String
    Public Property strCampo As String
    Public Property strMensaje As String
    Public Property logInconsitencia As Boolean
    Public Property intOrden As Short
    Public Property intIDRegistro As Nullable(Of Integer)
    Public Property dtmRegistro As Nullable(Of Date)
    Public Property intFila As Nullable(Of Integer)
    Public Property intColumna As Nullable(Of Integer)

End Class
