'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_OperacionesValoracion
    Public Property intiDConsecutivo As Integer
    Public Property intDiasVencimiento As Nullable(Of Integer)
    Public Property dtmFechaCumplimiento As Date
    Public Property dblFactorCapitalizacionMoneda1 As Nullable(Of Double)
    Public Property dblFactorCapitalizacionMoneda2 As Nullable(Of Double)
    Public Property dblTasaFWDMercado As Nullable(Of Double)
    Public Property dblValorDerechoCOP As Nullable(Of Double)
    Public Property dblValoObligacionCOP As Nullable(Of Double)
    Public Property dblValorMercadoCOP As Nullable(Of Double)
    Public Property dblValorDerechoUSD As Nullable(Of Double)
    Public Property dblValorObligacionUSD As Nullable(Of Double)
    Public Property dblValorMercadoUSD As Nullable(Of Double)
    Public Property dtmFechaValoracion As Date
    Public Property dblValorPresentePYG As Nullable(Of Double)
    Public Property dblPrecio As Nullable(Of Double)
    Public Property dblCantidad As Nullable(Of Double)
    Public Property strTipo As String
    Public Property strClasificacionNegocio As String
    Public Property FechaNegociacion As String
    Public Property intIDComitente As String
    Public Property strTipoCumplimiento As String
    Public Property strFixing As String
    Public Property dblTRM As Nullable(Of Double)
    Public Property Moneda1 As String
    Public Property Spot As Nullable(Of Double)
    Public Property dblDevaluacion As Nullable(Of Double)
    Public Property Moneda2 As String
    Public Property dblValorBruto As Double
    Public Property strObjetivo As String
    Public Property strProducto As String
    Public Property strEstado As String
    Public Property strNitTercero As String
    Public Property strNitFondo As String

End Class
