'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_OrdenesDivisasSectorReal
    Public Property id As Integer
    Public Property tipo_operacion As String
    Public Property mercado As Integer
    Public Property origen As String
    Public Property sub_mercado As String
    Public Property operacion As String
    Public Property id_usuario As String
    Public Property fecha_transaccion As Date
    Public Property hora_transaccion As System.TimeSpan
    Public Property precio As Double
    Public Property monto_transado As Double
    Public Property moneda_monto As String
    Public Property moneda_contraparte As String
    Public Property tipo_identificacion As String
    Public Property identificacion_contraparte As String
    Public Property comentario As String
    Public Property sistema_origen As String
    Public Property texto_origen As String
    Public Property sistema_negociacion As String
    Public Property tasa_pool As Nullable(Of Double)
    Public Property clase_id_comitente_contraparte As String
    Public Property id_comitente_contraparte As String
    Public Property bandera_tercer_offshore As String
    Public Property Enviado As Boolean
    Public Property Enviar As Boolean
    Public Property fecha_valor As Integer
    Public Property codigo_especial_fiduciario As String
    Public Property fecha_inicio_contrato As String
    Public Property fecha_fin_contrato As String
    Public Property fecha_pago As String
    Public Property tipo_registro As String
    Public Property inicio_primer_flujo As Integer
    Public Property calendario As String
    Public Property fecha_primera_amortizacion As String
    Public Property modfiy_following_business As String
    Public Property valor_amortizacion As String
    Public Property tipo_amortizacion As String
    Public Property tipo_tasa_1 As String
    Public Property tasa_interes As String
    Public Property base_dias_1 As String
    Public Property codigo_tasa_referencial_extendido As String
    Public Property spread_tasa As String
    Public Property tipo_tasa_2 As String
    Public Property tasa_interes_2 As String
    Public Property codigo_tasa_referencial_extendido_2 As String
    Public Property spread_tasa_2 As String
    Public Property base_dias_2 As String
    Public Property periodo_interes_2 As String
    Public Property tasa_referencial As String
    Public Property periodo_interes As String
    Public Property cumplimiento As String
    Public Property tasa_interes_moneda_monto As String
    Public Property tasa_interes_moneda_contraparte As String
    Public Property condicion_ejercicio As String
    Public Property precio_ejercicio As String
    Public Property volatilidad As String
    Public Property precio_spot As String
    Public Property prima As String
    Public Property tipo_opcion As String
    Public Property tipo_swap As String
    Public Property numeral_cambiario As Integer
    Public Property forma_de_pago As String
    Public Property tipo_de_operacion_complementaria As String
    Public Property porcentaje_comision As String

End Class
