'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblOrdenesReceptores
    Public Property intID As Integer
    Public Property intIDReceptor As Integer
    Public Property logLider As Boolean
    Public Property intIDOrden As Integer
    Public Property dblPorcentaje As Nullable(Of Double)
    Public Property strUsuario As String
    Public Property dtmActualizacion As Date

End Class
