'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_OrdenesValoracionHistoricoConsultar
    Public Property Cantidad As Nullable(Of Double)
    Public Property Precio As Nullable(Of Double)
    Public Property ValorDerechoCOP As Nullable(Of Decimal)
    Public Property ValorObligacionCOP As Nullable(Of Decimal)
    Public Property ValorMercadoCOP As Nullable(Of Decimal)
    Public Property ValorDerechoUSD As Nullable(Of Decimal)
    Public Property ValorObligacionUSD As Nullable(Of Decimal)
    Public Property ValorMercadoUSD As Nullable(Of Decimal)
    Public Property Fechavaloración As Date

End Class
