'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblOrdenes
    Public Property intID As Integer
    Public Property intConsecutivo As Long
    Public Property intIDComitente As String
    Public Property strTipo As String
    Public Property dtmOrden As Date
    Public Property dtmVigenciaHasta As Date
    Public Property strEstado As String
    Public Property dtmEstado As Date
    Public Property strUsuario As String
    Public Property dtmActualizacion As Date
    Public Property intVersion As Integer
    Public Property strProducto As String
    Public Property strClasificacionNegocio As String
    Public Property strUsuarioCreacion As String
    Public Property dtmCreacion As Date
    Public Property strTipoDerivado As String
    Public Property strFixing As String
    Public Property strTipoOperacion As String
    Public Property strObjetivo As String
    Public Property strTpoContraparte As String

    Public Overridable Property tblOrdenesDivisas As ICollection(Of tblOrdenesDivisas) = New HashSet(Of tblOrdenesDivisas)
    Public Overridable Property tblOrdenesDivisasMultimonedas As ICollection(Of tblOrdenesDivisasMultimonedas) = New HashSet(Of tblOrdenesDivisasMultimonedas)
    Public Overridable Property tblOrdenesDivisasDatosGiros As ICollection(Of tblOrdenesDivisasDatosGiros) = New HashSet(Of tblOrdenesDivisasDatosGiros)

End Class
