<?xml version="1.0" encoding="utf-8"?>
<Database EntityNamespace="CFTitulosNet" Class="CF_TitulosNetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <!--***************************************************************************************-->
  <!--Titulos-->
  <!--***************************************************************************************-->
  <Table Name="" Member="TitulosCompras">
    <Type Name="TitulosCompras" Id="ID15">
      <Column Name="intIDComprasXDescargar" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strLiq_Parcial" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strClaseOrden" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strTipo" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="lngIDComitente" Type="System.String" DbType="Varchar(17) NULL" CanBeNull="true" />
      <Column Name="lngIDCuentaDeceval" Type="System.Int32" DbType="int NOT NULL" CanBeNull="true" />
      <Column Name="strFondo_Descripcion" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strIDEspecie" Type="System.String" DbType="Varchar(15) NULL" CanBeNull="true" />
      <Column Name="dtmLiquidacion" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dtmCumplimientoTitulo" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dtmEmision" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dtmVencimiento" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dblTasaDescuento" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strTipoTasaFija" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="strIndicadorEconomico" Type="System.String" DbType="Varchar(2) NULL" CanBeNull="true" />
      <Column Name="dblPuntosIndicador" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strModalidad" Type="System.String" DbType="Varchar(2) NULL" CanBeNull="true" />
      <Column Name="curPrecio" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="curTotalLiq" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="lngPlazo" Type="System.Int32" DbType="int NOT NULL" CanBeNull="true" />
      <Column Name="strTipoDeOferta_Descripcion" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strClase_Descripcion" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="intCantidadRegistros" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="InfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="TitulosVentas">
    <Type Name="TitulosVentas" Id="ID16">
      <Column Name="intIDVentasXDescargar" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strLiq_Parcial" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strClaseOrden" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strTipo" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="lngIDComitente" Type="System.String" DbType="Varchar(17) NULL" CanBeNull="true" />
      <Column Name="lngIDCuentaDeceval" Type="System.Int32" DbType="int NOT NULL" CanBeNull="true" />
      <Column Name="strFondo_Descripcion" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strIDEspecie" Type="System.String" DbType="Varchar(15) NULL" CanBeNull="true" />
      <Column Name="dtmLiquidacion" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dtmCumplimientoTitulo" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dtmEmision" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dtmVencimiento" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dblTasaDescuento" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strTipoTasaFija" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="strIndicadorEconomico" Type="System.String" DbType="Varchar(2) NULL" CanBeNull="true" />
      <Column Name="dblPuntosIndicador" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strModalidad" Type="System.String" DbType="Varchar(2) NULL" CanBeNull="true" />
      <Column Name="curPrecio" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="curTotalLiq" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="lngPlazo" Type="System.Int32" DbType="int NOT NULL" CanBeNull="true" />
      <Column Name="strTipoDeOferta_Descripcion" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strClase_Descripcion" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="intCantidadRegistros" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="logCruzarLiquidacionVenta" Type="System.Nullable(of System.Boolean)" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="intIDLiquidaciones" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="strOrigen" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="InfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId1" />
    <UpdateFunction FunctionId="FunctionId1" />
  </Table>
  <Table Name="" Member="TitulosCruce">
    <Type Name="TitulosCruce" Id="ID17">
      <Column Name="intIDCruceTitulosPortafolio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lngIdRecibo" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="lngSecuencia" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="lngIDComitente" Type="System.String" DbType="Varchar(17) NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dblCantidadPedida" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strIDEspecie" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strLiq_Parcial" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strClase" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="strTipo" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="strTipoDeOferta" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="dtmLiquidacion" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dtmCumplimiento" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dtmEmision" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dtmVencimiento" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dblTasa" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strIndicadorEconomico" Type="System.String" DbType="Varchar(2) NULL" CanBeNull="true" />
      <Column Name="dblPuntosIndicador" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strModalidad" Type="System.String" DbType="Varchar(2) NULL" CanBeNull="true" />
      <Column Name="strObservaciones" Type="System.String" DbType="Varchar(15) NULL" CanBeNull="true" />
      <Column Name="dblLiq_Cantidad" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="intCruzar" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="InfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="TitulosPortafolio">
    <Type Name="TitulosPortafolio" Id="ID18">
      <Column Name="intIDPortafolioCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lngIdRecibo" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="lngSecuencia" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="lngIDComitente" Type="System.String" DbType="Varchar(17) NULL" CanBeNull="true" />
      <Column Name="strNombre" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strNroDocumento" Type="System.String" DbType="Varchar(15) NULL" CanBeNull="true" />
      <Column Name="lngIdCuentaDeceval" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="strDescripcionFondo" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strIDEspecie" Type="System.String" DbType="Varchar(20) NULL" CanBeNull="true" />
      <Column Name="strDescripcionEstadoActual" Type="System.String" DbType="Varchar(100) NULL" CanBeNull="true" />
      <Column Name="strLiq_Parcial" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="dtmLiquidacion" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="strTipoLiquidacion" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="dtmEmision" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dtmVencimiento" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dblTasaDescuento" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strTipoTasaFija" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="strIndicadorEconomico" Type="System.String" DbType="Varchar(2) NULL" CanBeNull="true" />
      <Column Name="dblPuntosIndicador" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strTipoDeOferta" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="strClase" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="curTotalLiq" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="strDescripcionModalidad" Type="System.String" DbType="Varchar(50) NULL" CanBeNull="true" />
      <Column Name="strCruce" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="strEstadoActual" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="strMotivoBloqueo" Type="System.String" DbType="Varchar(1) NULL" CanBeNull="true" />
      <Column Name="logCruzarPortafolio" Type="System.Nullable(of System.Boolean)" DbType="Bit NULL" CanBeNull="true" />
      <Column Name="intIDDetalleCustodias" Type="System.Int32" DbType="int NULL" CanBeNull="true" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="InfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <UpdateFunction FunctionId="FunctionId2" />
  </Table>
  <!--***************************************************************************************-->
  <!--RespuestaArchivoImportacion-->
  <!--***************************************************************************************-->
  <Table Name="" Member="RespuestaArchivoImportacion">
    <Type Name="RespuestaArchivoImportacion" Id="ID19">
      <Column Name="ID" Type="System.Int32" DbType="Int" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="Mensaje" Type="System.String" DbType="Varchar(5000)" CanBeNull="true" />
      <Column Name="Exitoso" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="Fila" Type="System.Nullable(Of System.Int32)" DbType="Int" CanBeNull="true" />
      <Column Name="Columna" Type="System.Nullable(Of System.Int32)" DbType="Int" CanBeNull="true" />
      <Column Name="NroProceso" Type="System.Nullable(Of System.Double)" DbType="Float" CanBeNull="true" />
      <Column Name="Campo" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="lngOperacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <!--***************************************************************************************-->
  <!--DECEVAL-->
  <!--***************************************************************************************-->
  <Table Name="" Member="tblResultadoEnvioArchivo">
    <Type Name="tblResultadoEnvioArchivo" Id="ID05">
      <Column Name="intID" Member="ID" IsDbGenerated="true" IsPrimaryKey="true" Type="System.Int32" DbType="Int NOT NULL IDENTITY" CanBeNull="false" />
      <Column Name="logExitoso" Member="logExitoso" Type="System.Boolean" DbType="bit null" CanBeNull="true" />
      <Column Name="strMensaje" Member="Mensaje" Type="System.string" DbType="varchar(500)" CanBeNull="true" />
      <Column Name="intIDArchivoInsertado" Member="IDArchivoInsertado" Type="System.Nullable(Of System.Int32)" DbType="int" CanBeNull="true" />
      <Column Name="strNombreArchivo" Member="NombreArchivo" Type="System.string" DbType="varchar(500)" CanBeNull="true" />
      <Column Name="logEjecucionAutomatica" Member="EjecucionAutomatica" Type="System.Boolean" DbType="bit" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <!--***************************************************************************************-->
  <!--ConceptoRetencion-->
  <!--***************************************************************************************-->
  <Table Name="CF.tblConceptoRetencion" Member="ConceptoRetencion">
    <Type Name="ConceptoRetencion" Id="ConceptoRetencion">
      <Column Name="intIDConceptoRetencion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strCodigo" Type="System.String" DbType="VARCHAR(50) NOT NULL" CanBeNull="true" />
      <Column Name="strDescripcion" Type="System.String" DbType="VARCHAR(100) NULL" CanBeNull="true" />
      <Column Name="dblPorcentajeRetencion" Type="System.Double" DbType="FLOAT NULL" CanBeNull="true" />
      <Column Name="logGravado" Type="System.Nullable(of System.Boolean)" DbType="Bit NOT NULL" CanBeNull="true" />
      <Column Name="dtmActualizacion" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="strUsuario" Type="System.String" DbType="VARCHAR(60)" CanBeNull="true" />
      <Column Name="strInfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="IDuspCalculosFinancieros_ConceptosRetencion_Actualizar">
      <Argument Parameter="pintIDConceptoRetencion" Member="intIDConceptoRetencion" />
      <Argument Parameter="pstrCodigo" Member="strCodigo" />
      <Argument Parameter="pstrDescripcion" Member="strDescripcion" />
      <Argument Parameter="pdblPorcentajeRetencion" Member="dblPorcentajeRetencion" />
      <Argument Parameter="plogGravado" Member="logGravado" />
      <Argument Parameter="pstrUsuario" Member="strUsuario" />
      <Argument Parameter="pstrInfoSesion" Member="strInfoSesion" />
      <Argument Parameter="pstrMsgValidacion" Member="strMsgValidacion" />
    </InsertFunction>
    <UpdateFunction FunctionId="IDuspCalculosFinancieros_ConceptosRetencion_Actualizar">
      <Argument Parameter="pintIDConceptoRetencion" Member="intIDConceptoRetencion" />
      <Argument Parameter="pstrCodigo" Member="strCodigo" />
      <Argument Parameter="pstrDescripcion" Member="strDescripcion" />
      <Argument Parameter="pdblPorcentajeRetencion" Member="dblPorcentajeRetencion" />
      <Argument Parameter="plogGravado" Member="logGravado" />
      <Argument Parameter="pstrUsuario" Member="strUsuario" />
      <Argument Parameter="pstrInfoSesion" Member="strInfoSesion" />
      <Argument Parameter="pstrMsgValidacion" Member="strMsgValidacion" />
    </UpdateFunction>
    <DeleteFunction FunctionId="IDuspCalculosFinancieros_ConceptosRetencion_Eliminar">
      <Argument Parameter="pintIDConceptoRetencion" Member="intIDConceptoRetencion" />
      <Argument Parameter="pstrCodigo" Member="strCodigo" />
      <Argument Parameter="pstrUsuario" Member="strUsuario" />
      <Argument Parameter="pstrInfoSesion" Member="strInfoSesion" />
      <Argument Parameter="pstrMsgValidacion" Member="strMsgValidacion" />
    </DeleteFunction>
  </Table>
  <!--***************************************************************************************-->

  
  


  <!--FUNCIONES-->
  <!--***************************************************************************************-->
  <!--Función Titulos-->
  <!--***************************************************************************************-->
  <Function Name="dbo.uspOyDNet_Titulos_Consecutivo" Method="uspOyDNet_Titulos_Consecutivo">
    <Parameter Name="pstrNombreConsecutivo" Type="System.String" DbType="Varchar(15) NULL" />
    <Parameter Name="pintConsecutivo" Type="System.Int32" DbType="Int NULL" Direction="InOut" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="Varchar(MAX) NULL" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_Titulos_ControlUsuarios" Method="uspOyDNet_Titulos_ControlUsuarios">
    <Parameter Name="pstrTipoProceso" Type="System.String" DbType="Varchar(1) NULL" />
    <Parameter Name="pintConsecutivo" Type="System.Int32" DbType="Int NULL"/>
    <Parameter Name="pstrMsgValidacion" Type="System.String" DbType="Varchar(8000) NULL" Direction="InOut" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="Varchar(MAX) NULL" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_Titulos_CompradosSinCargar_Consultar" Method="uspOyDNet_Titulos_CompradosSinCargar_Consultar">
    <Parameter Name="pstrFiltro" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="plogFiltrarTodo" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Parameter Name="pdtmFechaLimite" Type="System.Nullable(of System.DateTime)" DbType="Datetime NOT NULL"  />
    <Parameter Name="plngComitente" Type="System.String" DbType="Varchar(17) NULL" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15) NULL" />
    <Parameter Name="pdtmFechaCorte" Type="System.Nullable(of System.DateTime)" DbType="Datetime NOT NULL"  />
    <Parameter Name="pstrClase" Type="System.String" DbType="Varchar(1) NULL" />
    <Parameter Name="pintConsecutivo" Type="System.Int32" DbType="Int NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID15" />
  </Function>
  <Function Name="dbo.uspOyDNet_Titulos_VendidosSinDescargar_Consultar" Method="uspOyDNet_Titulos_VendidosSinDescargar_Consultar">
    <Parameter Name="pstrFiltro" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="plogFiltrarTodo" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Parameter Name="pdtmFechaLimite" Type="System.Nullable(of System.DateTime)" DbType="Datetime NOT NULL"  />
    <Parameter Name="plngComitente" Type="System.String" DbType="Varchar(17) NULL" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15) NULL" />
    <Parameter Name="pdtmFechaCorte" Type="System.Nullable(of System.DateTime)" DbType="Datetime NOT NULL"  />
    <Parameter Name="pstrClase" Type="System.String" DbType="Varchar(1) NULL" />
    <Parameter Name="pintConsecutivo" Type="System.Int32" DbType="Int NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID16" />
  </Function>
  <Function Name="dbo.uspOyDNet_Titulos_ComprasXCargar_Consultar" Method="uspOyDNet_Titulos_ComprasXCargar_Consultar">
    <Parameter Name="plngComitente" Type="System.String" DbType="Varchar(17) NULL" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15) NULL" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Varchar(1) NULL" />
    <Parameter Name="pintConsecutivo" Type="System.Int32" DbType="Int NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="plogFiltradoDesdePantalla" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_Titulos_CruceTitulosPortafolio_Consultar" Method="uspOyDNet_Titulos_CruceTitulosPortafolio_Consultar">
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15) NULL" />
    <Parameter Name="plngComitente" Type="System.String" DbType="Varchar(17) NULL" />
    <Parameter Name="pdtmFechaEmision" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL"  />
    <Parameter Name="pdtmFechaLimite" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL"  />
    <Parameter Name="pdtmFechaVencimiento" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL"  />
    <Parameter Name="pdblTasa" Type="System.Double" DbType="Float NULL" />
    <Parameter Name="pstrIndicador" Type="System.String" DbType="Varchar(20) NULL" />
    <Parameter Name="pdblPuntos" Type="System.Double" DbType="Float NULL" />
    <Parameter Name="pstrModalidad" Type="System.String" DbType="Varchar(20) NULL" />
    <Parameter Name="pdblCantidad" Type="System.Double" DbType="Float NULL" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Varchar(1) NULL" />
    <Parameter Name="plngCustodia" Type="System.Int32" DbType="Int NULL" />
    <Parameter Name="plngSecuencia" Type="System.Int32" DbType="Int NULL" />
    <Parameter Name="pstrTipoDeOferta" Type="System.String" DbType="Varchar(1) NULL" />
    <Parameter Name="plngIdLiqVenta" Type="System.Double" DbType="Float NULL" />
    <Parameter Name="plngIdParcialVenta" Type="System.Double" DbType="Float NULL" />
    <Parameter Name="pintConsecutivo" Type="System.Int32" DbType="Int NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="plogFiltradoDesdePantalla" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_Titulos_ConsultarCruce" Method="uspOyDNet_Titulos_ConsultarCruce">
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID17" />
  </Function>
  <Function Name="dbo.uspOyDNet_Titulos_PortafolioCliente_Consultar" Method="uspOyDNet_Titulos_PortafolioCliente_Consultar">
    <Parameter Name="pdtmFechaLimite" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL"  />
    <Parameter Name="plngComitente" Type="System.String" DbType="Varchar(17) NULL" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15) NULL" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Varchar(1) NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID18" />
  </Function>
  <Function Id="FunctionId1" Name="PorDefinir1" Method="PorDefinir1">
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId2" Name="PorDefinir2" Method="PorDefinir2">
    <Return Type="System.Int32" />
  </Function>
  <!--***************************************************************************************-->
  <!--Función RespuestaArchivoImportacion-->
  <!--***************************************************************************************-->
  <Function Name="dbo.uspOyDNet_Titulos_MovimientosDeceval_Importar" Method="uspOyDNet_Titulos_MovimientosDeceval_Importar">
    <Parameter Name="pdtmFechaProceso" Type="System.Nullable(of System.Datetime)" DbType="Datetime NOT NULL" />
    <Parameter Name="pstrRutaArchivoAImportar" Type="System.String" DbType="Varchar(500)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(100)" />
    <ElementType IdRef="ID19" />
  </Function>
  <!--***************************************************************************************-->
  <!--Función CruceOperacionesManual-->
  <!--***************************************************************************************-->
  <Function Name="dbo.uspOyDNet_CruceOperacionesManual_VendidosSinDescargar_Consultar" Method="uspOyDNet_CruceOperacionesManual_VendidosSinDescargar_Consultar">
    <Parameter Name="pstrFiltro" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="plogFiltrarTodo" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Parameter Name="pdtmFechaLimite" Type="System.Nullable(of System.DateTime)" DbType="Datetime NOT NULL"  />
    <Parameter Name="plngComitente" Type="System.String" DbType="Varchar(17) NULL" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15) NULL" />
    <Parameter Name="pdtmFechaCorte" Type="System.Nullable(of System.DateTime)" DbType="Datetime NOT NULL"  />
    <Parameter Name="pstrClase" Type="System.String" DbType="Varchar(1) NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID16" />
  </Function>
  <Function Name="dbo.uspOyDNet_CruceOperacionesManual_PortafolioCliente_Consultar" Method="uspOyDNet_CruceOperacionesManual_PortafolioCliente_Consultar">
    <Parameter Name="pstrFiltro" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="plogFiltrarTodo" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Parameter Name="pdtmFechaLimite" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL"  />
    <Parameter Name="plngComitente" Type="System.String" DbType="Varchar(17) NULL" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15) NULL" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Varchar(1) NULL" />
    <Parameter Name="pintIDLiquidaciones" Type="System.Int32" DbType="Int NULL" />
    <Parameter Name="pstrOrigen" Type="System.String" DbType="Varchar(50) NOT NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID18" />
  </Function>
  <Function Name="dbo.uspOyDNet_CruceOperacionesManual_Actualizar" Method="uspOyDNet_CruceOperacionesManual_Actualizar">
    <Parameter Name="pintIDLiquidaciones" Type="System.Int32" DbType="Int NOT NULL" />
    <Parameter Name="pxmlDetalleGrid" Type="System.String" DbType="Text NOT NULL" />
    <Parameter Name="pstrOrigen" Type="System.String" DbType="Varchar(50) NOT NULL" />
    <Parameter Name="pstrMsgValidacion" Type="System.String" DbType="Varchar(8000) NULL" Direction="InOut" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <!--***************************************************************************************-->
  <!--DECEVAL-->
  <!--***************************************************************************************-->
  <Function Name="DECEVAL.uspOyDNet_DecevalArchivos_Solicitar" Method="uspOyDNet_DecevalArchivos_Solicitar">
    <Parameter Name="pstrArchivo" Type="System.String" DbType="varchar (80) NOT NULL"/>
    <Parameter Name="pintTipoArchivo" Type="System.Int32" DbType="INT NOT NULL"/>
    <Parameter Name="pstrUsuario" Type="System.String" DbType="Varchar(60) NULL"/>
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="Varchar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="pstrCodigoISIN" Type="System.String" DbType="Varchar(80) NOT NULL"/>
    <Parameter Name="pintCuentaInversionista" Type="System.Int32" DbType="INT NOT NULL"/>
    <Parameter Name="pstrCodigoDeposito" Type="System.String" DbType="Varchar (20) NOT NULL"/>
    <ElementType IdRef="ID05" />
  </Function>
  <!--***************************************************************************************-->
  <!--ConceptoRetencion-->
  <!--***************************************************************************************-->
  <Function Id="IDuspCalculosFinancieros_ConceptosRetencion_Actualizar" Name="CF.uspCalculosFinancieros_ConceptosRetencion_Actualizar" Method="uspCalculosFinancieros_ConceptosRetencion_Actualizar">
    <Parameter Name="pintIDConceptoRetencion" Type="System.Int32" DbType="Int" />
    <Parameter Name="pstrCodigo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pstrDescripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pdblPorcentajeRetencion" Type="System.Double" DbType="Float" />
    <Parameter Name="plogGravado" Type="System.Nullable(of System.Boolean)" DbType="Bit NOT NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="pstrMsgValidacion" Type="System.String" DbType="VarChar(8000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="IDuspCalculosFinancieros_ConceptosRetencion_Eliminar" Name="CF.uspCalculosFinancieros_ConceptosRetencion_Eliminar" Method="uspCalculosFinancieros_ConceptosRetencion_Eliminar">
    <Parameter Name="pintIDConceptoRetencion" Type="System.Int32" DbType="Int" />
    <Parameter Name="pstrCodigo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="pstrMsgValidacion" Type="System.String" DbType="VarChar(8000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="CF.uspCalculosFinancieros_ConceptosRetencion_Filtrar" Method="uspCalculosFinancieros_ConceptosRetencion_Filtrar">
    <Parameter Name="pstrFiltro" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ConceptoRetencion" />
  </Function>
  <Function Name="CF.uspCalculosFinancieros_ConceptosRetencion_Consultar" Method="uspCalculosFinancieros_ConceptosRetencion_Consultar">
    <Parameter Name="pstrAccion" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="pintIDConceptoRetencion" Type="System.Int32" DbType="Int" />
    <Parameter Name="pstrCodigo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pstrDescripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="plogGravado" Type="System.Nullable(of System.Boolean)" DbType="Bit NOT NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ConceptoRetencion" />
  </Function>
  <!--***************************************************************************************-->
  </Database>