<?xml version="1.0" encoding="utf-8"?>
<Database Name="dbOYDPlus" EntityNamespace="OyDPLUSOrdenes" Class="OyDPLUSOrdenesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="ModulosUsuario">
    <Type Name="ModulosUsuario" Id="ID1">
      <Column Name="intID" Member="ID" Type="System.Int32" DbType="Int" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strModulo" Member="Modulo" Type="System.String" DbType="Varchar(60)" CanBeNull="false" />
      <Column Name="intPrioridad" Member="Prioridad" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="strAccionPermitida" Member="AccionPermitida" Type="System.String" DbType="Varchar(60)" CanBeNull="false" />
      <Column Name="strDescripcionAccion" Member="DescripcionAccion" Type="System.String" DbType="Varchar(60)" CanBeNull="false" />
      <Column Name="strTituloModulo" Member="TituloModulo" Type="System.String" DbType="Varchar(60)" CanBeNull="false" />
      <Column Name="strTituloVistaModulo" Member="TituloVistaModulo" Type="System.String" DbType="Varchar(100)" CanBeNull="false" />
    </Type>
  </Table>

  <Function Name="OYDPLUS.uspOyDNet_CargarModulosUsuario" Method="uspOyDNet_CargarModulosUsuario">
    <Parameter Name="pstrAplicacion" Type="System.String" DbType="VARCHAR(60)" />
    <Parameter Name="pstrVersion" Type="System.String" DbType="VARCHAR(20)" />
    <Parameter Name="pstrUsuarioUtilidades" Type="System.String" DbType="VARCHAR(60)" />
    <Parameter Name="pstrClave" Type="System.String" DbType="VARCHAR(60)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VARCHAR(60)" />
    <Parameter Name="pstrMaquina" Type="System.String" DbType="VARCHAR(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VARCHAR(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TINYINT" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>