'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblCRCC_CTRADES
    Public Property intID As Integer
    Public Property strTradeReference As String
    Public Property dtmSessionDate As Date
    Public Property intTradeID As Long
    Public Property strSide As String
    Public Property strUserID As String
    Public Property strAccount As String
    Public Property strContractCode As String
    Public Property numPrice As Decimal
    Public Property numQuantity As Decimal
    Public Property dtmSettleDate As Date
    Public Property strRegDate As String
    Public Property strInitialTradeExecID As String
    Public Property dtmActualizacion As Date
    Public Property bitSel As Boolean
    Public Property bitCazada As Boolean
    Public Property strTradeType As String

End Class
