'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblCRCC_CTRADES_TimeSpread
    Public Property IDLiq As Integer
    Public Property Tipo_Operacion As String
    Public Property Cantidad As Decimal
    Public Property Precio As Decimal
    Public Property Producto As String
    Public Property Fecha_Vencimiento As Date
    Public Property IntNroFolio As Integer
    Public Property bitSel As Boolean

End Class
