'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCRCC_CTRADES
    Public Property intID As Integer
    Public Property dtmSessionDate As Date
    Public Property strClearingHouseCode As String
    Public Property intTradeID As Integer
    Public Property strSide As String
    Public Property strMember As String
    Public Property strUserID As String
    Public Property strAccount As String
    Public Property strContractCode As String
    Public Property strTradeType As String
    Public Property numPrice As Nullable(Of Decimal)
    Public Property numQuantity As Nullable(Of Decimal)
    Public Property strTradeReference As String
    Public Property strOpenCloseIndicator As String
    Public Property numTradingFee As Nullable(Of Decimal)
    Public Property numClearingFee As Nullable(Of Decimal)
    Public Property strCurrency As String
    Public Property dtmSettleDate As Nullable(Of Date)
    Public Property strRegDate As String
    Public Property strRegTime As String
    Public Property intPreviousTradeID As Nullable(Of Integer)
    Public Property intInitialTradeID As Nullable(Of Integer)
    Public Property strInitialTradeMarketCode As String
    Public Property strInitialTradeExecID As String
    Public Property dtmInitialTradeTradingDate As Nullable(Of Date)
    Public Property strInitialTradeType As String
    Public Property strExecutionDate As String
    Public Property strExecutionTime As String
    Public Property strOrderNumber As String
    Public Property numGrossTradeAmt As Nullable(Of Decimal)
    Public Property strUsuario As String
    Public Property dtmActualizacion As Date
    Public Property bitCazada As Boolean
    Public Property strReferencia As String
    Public Property OrigTradeReference1 As String
    Public Property OrigTradeReference2 As String
    Public Property UTI As String
    Public Property NotTransferredQty As String
    Public Property NextTradeID As String
    Public Property Yield As String

End Class
