'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServicioDocumentador
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dcDocumentadorDataContext.IngresoDocumentoResult", [Namespace]:="http://schemas.datacontract.org/2004/07/AAS.Objetos.Documentador"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dcDocumentadorDataContextIngresoDocumentoResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValorRetornoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ValorRetorno() As String
            Get
                Return Me.ValorRetornoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValorRetornoField, value) <> true) Then
                    Me.ValorRetornoField = value
                    Me.RaisePropertyChanged("ValorRetorno")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResultadoIngreso", [Namespace]:="http://schemas.datacontract.org/2004/07/AAS.Objetos.Documentador"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResultadoIngreso
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IntNroErrorField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IntidField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private intResultadoField As System.Nullable(Of Integer)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IntNroError() As System.Nullable(Of Integer)
            Get
                Return Me.IntNroErrorField
            End Get
            Set
                If (Me.IntNroErrorField.Equals(value) <> true) Then
                    Me.IntNroErrorField = value
                    Me.RaisePropertyChanged("IntNroError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Intid() As System.Nullable(Of Integer)
            Get
                Return Me.IntidField
            End Get
            Set
                If (Me.IntidField.Equals(value) <> true) Then
                    Me.IntidField = value
                    Me.RaisePropertyChanged("Intid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mensaje() As String
            Get
                Return Me.MensajeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeField, value) <> true) Then
                    Me.MensajeField = value
                    Me.RaisePropertyChanged("Mensaje")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property intResultado() As System.Nullable(Of Integer)
            Get
                Return Me.intResultadoField
            End Get
            Set
                If (Me.intResultadoField.Equals(value) <> true) Then
                    Me.intResultadoField = value
                    Me.RaisePropertyChanged("intResultado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DatoEjecucion", [Namespace]:="http://schemas.datacontract.org/2004/07/AAS.Objetos.Documentador"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DatoEjecucion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoAplicacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoCategoriaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoExternoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdControlIngresoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NroDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PermisoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoIDClienteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoAplicacion() As String
            Get
                Return Me.CodigoAplicacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoAplicacionField, value) <> true) Then
                    Me.CodigoAplicacionField = value
                    Me.RaisePropertyChanged("CodigoAplicacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoCategoria() As String
            Get
                Return Me.CodigoCategoriaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoCategoriaField, value) <> true) Then
                    Me.CodigoCategoriaField = value
                    Me.RaisePropertyChanged("CodigoCategoria")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoExterno() As String
            Get
                Return Me.CodigoExternoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoExternoField, value) <> true) Then
                    Me.CodigoExternoField = value
                    Me.RaisePropertyChanged("CodigoExterno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdControlIngreso() As Integer
            Get
                Return Me.IdControlIngresoField
            End Get
            Set
                If (Me.IdControlIngresoField.Equals(value) <> true) Then
                    Me.IdControlIngresoField = value
                    Me.RaisePropertyChanged("IdControlIngreso")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NroDocumento() As String
            Get
                Return Me.NroDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NroDocumentoField, value) <> true) Then
                    Me.NroDocumentoField = value
                    Me.RaisePropertyChanged("NroDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Permiso() As String
            Get
                Return Me.PermisoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PermisoField, value) <> true) Then
                    Me.PermisoField = value
                    Me.RaisePropertyChanged("Permiso")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoDocumento() As String
            Get
                Return Me.TipoDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoDocumentoField, value) <> true) Then
                    Me.TipoDocumentoField = value
                    Me.RaisePropertyChanged("TipoDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoIDCliente() As String
            Get
                Return Me.TipoIDClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoIDClienteField, value) <> true) Then
                    Me.TipoIDClienteField = value
                    Me.RaisePropertyChanged("TipoIDCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Usuario() As String
            Get
                Return Me.UsuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioField, value) <> true) Then
                    Me.UsuarioField = value
                    Me.RaisePropertyChanged("Usuario")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Documentos", [Namespace]:="http://schemas.datacontract.org/2004/07/AAS.Objetos.Documentador"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Documentos
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoAplicacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoExternoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EliminarField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EntregadoField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreArchivoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreGuardadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NroDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObservacionesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RutaArchivoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SizeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private dtmFechaEntregaField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private dtmFinalVigenciaField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private dtmInicioVigenciaField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private intIdDocumentoField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private strTipoDocumentoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As System.Nullable(Of Boolean)
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoAplicacion() As String
            Get
                Return Me.CodigoAplicacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoAplicacionField, value) <> true) Then
                    Me.CodigoAplicacionField = value
                    Me.RaisePropertyChanged("CodigoAplicacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoExterno() As String
            Get
                Return Me.CodigoExternoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoExternoField, value) <> true) Then
                    Me.CodigoExternoField = value
                    Me.RaisePropertyChanged("CodigoExterno")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Eliminar() As System.Nullable(Of Boolean)
            Get
                Return Me.EliminarField
            End Get
            Set
                If (Me.EliminarField.Equals(value) <> true) Then
                    Me.EliminarField = value
                    Me.RaisePropertyChanged("Eliminar")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Entregado() As System.Nullable(Of Boolean)
            Get
                Return Me.EntregadoField
            End Get
            Set
                If (Me.EntregadoField.Equals(value) <> true) Then
                    Me.EntregadoField = value
                    Me.RaisePropertyChanged("Entregado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreArchivo() As String
            Get
                Return Me.NombreArchivoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreArchivoField, value) <> true) Then
                    Me.NombreArchivoField = value
                    Me.RaisePropertyChanged("NombreArchivo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreGuardado() As String
            Get
                Return Me.NombreGuardadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreGuardadoField, value) <> true) Then
                    Me.NombreGuardadoField = value
                    Me.RaisePropertyChanged("NombreGuardado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NroDocumento() As String
            Get
                Return Me.NroDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NroDocumentoField, value) <> true) Then
                    Me.NroDocumentoField = value
                    Me.RaisePropertyChanged("NroDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observaciones() As String
            Get
                Return Me.ObservacionesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacionesField, value) <> true) Then
                    Me.ObservacionesField = value
                    Me.RaisePropertyChanged("Observaciones")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RutaArchivo() As String
            Get
                Return Me.RutaArchivoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RutaArchivoField, value) <> true) Then
                    Me.RutaArchivoField = value
                    Me.RaisePropertyChanged("RutaArchivo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Size() As String
            Get
                Return Me.SizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SizeField, value) <> true) Then
                    Me.SizeField = value
                    Me.RaisePropertyChanged("Size")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property dtmFechaEntrega() As System.Nullable(Of Date)
            Get
                Return Me.dtmFechaEntregaField
            End Get
            Set
                If (Me.dtmFechaEntregaField.Equals(value) <> true) Then
                    Me.dtmFechaEntregaField = value
                    Me.RaisePropertyChanged("dtmFechaEntrega")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property dtmFinalVigencia() As System.Nullable(Of Date)
            Get
                Return Me.dtmFinalVigenciaField
            End Get
            Set
                If (Me.dtmFinalVigenciaField.Equals(value) <> true) Then
                    Me.dtmFinalVigenciaField = value
                    Me.RaisePropertyChanged("dtmFinalVigencia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property dtmInicioVigencia() As System.Nullable(Of Date)
            Get
                Return Me.dtmInicioVigenciaField
            End Get
            Set
                If (Me.dtmInicioVigenciaField.Equals(value) <> true) Then
                    Me.dtmInicioVigenciaField = value
                    Me.RaisePropertyChanged("dtmInicioVigencia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property intIdDocumento() As System.Nullable(Of Integer)
            Get
                Return Me.intIdDocumentoField
            End Get
            Set
                If (Me.intIdDocumentoField.Equals(value) <> true) Then
                    Me.intIdDocumentoField = value
                    Me.RaisePropertyChanged("intIdDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property strTipoDocumento() As String
            Get
                Return Me.strTipoDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.strTipoDocumentoField, value) <> true) Then
                    Me.strTipoDocumentoField = value
                    Me.RaisePropertyChanged("strTipoDocumento")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioDocumentador.IServicioDocumentador")>  _
    Public Interface IServicioDocumentador
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/NroDigitosDocumentador", ReplyAction:="http://tempuri.org/IServicioDocumentador/NroDigitosDocumentadorResponse")>  _
        Function NroDigitosDocumentador() As System.Nullable(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/NroDigitosDocumentador", ReplyAction:="http://tempuri.org/IServicioDocumentador/NroDigitosDocumentadorResponse")>  _
        Function NroDigitosDocumentadorAsync() As System.Threading.Tasks.Task(Of System.Nullable(Of Integer))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/ValidarIngresoDocumentador", ReplyAction:="http://tempuri.org/IServicioDocumentador/ValidarIngresoDocumentadorResponse")>  _
        Function ValidarIngresoDocumentador(ByVal pstrIdRegistro As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/ValidarIngresoDocumentador", ReplyAction:="http://tempuri.org/IServicioDocumentador/ValidarIngresoDocumentadorResponse")>  _
        Function ValidarIngresoDocumentadorAsync(ByVal pstrIdRegistro As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/RegistrarIngresoDocumentador", ReplyAction:="http://tempuri.org/IServicioDocumentador/RegistrarIngresoDocumentadorResponse")>  _
        Function RegistrarIngresoDocumentador(ByVal request As ServicioDocumentador.RegistrarIngresoDocumentadorRequest) As ServicioDocumentador.RegistrarIngresoDocumentadorResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/RegistrarIngresoDocumentador", ReplyAction:="http://tempuri.org/IServicioDocumentador/RegistrarIngresoDocumentadorResponse")>  _
        Function RegistrarIngresoDocumentadorAsync(ByVal request As ServicioDocumentador.RegistrarIngresoDocumentadorRequest) As System.Threading.Tasks.Task(Of ServicioDocumentador.RegistrarIngresoDocumentadorResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/Ingresar_Documento", ReplyAction:="http://tempuri.org/IServicioDocumentador/Ingresar_DocumentoResponse")>  _
        Function Ingresar_Documento( _
                    ByVal pstrUsuario As String,  _
                    ByVal pintidControlIngreso As Integer,  _
                    ByVal pstrCodigoAplicacion As String,  _
                    ByVal pstrCodigoCategoria As String,  _
                    ByVal pstrTipoDocumento As String,  _
                    ByVal pstrCodigoExterno As String,  _
                    ByVal pstrTipoIdCliente As String,  _
                    ByVal pstrNroDocumentoCliente As String,  _
                    ByVal pstrRutaArchivo As String,  _
                    ByVal pstrSize As String,  _
                    ByVal pstrNombreOriginal As String,  _
                    ByVal pstrNombreGuardado As String,  _
                    ByVal pbitEntregado As System.Nullable(Of Boolean),  _
                    ByVal pbitActivo As System.Nullable(Of Boolean),  _
                    ByVal pdtmFechaEntrega As System.Nullable(Of Date),  _
                    ByVal pdtmInicioVigencia As System.Nullable(Of Date),  _
                    ByVal pdtmFinalVigencia As System.Nullable(Of Date),  _
                    ByVal pstrObservaciones As String) As ServicioDocumentador.ResultadoIngreso()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/Ingresar_Documento", ReplyAction:="http://tempuri.org/IServicioDocumentador/Ingresar_DocumentoResponse")>  _
        Function Ingresar_DocumentoAsync( _
                    ByVal pstrUsuario As String,  _
                    ByVal pintidControlIngreso As Integer,  _
                    ByVal pstrCodigoAplicacion As String,  _
                    ByVal pstrCodigoCategoria As String,  _
                    ByVal pstrTipoDocumento As String,  _
                    ByVal pstrCodigoExterno As String,  _
                    ByVal pstrTipoIdCliente As String,  _
                    ByVal pstrNroDocumentoCliente As String,  _
                    ByVal pstrRutaArchivo As String,  _
                    ByVal pstrSize As String,  _
                    ByVal pstrNombreOriginal As String,  _
                    ByVal pstrNombreGuardado As String,  _
                    ByVal pbitEntregado As System.Nullable(Of Boolean),  _
                    ByVal pbitActivo As System.Nullable(Of Boolean),  _
                    ByVal pdtmFechaEntrega As System.Nullable(Of Date),  _
                    ByVal pdtmInicioVigencia As System.Nullable(Of Date),  _
                    ByVal pdtmFinalVigencia As System.Nullable(Of Date),  _
                    ByVal pstrObservaciones As String) As System.Threading.Tasks.Task(Of ServicioDocumentador.ResultadoIngreso())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/ConsultarConfiguracion", ReplyAction:="http://tempuri.org/IServicioDocumentador/ConsultarConfiguracionResponse")>  _
        Function ConsultarConfiguracion(ByVal pstrUsuario As String, ByVal pIdValidacion As String) As ServicioDocumentador.DatoEjecucion()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/ConsultarConfiguracion", ReplyAction:="http://tempuri.org/IServicioDocumentador/ConsultarConfiguracionResponse")>  _
        Function ConsultarConfiguracionAsync(ByVal pstrUsuario As String, ByVal pIdValidacion As String) As System.Threading.Tasks.Task(Of ServicioDocumentador.DatoEjecucion())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/ConsultarDocumentos", ReplyAction:="http://tempuri.org/IServicioDocumentador/ConsultarDocumentosResponse")>  _
        Function ConsultarDocumentos(ByVal pstrCodigoAplicacion As String, ByVal pstrCodigoExterno As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrCodigoCategoria As String) As ServicioDocumentador.Documentos()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/ConsultarDocumentos", ReplyAction:="http://tempuri.org/IServicioDocumentador/ConsultarDocumentosResponse")>  _
        Function ConsultarDocumentosAsync(ByVal pstrCodigoAplicacion As String, ByVal pstrCodigoExterno As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrCodigoCategoria As String) As System.Threading.Tasks.Task(Of ServicioDocumentador.Documentos())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/EliminarDocumento", ReplyAction:="http://tempuri.org/IServicioDocumentador/EliminarDocumentoResponse")>  _
        Function EliminarDocumento(ByVal pintIdDocumento As Integer) As ServicioDocumentador.ResultadoIngreso()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/EliminarDocumento", ReplyAction:="http://tempuri.org/IServicioDocumentador/EliminarDocumentoResponse")>  _
        Function EliminarDocumentoAsync(ByVal pintIdDocumento As Integer) As System.Threading.Tasks.Task(Of ServicioDocumentador.ResultadoIngreso())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirVisualizar", ReplyAction:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirVisualizarResponse")>  _
        Function Codigo_PermitirVisualizar() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirVisualizar", ReplyAction:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirVisualizarResponse")>  _
        Function Codigo_PermitirVisualizarAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirEliminar", ReplyAction:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirEliminarResponse")>  _
        Function Codigo_PermitirEliminar() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirEliminar", ReplyAction:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirEliminarResponse")>  _
        Function Codigo_PermitirEliminarAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirCargar", ReplyAction:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirCargarResponse")>  _
        Function Codigo_PermitirCargar() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirCargar", ReplyAction:="http://tempuri.org/IServicioDocumentador/Codigo_PermitirCargarResponse")>  _
        Function Codigo_PermitirCargarAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/ValidarDocumentoExiste", ReplyAction:="http://tempuri.org/IServicioDocumentador/ValidarDocumentoExisteResponse")>  _
        Function ValidarDocumentoExiste(ByVal pstrUsuario As String, ByVal pstrCategoria As String, ByVal pstrCodigoAplicacion As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrTipoDocumento As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioDocumentador/ValidarDocumentoExiste", ReplyAction:="http://tempuri.org/IServicioDocumentador/ValidarDocumentoExisteResponse")>  _
        Function ValidarDocumentoExisteAsync(ByVal pstrUsuario As String, ByVal pstrCategoria As String, ByVal pstrCodigoAplicacion As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrTipoDocumento As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RegistrarIngresoDocumentador", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class RegistrarIngresoDocumentadorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public pstrUsuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public pstrCodigoAplicacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public pstrCodigoCategoria As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public pstrTipoDocumento As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public pstrTipoIdCliente As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public pstrNroDocumentoCliente As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=6)>  _
        Public pstrCodigoExterno As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=7)>  _
        Public pstrPermiso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=8)>  _
        Public pstrCodigoIngreso As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pstrUsuario As String, ByVal pstrCodigoAplicacion As String, ByVal pstrCodigoCategoria As String, ByVal pstrTipoDocumento As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrCodigoExterno As String, ByVal pstrPermiso As String, ByVal pstrCodigoIngreso As String)
            MyBase.New
            Me.pstrUsuario = pstrUsuario
            Me.pstrCodigoAplicacion = pstrCodigoAplicacion
            Me.pstrCodigoCategoria = pstrCodigoCategoria
            Me.pstrTipoDocumento = pstrTipoDocumento
            Me.pstrTipoIdCliente = pstrTipoIdCliente
            Me.pstrNroDocumentoCliente = pstrNroDocumentoCliente
            Me.pstrCodigoExterno = pstrCodigoExterno
            Me.pstrPermiso = pstrPermiso
            Me.pstrCodigoIngreso = pstrCodigoIngreso
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RegistrarIngresoDocumentadorResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class RegistrarIngresoDocumentadorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public RegistrarIngresoDocumentadorResult() As ServicioDocumentador.dcDocumentadorDataContextIngresoDocumentoResult
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public pstrCodigoIngreso As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RegistrarIngresoDocumentadorResult() As ServicioDocumentador.dcDocumentadorDataContextIngresoDocumentoResult, ByVal pstrCodigoIngreso As String)
            MyBase.New
            Me.RegistrarIngresoDocumentadorResult = RegistrarIngresoDocumentadorResult
            Me.pstrCodigoIngreso = pstrCodigoIngreso
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServicioDocumentadorChannel
        Inherits ServicioDocumentador.IServicioDocumentador, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioDocumentadorClient
        Inherits System.ServiceModel.ClientBase(Of ServicioDocumentador.IServicioDocumentador)
        Implements ServicioDocumentador.IServicioDocumentador
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function NroDigitosDocumentador() As System.Nullable(Of Integer) Implements ServicioDocumentador.IServicioDocumentador.NroDigitosDocumentador
            Return MyBase.Channel.NroDigitosDocumentador
        End Function
        
        Public Function NroDigitosDocumentadorAsync() As System.Threading.Tasks.Task(Of System.Nullable(Of Integer)) Implements ServicioDocumentador.IServicioDocumentador.NroDigitosDocumentadorAsync
            Return MyBase.Channel.NroDigitosDocumentadorAsync
        End Function
        
        Public Function ValidarIngresoDocumentador(ByVal pstrIdRegistro As String) As Boolean Implements ServicioDocumentador.IServicioDocumentador.ValidarIngresoDocumentador
            Return MyBase.Channel.ValidarIngresoDocumentador(pstrIdRegistro)
        End Function
        
        Public Function ValidarIngresoDocumentadorAsync(ByVal pstrIdRegistro As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServicioDocumentador.IServicioDocumentador.ValidarIngresoDocumentadorAsync
            Return MyBase.Channel.ValidarIngresoDocumentadorAsync(pstrIdRegistro)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioDocumentador_IServicioDocumentador_RegistrarIngresoDocumentador(ByVal request As ServicioDocumentador.RegistrarIngresoDocumentadorRequest) As ServicioDocumentador.RegistrarIngresoDocumentadorResponse Implements ServicioDocumentador.IServicioDocumentador.RegistrarIngresoDocumentador
            Return MyBase.Channel.RegistrarIngresoDocumentador(request)
        End Function
        
        Public Function RegistrarIngresoDocumentador(ByVal pstrUsuario As String, ByVal pstrCodigoAplicacion As String, ByVal pstrCodigoCategoria As String, ByVal pstrTipoDocumento As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrCodigoExterno As String, ByVal pstrPermiso As String, ByRef pstrCodigoIngreso As String) As ServicioDocumentador.dcDocumentadorDataContextIngresoDocumentoResult()
            Dim inValue As ServicioDocumentador.RegistrarIngresoDocumentadorRequest = New ServicioDocumentador.RegistrarIngresoDocumentadorRequest()
            inValue.pstrUsuario = pstrUsuario
            inValue.pstrCodigoAplicacion = pstrCodigoAplicacion
            inValue.pstrCodigoCategoria = pstrCodigoCategoria
            inValue.pstrTipoDocumento = pstrTipoDocumento
            inValue.pstrTipoIdCliente = pstrTipoIdCliente
            inValue.pstrNroDocumentoCliente = pstrNroDocumentoCliente
            inValue.pstrCodigoExterno = pstrCodigoExterno
            inValue.pstrPermiso = pstrPermiso
            inValue.pstrCodigoIngreso = pstrCodigoIngreso
            Dim retVal As ServicioDocumentador.RegistrarIngresoDocumentadorResponse = CType(Me,ServicioDocumentador.IServicioDocumentador).RegistrarIngresoDocumentador(inValue)
            pstrCodigoIngreso = retVal.pstrCodigoIngreso
            Return retVal.RegistrarIngresoDocumentadorResult
        End Function
        
        Public Function RegistrarIngresoDocumentadorAsync(ByVal request As ServicioDocumentador.RegistrarIngresoDocumentadorRequest) As System.Threading.Tasks.Task(Of ServicioDocumentador.RegistrarIngresoDocumentadorResponse) Implements ServicioDocumentador.IServicioDocumentador.RegistrarIngresoDocumentadorAsync
            Return MyBase.Channel.RegistrarIngresoDocumentadorAsync(request)
        End Function
        
        Public Function Ingresar_Documento( _
                    ByVal pstrUsuario As String,  _
                    ByVal pintidControlIngreso As Integer,  _
                    ByVal pstrCodigoAplicacion As String,  _
                    ByVal pstrCodigoCategoria As String,  _
                    ByVal pstrTipoDocumento As String,  _
                    ByVal pstrCodigoExterno As String,  _
                    ByVal pstrTipoIdCliente As String,  _
                    ByVal pstrNroDocumentoCliente As String,  _
                    ByVal pstrRutaArchivo As String,  _
                    ByVal pstrSize As String,  _
                    ByVal pstrNombreOriginal As String,  _
                    ByVal pstrNombreGuardado As String,  _
                    ByVal pbitEntregado As System.Nullable(Of Boolean),  _
                    ByVal pbitActivo As System.Nullable(Of Boolean),  _
                    ByVal pdtmFechaEntrega As System.Nullable(Of Date),  _
                    ByVal pdtmInicioVigencia As System.Nullable(Of Date),  _
                    ByVal pdtmFinalVigencia As System.Nullable(Of Date),  _
                    ByVal pstrObservaciones As String) As ServicioDocumentador.ResultadoIngreso() Implements ServicioDocumentador.IServicioDocumentador.Ingresar_Documento
            Return MyBase.Channel.Ingresar_Documento(pstrUsuario, pintidControlIngreso, pstrCodigoAplicacion, pstrCodigoCategoria, pstrTipoDocumento, pstrCodigoExterno, pstrTipoIdCliente, pstrNroDocumentoCliente, pstrRutaArchivo, pstrSize, pstrNombreOriginal, pstrNombreGuardado, pbitEntregado, pbitActivo, pdtmFechaEntrega, pdtmInicioVigencia, pdtmFinalVigencia, pstrObservaciones)
        End Function
        
        Public Function Ingresar_DocumentoAsync( _
                    ByVal pstrUsuario As String,  _
                    ByVal pintidControlIngreso As Integer,  _
                    ByVal pstrCodigoAplicacion As String,  _
                    ByVal pstrCodigoCategoria As String,  _
                    ByVal pstrTipoDocumento As String,  _
                    ByVal pstrCodigoExterno As String,  _
                    ByVal pstrTipoIdCliente As String,  _
                    ByVal pstrNroDocumentoCliente As String,  _
                    ByVal pstrRutaArchivo As String,  _
                    ByVal pstrSize As String,  _
                    ByVal pstrNombreOriginal As String,  _
                    ByVal pstrNombreGuardado As String,  _
                    ByVal pbitEntregado As System.Nullable(Of Boolean),  _
                    ByVal pbitActivo As System.Nullable(Of Boolean),  _
                    ByVal pdtmFechaEntrega As System.Nullable(Of Date),  _
                    ByVal pdtmInicioVigencia As System.Nullable(Of Date),  _
                    ByVal pdtmFinalVigencia As System.Nullable(Of Date),  _
                    ByVal pstrObservaciones As String) As System.Threading.Tasks.Task(Of ServicioDocumentador.ResultadoIngreso()) Implements ServicioDocumentador.IServicioDocumentador.Ingresar_DocumentoAsync
            Return MyBase.Channel.Ingresar_DocumentoAsync(pstrUsuario, pintidControlIngreso, pstrCodigoAplicacion, pstrCodigoCategoria, pstrTipoDocumento, pstrCodigoExterno, pstrTipoIdCliente, pstrNroDocumentoCliente, pstrRutaArchivo, pstrSize, pstrNombreOriginal, pstrNombreGuardado, pbitEntregado, pbitActivo, pdtmFechaEntrega, pdtmInicioVigencia, pdtmFinalVigencia, pstrObservaciones)
        End Function
        
        Public Function ConsultarConfiguracion(ByVal pstrUsuario As String, ByVal pIdValidacion As String) As ServicioDocumentador.DatoEjecucion() Implements ServicioDocumentador.IServicioDocumentador.ConsultarConfiguracion
            Return MyBase.Channel.ConsultarConfiguracion(pstrUsuario, pIdValidacion)
        End Function
        
        Public Function ConsultarConfiguracionAsync(ByVal pstrUsuario As String, ByVal pIdValidacion As String) As System.Threading.Tasks.Task(Of ServicioDocumentador.DatoEjecucion()) Implements ServicioDocumentador.IServicioDocumentador.ConsultarConfiguracionAsync
            Return MyBase.Channel.ConsultarConfiguracionAsync(pstrUsuario, pIdValidacion)
        End Function
        
        Public Function ConsultarDocumentos(ByVal pstrCodigoAplicacion As String, ByVal pstrCodigoExterno As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrCodigoCategoria As String) As ServicioDocumentador.Documentos() Implements ServicioDocumentador.IServicioDocumentador.ConsultarDocumentos
            Return MyBase.Channel.ConsultarDocumentos(pstrCodigoAplicacion, pstrCodigoExterno, pstrTipoIdCliente, pstrNroDocumentoCliente, pstrCodigoCategoria)
        End Function
        
        Public Function ConsultarDocumentosAsync(ByVal pstrCodigoAplicacion As String, ByVal pstrCodigoExterno As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrCodigoCategoria As String) As System.Threading.Tasks.Task(Of ServicioDocumentador.Documentos()) Implements ServicioDocumentador.IServicioDocumentador.ConsultarDocumentosAsync
            Return MyBase.Channel.ConsultarDocumentosAsync(pstrCodigoAplicacion, pstrCodigoExterno, pstrTipoIdCliente, pstrNroDocumentoCliente, pstrCodigoCategoria)
        End Function
        
        Public Function EliminarDocumento(ByVal pintIdDocumento As Integer) As ServicioDocumentador.ResultadoIngreso() Implements ServicioDocumentador.IServicioDocumentador.EliminarDocumento
            Return MyBase.Channel.EliminarDocumento(pintIdDocumento)
        End Function
        
        Public Function EliminarDocumentoAsync(ByVal pintIdDocumento As Integer) As System.Threading.Tasks.Task(Of ServicioDocumentador.ResultadoIngreso()) Implements ServicioDocumentador.IServicioDocumentador.EliminarDocumentoAsync
            Return MyBase.Channel.EliminarDocumentoAsync(pintIdDocumento)
        End Function
        
        Public Function Codigo_PermitirVisualizar() As String Implements ServicioDocumentador.IServicioDocumentador.Codigo_PermitirVisualizar
            Return MyBase.Channel.Codigo_PermitirVisualizar
        End Function
        
        Public Function Codigo_PermitirVisualizarAsync() As System.Threading.Tasks.Task(Of String) Implements ServicioDocumentador.IServicioDocumentador.Codigo_PermitirVisualizarAsync
            Return MyBase.Channel.Codigo_PermitirVisualizarAsync
        End Function
        
        Public Function Codigo_PermitirEliminar() As String Implements ServicioDocumentador.IServicioDocumentador.Codigo_PermitirEliminar
            Return MyBase.Channel.Codigo_PermitirEliminar
        End Function
        
        Public Function Codigo_PermitirEliminarAsync() As System.Threading.Tasks.Task(Of String) Implements ServicioDocumentador.IServicioDocumentador.Codigo_PermitirEliminarAsync
            Return MyBase.Channel.Codigo_PermitirEliminarAsync
        End Function
        
        Public Function Codigo_PermitirCargar() As String Implements ServicioDocumentador.IServicioDocumentador.Codigo_PermitirCargar
            Return MyBase.Channel.Codigo_PermitirCargar
        End Function
        
        Public Function Codigo_PermitirCargarAsync() As System.Threading.Tasks.Task(Of String) Implements ServicioDocumentador.IServicioDocumentador.Codigo_PermitirCargarAsync
            Return MyBase.Channel.Codigo_PermitirCargarAsync
        End Function
        
        Public Function ValidarDocumentoExiste(ByVal pstrUsuario As String, ByVal pstrCategoria As String, ByVal pstrCodigoAplicacion As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrTipoDocumento As String) As Boolean Implements ServicioDocumentador.IServicioDocumentador.ValidarDocumentoExiste
            Return MyBase.Channel.ValidarDocumentoExiste(pstrUsuario, pstrCategoria, pstrCodigoAplicacion, pstrTipoIdCliente, pstrNroDocumentoCliente, pstrTipoDocumento)
        End Function
        
        Public Function ValidarDocumentoExisteAsync(ByVal pstrUsuario As String, ByVal pstrCategoria As String, ByVal pstrCodigoAplicacion As String, ByVal pstrTipoIdCliente As String, ByVal pstrNroDocumentoCliente As String, ByVal pstrTipoDocumento As String) As System.Threading.Tasks.Task(Of Boolean) Implements ServicioDocumentador.IServicioDocumentador.ValidarDocumentoExisteAsync
            Return MyBase.Channel.ValidarDocumentoExisteAsync(pstrUsuario, pstrCategoria, pstrCodigoAplicacion, pstrTipoIdCliente, pstrNroDocumentoCliente, pstrTipoDocumento)
        End Function
    End Class
End Namespace
