'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblTipoDocAutorizacion
    Public Property intID As Integer
    Public Property strTipoProducto As String
    Public Property strCodigoTipoDocumento As String

End Class
