'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblCombos
    Public Property intID As Integer
    Public Property intIDDependencia1 As Nullable(Of Integer)
    Public Property intIDDependencia2 As Nullable(Of Integer)
    Public Property strDependencia1 As String
    Public Property strDependencia2 As String
    Public Property strDescripcion As String
    Public Property strRetorno As String
    Public Property strTopico As String

End Class
