'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblFirmasGiveUp
    Public Property intID As Integer
    Public Property strContraParte As String
    Public Property strReferenciaGiveOut As String
    Public Property bitAceptaGiveOut As Nullable(Of Boolean)
    Public Property bitAceptaGiveIn As Nullable(Of Boolean)
    Public Property logActiva As Nullable(Of Boolean)

End Class
