'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCuentasInstrumentos
    Public Property intIdCuentasInstrumentos As Integer
    Public Property intIdCuentaCRCC As Integer
    Public Property intIdSubcuentaCRCC As Nullable(Of Integer)
    Public Property intIdProducto As Integer
    Public Property intIdCuentaCRCCReem As Integer
    Public Property intIdSubcuentaCRCCReem As Nullable(Of Integer)
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
