'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblClientesSubcuentasCRCC
    Public Property intIdClienteSubcuentaCRCC As Integer
    Public Property intIdClienteCuentaCRCC As Integer
    Public Property strNroSubcuenta As String
    Public Property strDescripcion As String
    Public Property bitActiva As Boolean
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
