'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblConceptosContables
    Public Property intIdConceptoContable As Integer
    Public Property strConceptoContable As String
    Public Property strDescripcionConceptoContable As String
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
