'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblClientesCuentasCRCC
    Public Property intIdClienteCuentaCRCC As Integer
    Public Property intIdCuentaMultiproducto As String
    Public Property strNroCuenta As String
    Public Property strDescripcion As String
    Public Property bitPorDefectoTerceros As Boolean
    Public Property bitPosicionPropia As Boolean
    Public Property bitActiva As Boolean
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String
    Public Property numMarginCall As Nullable(Of Decimal)
    Public Property bitPermiteGiveIn As Nullable(Of Boolean)
    Public Property bitPermiteGiveOut As Nullable(Of Boolean)
    Public Property intIdTipoCuenta As Nullable(Of Integer)

End Class
