'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblDetalleDatosTributarios
    Public Property intIdDetalleDatosTributarios As Integer
    Public Property intIdDatosTributarios As Integer
    Public Property dtmFechaInicial As Date
    Public Property dtmFechaFinal As Nullable(Of Date)
    Public Property numValor As Decimal
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
