'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblDocumentador_ControlIngreso
    Public Property intIdControlIngreso As Integer
    Public Property intidAplicacion As Nullable(Of Integer)
    Public Property intidCategoria As Nullable(Of Integer)
    Public Property strTipoDocumento As String
    Public Property strCodigoCliente As String
    Public Property intTipoIdCliente As Nullable(Of Integer)
    Public Property strNroDocumento As String
    Public Property IDValidacionIngreso As Nullable(Of System.Guid)
    Public Property strPermiso As String
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
