'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblGestionOperacionesLog
    Public Property intIdOperacion As Integer
    Public Property strTipoOperacion As String
    Public Property intNroFolioOrigen As Nullable(Of Long)
    Public Property intNroFolioOperacion As Nullable(Of Long)
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String
    Public Property intIdLiqFolioOrigen As Nullable(Of Integer)
    Public Property dtmFechaProceso As Nullable(Of Date)
    Public Property numCantidad As Nullable(Of Decimal)

End Class
