'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblLiquidacionesDVLog
    Public Property intIdLiquidacionLog As Integer
    Public Property intLotId As Integer
    Public Property strLogDescripcion As String
    Public Property dtmFecha As Date
    Public Property strUsuario As String

End Class
