'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblMvtocontable
    Public Property intIdMvtocontable As Integer
    Public Property intIdLiquidacion As Integer
    Public Property dtmFechaContabilidad As Date
    Public Property strComprobante As String
    Public Property strCodigoComprobante As String
    Public Property intIdCuenta As Integer
    Public Property strDocumento As String
    Public Property intIdNaturaleza As Nullable(Of Integer)
    Public Property intIdConceptoContable As Nullable(Of Integer)
    Public Property intIdFuenteContable As Nullable(Of Integer)
    Public Property numDebito As Nullable(Of Decimal)
    Public Property numCredito As Nullable(Of Decimal)
    Public Property numBase As Nullable(Of Decimal)
    Public Property intIdMoneda As Nullable(Of Integer)
    Public Property numTasaCambio As Nullable(Of Decimal)
    Public Property strDetalle As String
    Public Property intIdCuentaMultiproducto As Nullable(Of Integer)
    Public Property strNroDocumento As String
    Public Property strNbreTercero As String
    Public Property intIdCentroCosto As Nullable(Of Integer)
    Public Property intIdPlanoContable As Integer
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String
    Public Property intIdTipoPortafolio As Integer
    Public Property strTipoMovimiento As String
    Public Property strNrofactura As String
    Public Property bitAnulada As Nullable(Of Boolean)
    Public Property strNuevaContabilidad As String

End Class
