'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblMensajesCumPolitica
    Public Property intidMensajeCumPolitica As Integer
    Public Property intEstadoCumplimiento As Integer
    Public Property strMensaje As String
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
