'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblNivelAutorizacion
    Public Property intidNivelAutorizacion As Integer
    Public Property intidSucursal As Integer
    Public Property bitAplicaValorInversion As Boolean
    Public Property numRangoInicial As Decimal
    Public Property numRangoFinal As Decimal
    Public Property intNumNivelAutorizacion As Integer
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
