'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProductos
    Public Property intIdProducto As Integer
    Public Property strNombreProducto As String
    Public Property strDescripcion As String
    Public Property intIdTipoProducto As Short
    Public Property intIdActivoSubyacente As Integer
    Public Property intIdTipoCumplimiento As Short
    Public Property intIdTipoEjercicio As Short
    Public Property intUltimoDiaNegociacion As Byte
    Public Property numValorNominalContrato As Decimal
    Public Property intIdTipoNegociacionPrima As Integer
    Public Property intIdEstado As Short
    Public Property strPrefijoProducto As String
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String
    Public Property intNroDecimalesPrecio As Byte
    Public Property intNroDecimalesPrima As Byte
    Public Property numTickPrecio As Nullable(Of Decimal)
    Public Property intMaximoNegociacion As Nullable(Of Decimal)
    Public Property intMinimoRegistro As Nullable(Of Integer)
    Public Property intMinimoNegociacionPolitica As Nullable(Of Integer)
    Public Property intTipoContrato As Nullable(Of Integer)
    Public Property numPorcenAutoretencion As Nullable(Of Decimal)
    Public Property intIdTipoLiquidacion As Nullable(Of Integer)
    Public Property intIdTipoDerivado As Nullable(Of Integer)
    Public Property intIdTipoCurva As Nullable(Of Integer)
    Public Property intIdTipoSubyacente As Integer
    Public Property bitPrecioPorcentual As Boolean
    Public Property intIdProductoSubyacente As Nullable(Of Integer)

End Class
