'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProductosVencimientos
    Public Property intIdProductoVencimiento As Integer
    Public Property intIdProducto As Integer
    Public Property strVencimiento As String
    Public Property strNemotecnico As String
    Public Property dtmFechaVencimiento As Date
    Public Property logActivo As Boolean
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String
    Public Property intUltimoDiaNegPV As Integer
    Public Property dtmFechaUltDiaNeg As Nullable(Of Date)

End Class
