'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPersonasTipoDocumento
    Public Property intIdTipoDocumento As Integer
    Public Property strCodigoTipoDocumento As String
    Public Property strTipoDocumento As String
    Public Property strAbreviatura As String
    Public Property logPersonaNatural As Boolean
    Public Property logPordefecto As Boolean
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
