'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPreciosDerivados
    Public Property intId As Integer
    Public Property numOrden As Nullable(Of Decimal)
    Public Property dtmFechaRegistro As Nullable(Of Date)
    Public Property strNemotecnico As String
    Public Property dtmFechaVencimiento As Nullable(Of Date)
    Public Property numStrike As Nullable(Of Decimal)
    Public Property numPrecio As Nullable(Of Decimal)
    Public Property strNemotecnicoSubyacente As String
    Public Property numPrecioSubyacente As Nullable(Of Decimal)
    Public Property numUltimoPrecio As Nullable(Of Decimal)
    Public Property numVariacionPrecio As Nullable(Of Decimal)
    Public Property strFuente As String
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
