'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTipoDocAutorizacion
    Public Property intidTipoDocAutorizacion As Integer
    Public Property intidTipoProducto As Nullable(Of Short)
    Public Property strCodigoTipoDocumento As String
    Public Property dtmActualizacion As Nullable(Of Date)
    Public Property strUsuario As String

End Class
