'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTipoOpcionProducto
    Public Property intIdTipoOpcionProducto As Short
    Public Property strCodigoTipoOpcion As String
    Public Property strNombreTipoOpcion As String
    Public Property intIdTipoProducto As Short
    Public Property bitProductosEspeciales As Boolean
    Public Property bitPrima As Boolean
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String

End Class
