'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTipoOrdenDuracion
    Public Property intIdTipoOrdenDuracion As Short
    Public Property strCodigoTipoOrdenDuracion As String
    Public Property strNombreTipoOrdenDuracion As String
    Public Property strDescripcion As String
    Public Property bitPorDefecto As Boolean
    Public Property bitRequiereFecha As Boolean
    Public Property intIdTipoListaAsociada As Nullable(Of Integer)
    Public Property strEtiquetaLista As String
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String
    Public Property bitVigenciaMax As Nullable(Of Boolean)
    Public Property intIdTipoOpcionProducto As Nullable(Of Short)
    Public Property bitPermiteSeleccionarTipoSesion As Boolean
    Public Property intNroDiasVencimiento As Nullable(Of Integer)

End Class
