'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTipoOrdenEjecucion
    Public Property intIdTipoOrdenEjecucion As Short
    Public Property strCodigoTipoOrdenEjecucion As String
    Public Property strNombreTipoOrdenEjecucion As String
    Public Property bitPorDefecto As Boolean
    Public Property bitCantidadMinima As Boolean
    Public Property strDescripcion As String
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String
    Public Property bitRequiereInstrumento As Boolean

End Class
