<?xml version="1.0" encoding="utf-8"?><Database Name="dbADIN" EntityNamespace="OyDOperaciones" Class="OyDOperacionesDatacontext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.tblLiquidaciones" Member="Operaciones">
    <Type Name="Operaciones" Id="ID1">
      <Column Name="intIDLiquidaciones" Type="System.Int32" DbType="INT NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lngIDComisionista" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="lngIDSucComisionista" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="lngID" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="lngParcial" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="strTipo" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="strDescripcionTipo" Type="System.String" DbType="Varchar(40) NOT NULL" CanBeNull="true" />
      <Column Name="strClaseOrden" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="strDescripcionClase" Type="System.String" DbType="Varchar(40) NOT NULL" CanBeNull="true" />
      <Column Name="strIDEspecie" Type="System.String" DbType="Varchar(15) NOT NULL" CanBeNull="true" />
      <Column Name="strNombreEspecie" Type="System.String" DbType="Varchar(50) NOT NULL" CanBeNull="true" />
      <Column Name="lngIDOrden" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="intFechaOrden" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="strNroOrden" Type="System.String" DbType="Varchar(10) NOT NULL" CanBeNull="true" />
      <Column Name="strPrefijo" Type="System.String" DbType="Varchar(5)" CanBeNull="true" />
      <Column Name="lngIDFactura" Type="System.Nullable(of System.Int32)" DbType="INT" CanBeNull="true" />
      <Column Name="strFacturada" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="lngIDComitente" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="true" />
      <Column Name="strNombreComitente" Type="System.String" DbType="Varchar(50) NOT NULL" CanBeNull="true" />
      <Column Name="lngIDOrdenante" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="true" />
      <Column Name="strNombreOrdenante" Type="System.String" DbType="Varchar(50) NOT NULL" CanBeNull="true" />
      <Column Name="lngIDBolsa" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="dblValBolsa" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bytIDRueda" Type="System.Int16" DbType="Smallint" CanBeNull="true" />
      <Column Name="dblTasaDescuento" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblTasaCompraVende" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strModalidad" Type="System.String" DbType="Varchar(2)" CanBeNull="true" />
      <Column Name="strIndicadorEconomico" Type="System.String" DbType="Varchar(2)" CanBeNull="true" />
      <Column Name="dblPuntosIndicador" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lngPlazo" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="dtmLiquidacion" Type="System.DateTime" DbType="Datetime NOT NULL" CanBeNull="true" />
      <Column Name="dtmCumplimiento" Type="System.DateTime" DbType="Datetime NOT NULL" CanBeNull="true" />
      <Column Name="dtmEmision" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="dtmVencimiento" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="logOtraPlaza" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" CanBeNull="true" />
      <Column Name="strPlaza" Type="System.String" DbType="Varchar(3)" CanBeNull="true" />
      <Column Name="lngIDComisionistaLocal" Type="System.Nullable(of System.Int32)" DbType="INT" CanBeNull="true" />
      <Column Name="lngIDComisionistaOtraPlaza" Type="System.Nullable(of System.Int32)" DbType="INT" CanBeNull="true" />
      <Column Name="lngIDCiudadOtraPlaza" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="strDescripcionCiudadOtraPlaza" Type="System.String" DbType="Varchar(40) NULL" CanBeNull="true" />
      <Column Name="dblTasaEfectiva" Type="System.Double" DbType="Float NOT NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curPrecio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curTransaccion" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curSubTotalLiq" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curTotalLiq" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curComision" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curRetencion" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curIntereses" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curValorIva" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lngDiasIntereses" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="dblFactorComisionPactada" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strMercado" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="strNroTitulo" Type="System.String" DbType="Varchar(25)" CanBeNull="true" />
      <Column Name="lngIDCiudadExpTitulo" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="lngPlazoOriginal" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="logAplazamiento" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" CanBeNull="true" />
      <Column Name="bytVersionPapeleta" Type="System.Int16" DbType="Smallint" CanBeNull="true" />
      <Column Name="dtmEmisionOriginal" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="dtmVencimientoOriginal" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="lngImpresiones" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="strFormaPago" Type="System.String" DbType="Varchar(2)" CanBeNull="true" />
      <Column Name="lngCtrlImpPapeleta" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="lngDiasVencimiento" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="strPosicionPropia" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="strTransaccion" Type="System.String" DbType="Varchar(2)" CanBeNull="true" />
      <Column Name="strTipoOperacion" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="lngDiasContado" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="logOrdinaria" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" CanBeNull="true" />
      <Column Name="strObjetoOrdenExtraordinaria" Type="System.String" DbType="Varchar(3)" CanBeNull="true" />
      <Column Name="lngNumPadre" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="lngParcialPadre" Type="System.Nullable(of System.Int32)" DbType="INT" CanBeNull="true" />
      <Column Name="dtmOperacionPadre" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="lngDiasTramo" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="logVendido" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" CanBeNull="true" />
      <Column Name="dtmVendido" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="logManual" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" CanBeNull="true" />
      <Column Name="dblValorTraslado" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblValorBrutoCompraVencida" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strAutoRetenedor" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="strSujeto" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="dblPcRenEfecCompraRet" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblPcRenEfecVendeRet" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strReinversion" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="strSwap" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="lngNroSwap" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="strCertificacion" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="dblDescuentoAcumula" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblPctRendimiento" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dtmFechaCompraVencido" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="dblPrecioCompraVencido" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strConstanciaEnajenacion" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="strRepoTitulo" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="dblServBolsaVble" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblServBolsaFijo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="logTraslado" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" CanBeNull="true" />
      <Column Name="strUBICACIONTITULO" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="strHoraGrabacion" Type="System.String" DbType="Varchar(8)" CanBeNull="true" />
      <Column Name="strOrigenOperacion" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="lngCodigoOperadorCompra" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="lngCodigoOperadorVende" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="strIdentificacionRemate" Type="System.String" DbType="Varchar(2)" CanBeNull="true" />
      <Column Name="strModalidaOperacion" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="strIndicadorPrecio" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="strPeriodoExdividendo" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="lngPlazoOperacionRepo" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="dblValorCaptacionRepo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lngVolumenCompraRepo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblPrecioNetoFraccion" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lngVolumenNetoFraccion" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lngCodigoContactoComercial" Type="System.String" DbType="Varchar(10)" CanBeNull="true" />
      <Column Name="lngNroFraccionOperacion" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="strIdentificacionPatrimonio1" Type="System.String" DbType="Varchar(3)" CanBeNull="true" />
      <Column Name="strTipoidentificacionCliente2" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="strNitCliente2" Type="System.String" DbType="Varchar(12)" CanBeNull="true" />
      <Column Name="strIdentificacionPatrimonio2" Type="System.String" DbType="Varchar(3)" CanBeNull="true" />
      <Column Name="strTipoIdentificacionCliente3" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="strNitCliente3" Type="System.String" DbType="Varchar(12)" CanBeNull="true" />
      <Column Name="strIdentificacionPatrimonio3" Type="System.String" DbType="Varchar(3)" CanBeNull="true" />
      <Column Name="strIndicadorOperacion" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="dblBaseRetencion" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblPorcRetencion" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblBaseRetencionTranslado" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblPorcRetencionTranslado" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblPorcIvaComision" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strIndicadorAcciones" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="strOperacionNegociada" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="dtmFechaConstancia" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="dblValorConstancia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strGeneraConstancia" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="logCargado" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" CanBeNull="true" />
      <Column Name="dtmActualizacion" Type="System.DateTime" DbType="Datetime NOT NULL" CanBeNull="true" />
      <Column Name="dtmCumplimientoTitulo" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="intNroLote" Type="System.Int32" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="dblValorEntregaContraPago" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strAquienSeEnviaRetencion" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="strIDBaseDias" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="true" />
      <Column Name="strTipoDeOferta" Type="System.String" DbType="Char(1)" CanBeNull="true" />
      <Column Name="intNroLoteENC" Type="System.Int32" DbType="INT" CanBeNull="true" />
      <Column Name="dtmContabilidadENC" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="strCodigoIntermediario" Type="System.String" DbType="Varchar(10)" CanBeNull="true" />
      <Column Name="InfoSesion" Type="System.String" DbType="Varchar(1000)" CanBeNull="true" />
      <Column Name="curValorExtemporaneo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strPosicionExtemporaneo" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="logRetardo" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" CanBeNull="true" />
      <Column Name="strParcialRet" Type="System.String" DbType="Varchar(10)" CanBeNull="true" />
      <Column Name="logRetardoPadre" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" CanBeNull="true" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="strInfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId1">
      <Argument Parameter="pintIDLiquidaciones" Member="intIDLiquidaciones" />
      <Argument Parameter="plngID" Member="lngID" />
      <Argument Parameter="plngParcial" Member="lngParcial" />
      <Argument Parameter="pstrTipo" Member="strTipo" />
      <Argument Parameter="pstrClaseOrden" Member="strClaseOrden" />
      <Argument Parameter="pstrIDEspecie" Member="strIDEspecie" />
      <Argument Parameter="plngIDOrden" Member="lngIDOrden" />
      <Argument Parameter="pstrPrefijo" Member="strPrefijo" />
      <Argument Parameter="plngIDFactura" Member="lngIDFactura" />
      <Argument Parameter="pstrFacturada" Member="strFacturada" />
      <Argument Parameter="plngIDComitente" Member="lngIDComitente" />
      <Argument Parameter="plngIDOrdenante" Member="lngIDOrdenante" />
      <Argument Parameter="plngIDBolsa" Member="lngIDBolsa" />
      <Argument Parameter="pdblValBolsa" Member="dblValBolsa" />
      <Argument Parameter="pbytIDRueda" Member="bytIDRueda" />
      <Argument Parameter="pdblTasaDescuento" Member="dblTasaDescuento" />
      <Argument Parameter="pdblTasaCompraVende" Member="dblTasaCompraVende" />
      <Argument Parameter="pstrModalidad" Member="strModalidad" />
      <Argument Parameter="pstrIndicadorEconomico" Member="strIndicadorEconomico" />
      <Argument Parameter="pdblPuntosIndicador" Member="dblPuntosIndicador" />
      <Argument Parameter="plngPlazo" Member="lngPlazo" />
      <Argument Parameter="pdtmLiquidacion" Member="dtmLiquidacion" />
      <Argument Parameter="pdtmCumplimiento" Member="dtmCumplimiento" />
      <Argument Parameter="pdtmEmision" Member="dtmEmision" />
      <Argument Parameter="pdtmVencimiento" Member="dtmVencimiento" />
      <Argument Parameter="plogOtraPlaza" Member="logOtraPlaza" />
      <Argument Parameter="pstrPlaza" Member="strPlaza" />
      <Argument Parameter="plngIDComisionistaLocal" Member="lngIDComisionistaLocal" />
      <Argument Parameter="plngIDComisionistaOtraPlaza" Member="lngIDComisionistaOtraPlaza" />
      <Argument Parameter="plngIDCiudadOtraPlaza" Member="lngIDCiudadOtraPlaza" />
      <Argument Parameter="pdblTasaEfectiva" Member="dblTasaEfectiva" />
      <Argument Parameter="pdblCantidad" Member="dblCantidad" />
      <Argument Parameter="pcurPrecio" Member="curPrecio" />
      <Argument Parameter="pcurTransaccion" Member="curTransaccion" />
      <Argument Parameter="pcurSubTotalLiq" Member="curSubTotalLiq" />
      <Argument Parameter="pcurTotalLiq" Member="curTotalLiq" />
      <Argument Parameter="pcurComision" Member="curComision" />
      <Argument Parameter="pcurRetencion" Member="curRetencion" />
      <Argument Parameter="pcurIntereses" Member="curIntereses" />
      <Argument Parameter="pcurValorIva" Member="curValorIva" />
      <Argument Parameter="plngDiasIntereses" Member="lngDiasIntereses" />
      <Argument Parameter="pdblFactorComisionPactada" Member="dblFactorComisionPactada" />
      <Argument Parameter="pstrMercado" Member="strMercado" />
      <Argument Parameter="pstrNroTitulo" Member="strNroTitulo" />
      <Argument Parameter="plngIDCiudadExpTitulo" Member="lngIDCiudadExpTitulo" />
      <Argument Parameter="plngPlazoOriginal" Member="lngPlazoOriginal" />
      <Argument Parameter="plogAplazamiento" Member="logAplazamiento" />
      <Argument Parameter="pbytVersionPapeleta" Member="bytVersionPapeleta" />
      <Argument Parameter="pdtmEmisionOriginal" Member="dtmEmisionOriginal" />
      <Argument Parameter="pdtmVencimientoOriginal" Member="dtmVencimientoOriginal" />
      <Argument Parameter="plngImpresiones" Member="lngImpresiones" />
      <Argument Parameter="pstrFormaPago" Member="strFormaPago" />
      <Argument Parameter="plngCtrlImpPapeleta" Member="lngCtrlImpPapeleta" />
      <Argument Parameter="plngDiasVencimiento" Member="lngDiasVencimiento" />
      <Argument Parameter="pstrPosicionPropia" Member="strPosicionPropia" />
      <Argument Parameter="pstrTransaccion" Member="strTransaccion" />
      <Argument Parameter="pstrTipoOperacion" Member="strTipoOperacion" />
      <Argument Parameter="plngDiasContado" Member="lngDiasContado" />
      <Argument Parameter="plogOrdinaria" Member="logOrdinaria" />
      <Argument Parameter="pstrObjetoOrdenExtraordinaria" Member="strObjetoOrdenExtraordinaria" />
      <Argument Parameter="plngNumPadre" Member="lngNumPadre" />
      <Argument Parameter="plngParcialPadre" Member="lngParcialPadre" />
      <Argument Parameter="pdtmOperacionPadre" Member="dtmOperacionPadre" />
      <Argument Parameter="plngDiasTramo" Member="lngDiasTramo" />
      <Argument Parameter="plogVendido" Member="logVendido" />
      <Argument Parameter="pdtmVendido" Member="dtmVendido" />
      <Argument Parameter="plogManual" Member="logManual" />
      <Argument Parameter="pdblValorTraslado" Member="dblValorTraslado" />
      <Argument Parameter="pdblValorBrutoCompraVencida" Member="dblValorBrutoCompraVencida" />
      <Argument Parameter="pstrAutoRetenedor" Member="strAutoRetenedor" />
      <Argument Parameter="pstrSujeto" Member="strSujeto" />
      <Argument Parameter="pdblPcRenEfecCompraRet" Member="dblPcRenEfecCompraRet" />
      <Argument Parameter="pdblPcRenEfecVendeRet" Member="dblPcRenEfecVendeRet" />
      <Argument Parameter="pstrReinversion" Member="strReinversion" />
      <Argument Parameter="pstrSwap" Member="strSwap" />
      <Argument Parameter="plngNroSwap" Member="lngNroSwap" />
      <Argument Parameter="pstrCertificacion" Member="strCertificacion" />
      <Argument Parameter="pdblDescuentoAcumula" Member="dblDescuentoAcumula" />
      <Argument Parameter="pdblPctRendimiento" Member="dblPctRendimiento" />
      <Argument Parameter="pdtmFechaCompraVencido" Member="dtmFechaCompraVencido" />
      <Argument Parameter="pdblPrecioCompraVencido" Member="dblPrecioCompraVencido" />
      <Argument Parameter="pstrConstanciaEnajenacion" Member="strConstanciaEnajenacion" />
      <Argument Parameter="pstrRepoTitulo" Member="strRepoTitulo" />
      <Argument Parameter="pdblServBolsaVble" Member="dblServBolsaVble" />
      <Argument Parameter="pdblServBolsaFijo" Member="dblServBolsaFijo" />
      <Argument Parameter="pstrUBICACIONTITULO" Member="strUBICACIONTITULO" />
      <Argument Parameter="pstrHoraGrabacion" Member="strHoraGrabacion" />
      <Argument Parameter="pstrOrigenOperacion" Member="strOrigenOperacion" />
      <Argument Parameter="plngCodigoOperadorCompra" Member="lngCodigoOperadorCompra" />
      <Argument Parameter="plngCodigoOperadorVende" Member="lngCodigoOperadorVende" />
      <Argument Parameter="pstrIdentificacionRemate" Member="strIdentificacionRemate" />
      <Argument Parameter="pstrModalidaOperacion" Member="strModalidaOperacion" />
      <Argument Parameter="pstrIndicadorPrecio" Member="strIndicadorPrecio" />
      <Argument Parameter="pstrPeriodoExdividendo" Member="strPeriodoExdividendo" />
      <Argument Parameter="plngPlazoOperacionRepo" Member="lngPlazoOperacionRepo" />
      <Argument Parameter="pdblValorCaptacionRepo" Member="dblValorCaptacionRepo" />
      <Argument Parameter="plngVolumenCompraRepo" Member="lngVolumenCompraRepo" />
      <Argument Parameter="pdblPrecioNetoFraccion" Member="dblPrecioNetoFraccion" />
      <Argument Parameter="plngVolumenNetoFraccion" Member="lngVolumenNetoFraccion" />
      <Argument Parameter="plngCodigoContactoComercial" Member="lngCodigoContactoComercial" />
      <Argument Parameter="plngNroFraccionOperacion" Member="lngNroFraccionOperacion" />
      <Argument Parameter="pstrIdentificacionPatrimonio1" Member="strIdentificacionPatrimonio1" />
      <Argument Parameter="pstrTipoidentificacionCliente2" Member="strTipoidentificacionCliente2" />
      <Argument Parameter="pstrNitCliente2" Member="strNitCliente2" />
      <Argument Parameter="pstrIdentificacionPatrimonio2" Member="strIdentificacionPatrimonio2" />
      <Argument Parameter="pstrTipoIdentificacionCliente3" Member="strTipoIdentificacionCliente3" />
      <Argument Parameter="pstrNitCliente3" Member="strNitCliente3" />
      <Argument Parameter="pstrIdentificacionPatrimonio3" Member="strIdentificacionPatrimonio3" />
      <Argument Parameter="pstrIndicadorOperacion" Member="strIndicadorOperacion" />
      <Argument Parameter="pdblBaseRetencion" Member="dblBaseRetencion" />
      <Argument Parameter="pdblPorcRetencion" Member="dblPorcRetencion" />
      <Argument Parameter="pdblBaseRetencionTranslado" Member="dblBaseRetencionTranslado" />
      <Argument Parameter="pdblPorcRetencionTranslado" Member="dblPorcRetencionTranslado" />
      <Argument Parameter="pdblPorcIvaComision" Member="dblPorcIvaComision" />
      <Argument Parameter="pstrIndicadorAcciones" Member="strIndicadorAcciones" />
      <Argument Parameter="pstrOperacionNegociada" Member="strOperacionNegociada" />
      <Argument Parameter="pdtmFechaConstancia" Member="dtmFechaConstancia" />
      <Argument Parameter="pdblValorConstancia" Member="dblValorConstancia" />
      <Argument Parameter="pstrGeneraConstancia" Member="strGeneraConstancia" />
      <Argument Parameter="plogCargado" Member="logCargado" />
      <Argument Parameter="pdtmCumplimientoTitulo" Member="dtmCumplimientoTitulo" />
      <Argument Parameter="pintNroLote" Member="intNroLote" />
      <Argument Parameter="pdblValorEntregaContraPago" Member="dblValorEntregaContraPago" />
      <Argument Parameter="pstrAquienSeEnviaRetencion" Member="strAquienSeEnviaRetencion" />
      <Argument Parameter="pstrIDBaseDias" Member="strIDBaseDias" />
      <Argument Parameter="pstrTipoDeOferta" Member="strTipoDeOferta" />
      <Argument Parameter="pintNroLoteENC" Member="intNroLoteENC" />
      <Argument Parameter="pdtmContabilidadENC" Member="dtmContabilidadENC" />
      <Argument Parameter="pstrCodigoIntermediario" Member="strCodigoIntermediario" />
      <Argument Parameter="pcurValorExtemporaneo" Member="curValorExtemporaneo" />
      <Argument Parameter="pstrPosicionExtemporaneo" Member="strPosicionExtemporaneo" />
      <Argument Parameter="pstrUsuario" Member="strUsuario" />
      <Argument Parameter="pstrInfoSesion" Member="strInfoSesion" />
      <Argument Parameter="pstrMsgValidacion" Member="strMsgValidacion" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId1">
      <Argument Parameter="pintIDLiquidaciones" Member="intIDLiquidaciones" />
      <Argument Parameter="plngID" Member="lngID" />
      <Argument Parameter="plngParcial" Member="lngParcial" />
      <Argument Parameter="pstrTipo" Member="strTipo" />
      <Argument Parameter="pstrClaseOrden" Member="strClaseOrden" />
      <Argument Parameter="pstrIDEspecie" Member="strIDEspecie" />
      <Argument Parameter="plngIDOrden" Member="lngIDOrden" />
      <Argument Parameter="pstrPrefijo" Member="strPrefijo" />
      <Argument Parameter="plngIDFactura" Member="lngIDFactura" />
      <Argument Parameter="pstrFacturada" Member="strFacturada" />
      <Argument Parameter="plngIDComitente" Member="lngIDComitente" />
      <Argument Parameter="plngIDOrdenante" Member="lngIDOrdenante" />
      <Argument Parameter="plngIDBolsa" Member="lngIDBolsa" />
      <Argument Parameter="pdblValBolsa" Member="dblValBolsa" />
      <Argument Parameter="pbytIDRueda" Member="bytIDRueda" />
      <Argument Parameter="pdblTasaDescuento" Member="dblTasaDescuento" />
      <Argument Parameter="pdblTasaCompraVende" Member="dblTasaCompraVende" />
      <Argument Parameter="pstrModalidad" Member="strModalidad" />
      <Argument Parameter="pstrIndicadorEconomico" Member="strIndicadorEconomico" />
      <Argument Parameter="pdblPuntosIndicador" Member="dblPuntosIndicador" />
      <Argument Parameter="plngPlazo" Member="lngPlazo" />
      <Argument Parameter="pdtmLiquidacion" Member="dtmLiquidacion" />
      <Argument Parameter="pdtmCumplimiento" Member="dtmCumplimiento" />
      <Argument Parameter="pdtmEmision" Member="dtmEmision" />
      <Argument Parameter="pdtmVencimiento" Member="dtmVencimiento" />
      <Argument Parameter="plogOtraPlaza" Member="logOtraPlaza" />
      <Argument Parameter="pstrPlaza" Member="strPlaza" />
      <Argument Parameter="plngIDComisionistaLocal" Member="lngIDComisionistaLocal" />
      <Argument Parameter="plngIDComisionistaOtraPlaza" Member="lngIDComisionistaOtraPlaza" />
      <Argument Parameter="plngIDCiudadOtraPlaza" Member="lngIDCiudadOtraPlaza" />
      <Argument Parameter="pdblTasaEfectiva" Member="dblTasaEfectiva" />
      <Argument Parameter="pdblCantidad" Member="dblCantidad" />
      <Argument Parameter="pcurPrecio" Member="curPrecio" />
      <Argument Parameter="pcurTransaccion" Member="curTransaccion" />
      <Argument Parameter="pcurSubTotalLiq" Member="curSubTotalLiq" />
      <Argument Parameter="pcurTotalLiq" Member="curTotalLiq" />
      <Argument Parameter="pcurComision" Member="curComision" />
      <Argument Parameter="pcurRetencion" Member="curRetencion" />
      <Argument Parameter="pcurIntereses" Member="curIntereses" />
      <Argument Parameter="pcurValorIva" Member="curValorIva" />
      <Argument Parameter="plngDiasIntereses" Member="lngDiasIntereses" />
      <Argument Parameter="pdblFactorComisionPactada" Member="dblFactorComisionPactada" />
      <Argument Parameter="pstrMercado" Member="strMercado" />
      <Argument Parameter="pstrNroTitulo" Member="strNroTitulo" />
      <Argument Parameter="plngIDCiudadExpTitulo" Member="lngIDCiudadExpTitulo" />
      <Argument Parameter="plngPlazoOriginal" Member="lngPlazoOriginal" />
      <Argument Parameter="plogAplazamiento" Member="logAplazamiento" />
      <Argument Parameter="pbytVersionPapeleta" Member="bytVersionPapeleta" />
      <Argument Parameter="pdtmEmisionOriginal" Member="dtmEmisionOriginal" />
      <Argument Parameter="pdtmVencimientoOriginal" Member="dtmVencimientoOriginal" />
      <Argument Parameter="plngImpresiones" Member="lngImpresiones" />
      <Argument Parameter="pstrFormaPago" Member="strFormaPago" />
      <Argument Parameter="plngCtrlImpPapeleta" Member="lngCtrlImpPapeleta" />
      <Argument Parameter="plngDiasVencimiento" Member="lngDiasVencimiento" />
      <Argument Parameter="pstrPosicionPropia" Member="strPosicionPropia" />
      <Argument Parameter="pstrTransaccion" Member="strTransaccion" />
      <Argument Parameter="pstrTipoOperacion" Member="strTipoOperacion" />
      <Argument Parameter="plngDiasContado" Member="lngDiasContado" />
      <Argument Parameter="plogOrdinaria" Member="logOrdinaria" />
      <Argument Parameter="pstrObjetoOrdenExtraordinaria" Member="strObjetoOrdenExtraordinaria" />
      <Argument Parameter="plngNumPadre" Member="lngNumPadre" />
      <Argument Parameter="plngParcialPadre" Member="lngParcialPadre" />
      <Argument Parameter="pdtmOperacionPadre" Member="dtmOperacionPadre" />
      <Argument Parameter="plngDiasTramo" Member="lngDiasTramo" />
      <Argument Parameter="plogVendido" Member="logVendido" />
      <Argument Parameter="pdtmVendido" Member="dtmVendido" />
      <Argument Parameter="plogManual" Member="logManual" />
      <Argument Parameter="pdblValorTraslado" Member="dblValorTraslado" />
      <Argument Parameter="pdblValorBrutoCompraVencida" Member="dblValorBrutoCompraVencida" />
      <Argument Parameter="pstrAutoRetenedor" Member="strAutoRetenedor" />
      <Argument Parameter="pstrSujeto" Member="strSujeto" />
      <Argument Parameter="pdblPcRenEfecCompraRet" Member="dblPcRenEfecCompraRet" />
      <Argument Parameter="pdblPcRenEfecVendeRet" Member="dblPcRenEfecVendeRet" />
      <Argument Parameter="pstrReinversion" Member="strReinversion" />
      <Argument Parameter="pstrSwap" Member="strSwap" />
      <Argument Parameter="plngNroSwap" Member="lngNroSwap" />
      <Argument Parameter="pstrCertificacion" Member="strCertificacion" />
      <Argument Parameter="pdblDescuentoAcumula" Member="dblDescuentoAcumula" />
      <Argument Parameter="pdblPctRendimiento" Member="dblPctRendimiento" />
      <Argument Parameter="pdtmFechaCompraVencido" Member="dtmFechaCompraVencido" />
      <Argument Parameter="pdblPrecioCompraVencido" Member="dblPrecioCompraVencido" />
      <Argument Parameter="pstrConstanciaEnajenacion" Member="strConstanciaEnajenacion" />
      <Argument Parameter="pstrRepoTitulo" Member="strRepoTitulo" />
      <Argument Parameter="pdblServBolsaVble" Member="dblServBolsaVble" />
      <Argument Parameter="pdblServBolsaFijo" Member="dblServBolsaFijo" />
      <Argument Parameter="pstrUBICACIONTITULO" Member="strUBICACIONTITULO" />
      <Argument Parameter="pstrHoraGrabacion" Member="strHoraGrabacion" />
      <Argument Parameter="pstrOrigenOperacion" Member="strOrigenOperacion" />
      <Argument Parameter="plngCodigoOperadorCompra" Member="lngCodigoOperadorCompra" />
      <Argument Parameter="plngCodigoOperadorVende" Member="lngCodigoOperadorVende" />
      <Argument Parameter="pstrIdentificacionRemate" Member="strIdentificacionRemate" />
      <Argument Parameter="pstrModalidaOperacion" Member="strModalidaOperacion" />
      <Argument Parameter="pstrIndicadorPrecio" Member="strIndicadorPrecio" />
      <Argument Parameter="pstrPeriodoExdividendo" Member="strPeriodoExdividendo" />
      <Argument Parameter="plngPlazoOperacionRepo" Member="lngPlazoOperacionRepo" />
      <Argument Parameter="pdblValorCaptacionRepo" Member="dblValorCaptacionRepo" />
      <Argument Parameter="plngVolumenCompraRepo" Member="lngVolumenCompraRepo" />
      <Argument Parameter="pdblPrecioNetoFraccion" Member="dblPrecioNetoFraccion" />
      <Argument Parameter="plngVolumenNetoFraccion" Member="lngVolumenNetoFraccion" />
      <Argument Parameter="plngCodigoContactoComercial" Member="lngCodigoContactoComercial" />
      <Argument Parameter="plngNroFraccionOperacion" Member="lngNroFraccionOperacion" />
      <Argument Parameter="pstrIdentificacionPatrimonio1" Member="strIdentificacionPatrimonio1" />
      <Argument Parameter="pstrTipoidentificacionCliente2" Member="strTipoidentificacionCliente2" />
      <Argument Parameter="pstrNitCliente2" Member="strNitCliente2" />
      <Argument Parameter="pstrIdentificacionPatrimonio2" Member="strIdentificacionPatrimonio2" />
      <Argument Parameter="pstrTipoIdentificacionCliente3" Member="strTipoIdentificacionCliente3" />
      <Argument Parameter="pstrNitCliente3" Member="strNitCliente3" />
      <Argument Parameter="pstrIdentificacionPatrimonio3" Member="strIdentificacionPatrimonio3" />
      <Argument Parameter="pstrIndicadorOperacion" Member="strIndicadorOperacion" />
      <Argument Parameter="pdblBaseRetencion" Member="dblBaseRetencion" />
      <Argument Parameter="pdblPorcRetencion" Member="dblPorcRetencion" />
      <Argument Parameter="pdblBaseRetencionTranslado" Member="dblBaseRetencionTranslado" />
      <Argument Parameter="pdblPorcRetencionTranslado" Member="dblPorcRetencionTranslado" />
      <Argument Parameter="pdblPorcIvaComision" Member="dblPorcIvaComision" />
      <Argument Parameter="pstrIndicadorAcciones" Member="strIndicadorAcciones" />
      <Argument Parameter="pstrOperacionNegociada" Member="strOperacionNegociada" />
      <Argument Parameter="pdtmFechaConstancia" Member="dtmFechaConstancia" />
      <Argument Parameter="pdblValorConstancia" Member="dblValorConstancia" />
      <Argument Parameter="pstrGeneraConstancia" Member="strGeneraConstancia" />
      <Argument Parameter="plogCargado" Member="logCargado" />
      <Argument Parameter="pdtmCumplimientoTitulo" Member="dtmCumplimientoTitulo" />
      <Argument Parameter="pintNroLote" Member="intNroLote" />
      <Argument Parameter="pdblValorEntregaContraPago" Member="dblValorEntregaContraPago" />
      <Argument Parameter="pstrAquienSeEnviaRetencion" Member="strAquienSeEnviaRetencion" />
      <Argument Parameter="pstrIDBaseDias" Member="strIDBaseDias" />
      <Argument Parameter="pstrTipoDeOferta" Member="strTipoDeOferta" />
      <Argument Parameter="pintNroLoteENC" Member="intNroLoteENC" />
      <Argument Parameter="pdtmContabilidadENC" Member="dtmContabilidadENC" />
      <Argument Parameter="pstrCodigoIntermediario" Member="strCodigoIntermediario" />
      <Argument Parameter="pcurValorExtemporaneo" Member="curValorExtemporaneo" />
      <Argument Parameter="pstrPosicionExtemporaneo" Member="strPosicionExtemporaneo" />
      <Argument Parameter="pstrUsuario" Member="strUsuario" />
      <Argument Parameter="pstrInfoSesion" Member="strInfoSesion" />
      <Argument Parameter="pstrMsgValidacion" Member="strMsgValidacion" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId2">
      <Argument Parameter="pintIDLiquidaciones" Member="intIDLiquidaciones" />
      <Argument Parameter="pstrUsuario" Member="strUsuario" />
      <Argument Parameter="pstrInfoSesion" Member="strInfoSesion" />
      <Argument Parameter="pstrMsgValidacion" Member="strMsgValidacion" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.tblReceptoresOrdenes" Member="OperacionesReceptores">
    <Type Name="OperacionesReceptores" Id="ID3">
      <Column Name="intIDReceptoresOrdenes" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strTipoOrden" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="strClaseOrden" Type="System.String" DbType="Varchar(1) NOT NULL" CanBeNull="true" />
      <Column Name="lngIDOrden" Type="System.int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="lngVersion" Type="System.int32" DbType="Int NOT NULL" CanBeNull="true" />
      <Column Name="strIDReceptor" Type="System.String" DbType="Varchar(4) NOT NULL" CanBeNull="true" />
      <Column Name="logLider" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="true" />
      <Column Name="dblPorcentaje" Type="System.Double" DbType="Float NOT NULL" CanBeNull="true" />
      <Column Name="strNombre" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="strInfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId3">
      <Argument Parameter="pstrTipoOrden" Member="strTipoOrden" />
      <Argument Parameter="pstrClaseOrden" Member="strClaseOrden" />
      <Argument Parameter="plngIDOrden" Member="lngIDOrden" />
      <Argument Parameter="plngVersion" Member="lngVersion" />
      <Argument Parameter="pstrIDReceptor" Member="strIDReceptor" />
      <Argument Parameter="plogLider" Member="logLider" />
      <Argument Parameter="pdblPorcentaje" Member="dblPorcentaje" />
      <Argument Parameter="pstrUsuario" Member="strUsuario" />
      <Argument Parameter="pintIDReceptoresOrdenes" Member="intIDReceptoresOrdenes" />
      <Argument Parameter="InfoSesion" Member="strInfoSesion" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId3">
      <Argument Parameter="pstrTipoOrden" Member="strTipoOrden" />
      <Argument Parameter="pstrClaseOrden" Member="strClaseOrden" />
      <Argument Parameter="plngIDOrden" Member="lngIDOrden" />
      <Argument Parameter="plngVersion" Member="lngVersion" />
      <Argument Parameter="pstrIDReceptor" Member="strIDReceptor" />
      <Argument Parameter="plogLider" Member="logLider" />
      <Argument Parameter="pdblPorcentaje" Member="dblPorcentaje" />
      <Argument Parameter="pstrUsuario" Member="strUsuario" />
      <Argument Parameter="pintIDReceptoresOrdenes" Member="intIDReceptoresOrdenes" />
      <Argument Parameter="InfoSesion" Member="strInfoSesion" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId4">
      <Argument Parameter="pintIDReceptoresOrdenes" Member="intIDReceptoresOrdenes" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.tblBeneficiariosOrdenes" Member="OperacionesBeneficiarios">
    <Type Name="OperacionesBeneficiarios" Id="ID4">
      <Column Name="intIDBeneficiariosOrdenes" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
      <Column Name="strTipoIdentificacion" Type="System.String" DbType="Varchar(4) NOT NULL" CanBeNull="true" />
      <Column Name="lngNroDocumento" Type="System.Decimal" DbType="numeric (15, 0) NOT NULL" CanBeNull="true" />
      <Column Name="strParentesco" Type="System.String" DbType="Varchar(15)" CanBeNull="true" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="strInfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblEspeciesLiquidaciones" Member="OperacionesEspecies">
    <Type Name="OperacionesEspecies" Id="ID5">
      <Column Name="intIDEspeciesLiquidaciones" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strIDEspecie" Type="System.String" DbType="Varchar(15)" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="Varchar(50)" CanBeNull="false" />
      <Column Name="strDescripcion" Type="System.String" DbType="Varchar(50)" CanBeNull="false" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="strInfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAplazamientosLiquidaciones" Member="OperacionesAplazamientos">
    <Type Name="OperacionesAplazamientos" Id="ID6">
      <Column Name="intIDAplazamientos" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strAplazamiento" Type="System.String" DbType="Varchar(15)" CanBeNull="false" />
      <Column Name="dtmCumplimiento" Type="System.DateTime" DbType="datetime" CanBeNull="false" />
      <Column Name="dtmActualizacion" Type="System.DateTime" DbType="datetime" CanBeNull="false" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="strInfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblCustodiasLiquidaciones" Member="OperacionesCustodias">
    <Type Name="OperacionesCustodias" Id="ID7">
      <Column Name="intIDCustodia" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lngIdRecibo" Type="System.int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lngSecuencia" Type="System.int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strEstado" Type="System.String" DbType="Varchar(1)" CanBeNull="false" />
      <Column Name="strEstadoActual" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="strUsuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="true" />
      <Column Name="strInfoSesion" Type="System.String" DbType="Varchar(max) NULL" CanBeNull="true" />
      <Column Name="strMsgValidacion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblLiquidacionesOrdenes" Member="LiquidacionesOrdenes">
    <Type Name="LiquidacionesOrdenes" Id="ID2">
      <Column Name="strObjeto" Type="System.String" DbType="char(3) NOT NULL" CanBeNull="true" />
      <Column Name="logOrdinaria" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="dblComisionPactada" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="intIDOrdenes" Type="System.int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblLiquidacionesConsultar" Member="LiquidacionesConsultar">
    <Type Name="LiquidacionesConsultar" Id="ID8">
      <Column Name="lngIDComitente" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="false" />
      <Column Name="strComitente" Type="System.String" DbType="Varchar(50)" CanBeNull="false" />
      <Column Name="lngIDOrdenante" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="false" />
      <Column Name="strOrdenante" Type="System.String" DbType="Varchar(50)" CanBeNull="false" />
      <Column Name="logOrdinaria" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="strObjeto" Type="System.String" DbType="Char(3)" CanBeNull="false" />
      <Column Name="strEstado" Type="System.String" DbType="Char(1)" CanBeNull="false" />
      <Column Name="strTipo" Type="System.String" DbType="Char(1)" CanBeNull="false" />
      <Column Name="strClase" Type="System.String" DbType="Char(1)" CanBeNull="false" />
      <Column Name="lngID" Type="System.int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dtmOrden" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="strUBICACIONTITULO" Type="System.String" DbType="Varchar(1)" CanBeNull="false" />
      <Column Name="strIDEspecie" Type="System.String" DbType="Varchar(15)" CanBeNull="false" />
      <Column Name="strEspecie" Type="System.String" DbType="Varchar(50)" CanBeNull="false" />
      <Column Name="lngIDClase" Type="System.int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dblInferior" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblSuperior" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblCantidad" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblComisionPactada" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strModalidad" Type="System.String" DbType="Varchar(2)" CanBeNull="false" />
      <Column Name="dtmEmision" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="dtmVencimiento" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="dblTasaInicial" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblTasaNominal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="logRepo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="logEnPesos" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="dblPrecio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblPuntosIndicador" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="intPlazo" Type="System.int32" DbType="Int" CanBeNull="true" />
      <Column Name="strIndicador" Type="System.String" DbType="Varchar(15)" CanBeNull="true" />
      <Column Name="dblTasaEfectiva" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblconsultarcantidad" Member="ConsultarCantidad">
    <Type Name="ConsultarCantidad" Id="ID9">
      <Column Name="dblCantidadLiq" Type="System.Double" DbType="Float" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="dblCantidadOrden" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblmodificacionvalidar" Member="ModificacionValidar">
    <Type Name="ModificacionValidar" Id="ID10">
      <Column Name="intID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="logExitoso" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="strMensaje" Type="System.String" DbType="Varchar(255)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>  
  <Table Name="dbo.tblRetardoOperaciones" Member="RetardoOperacionesActualizar">
    <Type Name="RetardoOperacionesActualizar" Id="ID11">
      <Column Name="intID" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="logExitoso" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="strMensaje" Type="System.String" DbType="Varchar(255)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="CF.tblRetardoOperaciones_Retardo" Member="RetardoOperaciones">
    <Type Name="RetardoOperaciones" Id="ID12">
      <Column Name="intIDRetardo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dtmFecha" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="intCuentaInversionistaDCVL" Type="System.Nullable(of System.Int32)" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="strNemoEspecie" Type="System.String" DbType="Varchar(15) NOT NULL" CanBeNull="true" />
      <Column Name="strTipo" Type="System.String" DbType="Varchar(15) NOT NULL" CanBeNull="true" />
      <Column Name="dblNetoTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="true" />
      <Column Name="logProcesado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <UpdateFunction FunctionId="UpdateRetardoOperaciones">
    </UpdateFunction>
  </Table>
  <Table Name="CF.tblRetardoOperaciones_Liquidaciones" Member="RetardoOperacionesDetalle">
    <Type Name="RetardoOperacionesDetalle" Id="ID13">
      <Column Name="intIDRetardoOperacionesDetalle" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lngIDComitente" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="true" />
      <Column Name="intIDLiquidaciones" Type="System.Nullable(of System.Int32)" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="lngID" Type="System.Nullable(of System.Int32)" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="lngParcial" Type="System.Nullable(of System.Int32)" DbType="INT NOT NULL" CanBeNull="true" />
      <Column Name="strTipo" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="true" />
      <Column Name="strClaseOrden" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="true" />
      <Column Name="dtmLiquidacion" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dtmCumplimientoTitulo" Type="System.Nullable(of System.DateTime)" DbType="Datetime NULL" CanBeNull="true" />
      <Column Name="dblPrecio" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dblCantidad" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="dblRetardo" Type="System.Double" DbType="Float NULL" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <UpdateFunction FunctionId="UpdateRetardoOperacionesDetalle">
    </UpdateFunction>
  </Table>
  <Function Id="FunctionId1" Name="dbo.uspOyDNet_Operaciones_Actualizar" Method="uspOyDNet_Operaciones_Actualizar">
    <Parameter Name="pintIDLiquidaciones" Type="System.Int32" DbType="INT NOT NULL" Direction="InOut" />
    <Parameter Name="plngID" Type="System.Int32" DbType="INT NOT NULL" />
    <Parameter Name="plngParcial" Type="System.Int32" DbType="INT NOT NULL" />
    <Parameter Name="pstrTipo" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pstrClaseOrden" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15) NOT NULL" />
    <Parameter Name="plngIDOrden" Type="System.Int32" DbType="INT NOT NULL" />
    <Parameter Name="pstrPrefijo" Type="System.String" DbType="Varchar(5)" />
    <Parameter Name="plngIDFactura" Type="System.Nullable(of System.Int32)" DbType="INT" />
    <Parameter Name="pstrFacturada" Type="System.String" DbType="Varchar(1)" />
    <Parameter Name="plngIDComitente" Type="System.String" DbType="Char(17) NOT NULL" />
    <Parameter Name="plngIDOrdenante" Type="System.String" DbType="Char(17) NOT NULL" />
    <Parameter Name="plngIDBolsa" Type="System.Int32" DbType="INT NOT NULL" />
    <Parameter Name="pdblValBolsa" Type="System.Double" DbType="Float" />
    <Parameter Name="pbytIDRueda" Type="System.Int16" DbType="Smallint" />
    <Parameter Name="pdblTasaDescuento" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblTasaCompraVende" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrModalidad" Type="System.String" DbType="Varchar(2)" />
    <Parameter Name="pstrIndicadorEconomico" Type="System.String" DbType="Varchar(2)" />
    <Parameter Name="pdblPuntosIndicador" Type="System.Double" DbType="Float" />
    <Parameter Name="plngPlazo" Type="System.Int32" DbType="INT" />
    <Parameter Name="pdtmLiquidacion" Type="System.DateTime" DbType="Datetime NOT NULL" />
    <Parameter Name="pdtmCumplimiento" Type="System.DateTime" DbType="Datetime NOT NULL" />
    <Parameter Name="pdtmEmision" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="pdtmVencimiento" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="plogOtraPlaza" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Parameter Name="pstrPlaza" Type="System.String" DbType="Varchar(3)" />
    <Parameter Name="plngIDComisionistaLocal" Type="System.Nullable(of System.Int32)" DbType="INT" />
    <Parameter Name="plngIDComisionistaOtraPlaza" Type="System.Nullable(of System.Int32)" DbType="INT" />
    <Parameter Name="plngIDCiudadOtraPlaza" Type="System.Int32" DbType="INT" />
    <Parameter Name="pdblTasaEfectiva" Type="System.Double" DbType="Float NOT NULL" />
    <Parameter Name="pdblCantidad" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurPrecio" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurTransaccion" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurSubTotalLiq" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurTotalLiq" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurComision" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurRetencion" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurIntereses" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurValorIva" Type="System.Double" DbType="Float" />
    <Parameter Name="plngDiasIntereses" Type="System.Int32" DbType="INT" />
    <Parameter Name="pdblFactorComisionPactada" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrMercado" Type="System.String" DbType="Varchar(1)" />
    <Parameter Name="pstrNroTitulo" Type="System.String" DbType="Varchar(25)" />
    <Parameter Name="plngIDCiudadExpTitulo" Type="System.Int32" DbType="INT" />
    <Parameter Name="plngPlazoOriginal" Type="System.Int32" DbType="INT" />
    <Parameter Name="plogAplazamiento" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Parameter Name="pbytVersionPapeleta" Type="System.Int16" DbType="Smallint" />
    <Parameter Name="pdtmEmisionOriginal" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="pdtmVencimientoOriginal" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="plngImpresiones" Type="System.Int32" DbType="INT" />
    <Parameter Name="pstrFormaPago" Type="System.String" DbType="Varchar(2)" />
    <Parameter Name="plngCtrlImpPapeleta" Type="System.Int32" DbType="INT" />
    <Parameter Name="plngDiasVencimiento" Type="System.Int32" DbType="INT" />
    <Parameter Name="pstrPosicionPropia" Type="System.String" DbType="Varchar(1)" />
    <Parameter Name="pstrTransaccion" Type="System.String" DbType="Varchar(2)" />
    <Parameter Name="pstrTipoOperacion" Type="System.String" DbType="Varchar(1)" />
    <Parameter Name="plngDiasContado" Type="System.Int32" DbType="INT" />
    <Parameter Name="plogOrdinaria" Type="System.Nullable(of System.Boolean)" DbType="bit" />
    <Parameter Name="pstrObjetoOrdenExtraordinaria" Type="System.String" DbType="varchar(3)" />
    <Parameter Name="plngNumPadre" Type="System.Int32" DbType="INT" />
    <Parameter Name="plngParcialPadre" Type="System.Nullable(of System.Int32)" DbType="INT" />
    <Parameter Name="pdtmOperacionPadre" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="plngDiasTramo" Type="System.Int32" DbType="INT" />
    <Parameter Name="plogVendido" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Parameter Name="pdtmVendido" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="plogManual" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Parameter Name="pdblValorTraslado" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblValorBrutoCompraVencida" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrAutoRetenedor" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pstrSujeto" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pdblPcRenEfecCompraRet" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblPcRenEfecVendeRet" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrReinversion" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pstrSwap" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="plngNroSwap" Type="System.Int32" DbType="INT" />
    <Parameter Name="pstrCertificacion" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pdblDescuentoAcumula" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblPctRendimiento" Type="System.Double" DbType="Float" />
    <Parameter Name="pdtmFechaCompraVencido" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="pdblPrecioCompraVencido" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrConstanciaEnajenacion" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pstrRepoTitulo" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pdblServBolsaVble" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblServBolsaFijo" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrTraslado" Type="System.String" DbType="Varchar(1)" />
    <Parameter Name="pstrUBICACIONTITULO" Type="System.String" DbType="Varchar(1)" />
    <Parameter Name="pstrHoraGrabacion" Type="System.String" DbType="Varchar(8)" />
    <Parameter Name="pstrOrigenOperacion" Type="System.String" DbType="Varchar(1)" />
    <Parameter Name="plngCodigoOperadorCompra" Type="System.Int32" DbType="INT" />
    <Parameter Name="plngCodigoOperadorVende" Type="System.Int32" DbType="INT" />
    <Parameter Name="pstrIdentificacionRemate" Type="System.String" DbType="Varchar(2)" />
    <Parameter Name="pstrModalidaOperacion" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrIndicadorPrecio" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrPeriodoExdividendo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngPlazoOperacionRepo" Type="System.Int32" DbType="INT" />
    <Parameter Name="pdblValorCaptacionRepo" Type="System.Double" DbType="Float" />
    <Parameter Name="plngVolumenCompraRepo" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblPrecioNetoFraccion" Type="System.Double" DbType="Float" />
    <Parameter Name="plngVolumenNetoFraccion" Type="System.Double" DbType="Float" />
    <Parameter Name="plngCodigoContactoComercial" Type="System.String" DbType="Varchar(10)" />
    <Parameter Name="plngNroFraccionOperacion" Type="System.Int32" DbType="INT" />
    <Parameter Name="pstrIdentificacionPatrimonio1" Type="System.String" DbType="Varchar(3)" />
    <Parameter Name="pstrTipoidentificacionCliente2" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrNitCliente2" Type="System.String" DbType="Varchar(12)" />
    <Parameter Name="pstrIdentificacionPatrimonio2" Type="System.String" DbType="Varchar(3)" />
    <Parameter Name="pstrTipoIdentificacionCliente3" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrNitCliente3" Type="System.String" DbType="Varchar(12)" />
    <Parameter Name="pstrIdentificacionPatrimonio3" Type="System.String" DbType="Varchar(3)" />
    <Parameter Name="pstrIndicadorOperacion" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pdblBaseRetencion" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblPorcRetencion" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblBaseRetencionTranslado" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblPorcRetencionTranslado" Type="System.Double" DbType="Float" />
    <Parameter Name="pdblPorcIvaComision" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrIndicadorAcciones" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrOperacionNegociada" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pdtmFechaConstancia" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="pdblValorConstancia" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrGeneraConstancia" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plogCargado" Type="System.Nullable(of System.Boolean)" DbType="BIT NOT NULL" />
    <Parameter Name="pdtmCumplimientoTitulo" Type="System.DateTime" DbType="Datetime NOT NULL" />
    <Parameter Name="pintNroLote" Type="System.Int32" DbType="INT" />
    <Parameter Name="pdblValorEntregaContraPago" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrAquienSeEnviaRetencion" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrIDBaseDias" Type="System.String" DbType="Char(1) NOT NULL" />
    <Parameter Name="pstrTipoDeOferta" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pintNroLoteENC" Type="System.Int32" DbType="INT" />
    <Parameter Name="pdtmContabilidadENC" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="pstrCodigoIntermediario" Type="System.String" DbType="Varchar(10)" />
    <Parameter Name="pcurValorExtemporaneo" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrPosicionExtemporaneo" Type="System.String" DbType="Varchar(1)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="pstrMsgValidacion" Type="System.String" DbType="VarChar(8000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId2" Name="dbo.uspOyDNet_Operaciones_Eliminar" Method="uspOyDNet_Operaciones_Eliminar">
    <Parameter Name="pintIDLiquidaciones" Type="System.Int32" DbType="INT NOT NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="pstrMsgValidacion" Type="System.String" DbType="varchar(8000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_Operaciones_Filtrar" Method="uspOyDNet_Operaciones_Filtrar">
    <Parameter Name="pstrFiltro" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.uspOyDNet_Operaciones_Consultar" Method="uspOyDNet_Operaciones_Consultar">
    <Parameter Name="pstrAccion" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="plngID" Type="System.Int32" DbType="INT NOT NULL" />
    <Parameter Name="plngIDComitente" Type="System.String" DbType="Char(17) NOT NULL" />
    <Parameter Name="pstrTipo" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pstrClaseOrden" Type="System.String" DbType="Varchar(1) NOT NULL" />
    <Parameter Name="pdtmLiquidacion" Type="System.DateTime" DbType="Datetime NOT NULL" />
    <Parameter Name="pdtmCumplimiento" Type="System.DateTime" DbType="Datetime NOT NULL" />
    <Parameter Name="plngIDOrden" Type="System.Int32" DbType="INT" />
    <Parameter Name="plngIDano" Type="System.Int32" DbType="INT" />
    <Parameter Name="plngParcial" Type="System.Nullable(of System.Int32)" DbType="INT NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.spLiquidacionesVeriLiq_OyDNet" Method="spLiquidacionesVeriLiq_OyDNet">
    <Parameter Name="plngID" Type="System.int32" DbType="int" Direction="InOut" />
    <Parameter Name="plngParcial" Type="System.Int32" DbType="Int" />
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pdtmLiquidacion" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLiquidacionesOrdenes_OyDNet" Method="spLiquidacionesOrdenes_OyDNet">
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngIDOrden" Parameter="plngID" Type="System.int32" DbType="int" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.sp_CumplimientoOrden_OyDNet" Method="sp_CumplimientoOrden_OyDNet">
    <Parameter Name="pstrTipo" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="plngIDOrden" Type="System.Int32" DbType="Int" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="pdblCantidadLiq" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="pdblCantidadOrden" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="pdblCantidadImportacion" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdOrdenes_OyDNet" Method="spUpdOrdenes_OyDNet">
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngID" Type="System.int32" DbType="int" />
    <Parameter Name="plngVersion" Type="System.int32" DbType="int" />
    <Parameter Name="pstrEstado" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="pdtmEstado" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLiquidacionesOrdeCum_OyDNet" Method="spLiquidacionesOrdeCum_OyDNet">
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngID" Type="System.int32" DbType="int" />
    <Parameter Name="pstrEstado" Type="System.String" DbType="VarChar(1)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_Liquidaciones_Aplazamiento" Method="uspOyDNet_Liquidaciones_Aplazamiento">
    <Parameter Name="pstrTipoAplazamiento" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="pstrAplazamiento" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="pstrClaseOrden" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="pstrTipoOrden" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="plngIDLiquidacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="plngParcial" Type="System.Int32" DbType="Int" />
    <Parameter Name="pdtmLiquidacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pdtmCumplimiento" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrError" Type="System.String" DbType="VarChar(300)" Direction="InOut" />
    <Parameter Name="intNroAplazamientos" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="InfoSesion" Parameter="infoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spValorEspecie_OyDNet" Method="spValorEspecie_OyDNet">
    <Parameter Name="pstrId" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="pdtmFecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Curvalor" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDenominacionEspecie" Method="spDenominacionEspecie">
    <Parameter Name="pstrId" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="pstrNombre" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spdblIvacomision" Method="spdblIvacomision">
    <Parameter Name="dblIvaComision" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId3" Name="dbo.uspOyDNet_ReceptoresOrdenes_Actualizar" Method="uspOyDNet_ReceptoresOrdenes_Actualizar">
    <Parameter Name="pstrTipoOrden" Type="System.String" DbType="varchar(1)" />
    <Parameter Name="pstrClaseOrden" Type="System.String" DbType="varchar(1)" />
    <Parameter Name="plngIDOrden" Type="System.int32" DbType="int" />
    <Parameter Name="plngVersion" Type="System.int32" DbType="int" />
    <Parameter Name="pstrIDReceptor" Type="System.String" DbType="varchar(4)" />
    <Parameter Name="plogLider" Type="System.Boolean" DbType="bit" />
    <Parameter Name="pdblPorcentaje" Type="System.Double" DbType="float" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="pintIDReceptoresOrdenes" Type="System.int32" DbType="int" Direction="InOut" />
    <Parameter Name="InfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_Bolsa_ReceptoresOrdenes_Filtrar" Method="uspOyDNet_Bolsa_ReceptoresOrdenes_Filtrar">
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngIDOrden" Parameter="plngID" Type="System.int32" DbType="int" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Id="FunctionId4" Name="dbo.uspOyDNet_ReceptoresOrdenes_Eliminar" Method="uspOyDNet_ReceptoresOrdenes_Eliminar">
    <Parameter Name="pintIDReceptoresOrdenes" Type="System.int32" DbType="int" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLiquidacionesReceOrd_OyDNet" Method="spLiquidacionesReceOrd_OyDNet">
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngIDOrden" Parameter="plngID" Type="System.int32" DbType="int" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.uspOyDNet_Bolsa_BeneficiariosOrdenes_Filtrar" Method="uspOyDNet_Bolsa_BeneficiariosOrdenes_Filtrar">
    <Parameter Name="plngID" Type="System.int32" DbType="int" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.spLiquidacionesBeneOrd_OyDNet" Method="spLiquidacionesBeneOrd_OyDNet">
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngIDOrden" Parameter="plngID" Type="System.int32" DbType="int" />
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.spLiquidacionesEspecies_OyDNet" Method="spLiquidacionesEspecies_OyDNet">
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngIDOrden" Parameter="plngID" Type="System.int32" DbType="int" />
    <ElementType IdRef="ID5" />
  </Function>
  <Function Name="dbo.uspOyDNet_Bolsa_EspeciesLiquidaciones_Filtrar" Method="uspOyDNet_Bolsa_EspeciesLiquidaciones_Filtrar">
    <Parameter Name="plngID" Type="System.int32" DbType="int" />
    <Parameter Name="plngParcial" Type="System.int32" DbType="int" />
    <Parameter Name="pdtmLiquidacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID5" />
  </Function>
  <Function Name="dbo.uspOyDNet_Bolsa_AplazamientosLiquidaciones_Filtrar" Method="uspOyDNet_Bolsa_AplazamientosLiquidaciones_Filtrar">
    <Parameter Name="plngID" Type="System.int32" DbType="int" />
    <Parameter Name="pdtmLiquidacion" Type="System.DateTime" DbType="datetime" />
    <Parameter Name="plngParcial" Type="System.Int32" DbType="Int" />
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID6" />
  </Function>
  <Function Name="dbo.uspOyDNet_Bolsa_CustodiasLiquidaciones_Filtrar" Method="uspOyDNet_Bolsa_CustodiasLiquidaciones_Filtrar">
    <Parameter Name="plngIDComisionista" Type="System.int32" DbType="int" />
    <Parameter Name="PlngIDSucComisionista" Type="System.int32" DbType="int" />
    <Parameter Name="plngIDComitente" Type="System.String" DbType="char (17)" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="varchar(15)" />
    <Parameter Name="pstrTipo" Type="System.String" DbType="varchar(1)" />
    <Parameter Name="pstrClaseOrden" Type="System.String" DbType="varchar(1)" />
    <Parameter Name="plngID" Type="System.int32" DbType="int" />
    <Parameter Name="plngParcial" Type="System.int32" DbType="int" />
    <Parameter Name="pdtmLiquidacion" Type="System.DateTime" DbType="datetime" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID7" />
  </Function>
  <Function Name="dbo.spLiquidacionesVeriOrd_OyDNet" Method="spLiquidacionesVeriOrd_OyDNet">
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngID" Type="System.int32" DbType="int" />
    <ElementType IdRef="ID8" />
  </Function>
  <Function Name="dbo.sp_TraerCumplimiento_OyDNet" Method="sp_TraerCumplimiento_OyDNet">
    <Parameter Name="pstrTipo" Type="System.String" DbType="Char(1)" />
    <Parameter Name="pstrClase" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngIDOrden" Parameter="plngID" Type="System.int32" DbType="int" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="VarChar(15)" />
    <ElementType IdRef="ID9" />
  </Function>
  <Function Name="dbo.usp_Operaciones_ModificacionValidar" Method="usp_Operaciones_ModificacionValidar">
    <Parameter Name="plngID" Type="System.Int32" DbType="Int" />
    <Parameter Name="plngParcial" Type="System.Int32" DbType="Int" />
    <Parameter Name="pstrTipo" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="pstrClaseOrden" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="pdtmLiquidacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pstrTipoDeOferta" Type="System.String" DbType="Char(1)" />
    <Parameter Name="plngIDComitente" Type="System.String" DbType="Char(17)" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15)" />
    <ElementType IdRef="ID10" />
  </Function>
  <Function Name="dbo.usp_Operaciones_Retardo_Actualizar" Method="usp_Operaciones_Retardo_Actualizar">
    <Parameter Name="plngID" Type="System.Int32" DbType="Int" />
    <Parameter Name="plngParcial" Type="System.Int32" DbType="Int" />
    <Parameter Name="pstrTipo" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="pstrClaseOrden" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="pdtmLiquidacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="plogReconstruirRetardo" Type="System.Nullable(of System.Boolean)" DbType="bit" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(100)" />
    <ElementType IdRef="ID11" />
  </Function>

  <Function Name="dbo.uspOyDNet_RetardoOperaciones_Consultar" Method="uspOyDNet_RetardoOperaciones_Consultar">
    <Parameter Name="plogFiltroSencillo" Type="System.Boolean" DbType="bit" />
    <Parameter Name="plogFiltroAvanzado" Type="System.Boolean" DbType="bit" />
    <Parameter Name="pstrFiltro" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="pdtmFecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pintCuenta" Type="System.Int32" DbType="INT" />
    <Parameter Name="pstrIDEspecie" Type="System.String" DbType="Varchar(15)" />
    <Parameter Name="plogProcesado" Type="System.Boolean" DbType="bit" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID12" />
  </Function>
  <Function Name="dbo.uspOyDNet_RetardoOperaciones_ConsultarDetalle" Method="uspOyDNet_RetardoOperaciones_ConsultarDetalle">
    <Parameter Name="pintIDRetardo" Type="System.Int32" DbType="INT NOT NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID13" />
  </Function>
  <Function Name="dbo.uspOyDNet_RetardoOperaciones_Controlador" Method="uspOyDNet_RetardoOperaciones_Controlador">
    <Parameter Name="pstrArchivoCarga" Type="System.String" DbType="VarChar(500) NOT NULL" />
    <Parameter Name="pstrArchivoFormato" Type="System.String" DbType="VarChar(500) NOT NULL" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="pstrInfosesion" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="plogRetardoxPantalla" Type="System.Boolean" DbType="bit" />
    <Parameter Name="pintIDRetardo" Type="System.Int32" DbType="INT NOT NULL" />
	  <Parameter Name="pxmlDetalleGrid" Type="System.String" DbType="Text NOT NULL" />
    <Parameter Name="pstrMsgValidacion" Type="System.String" DbType="VarChar(8000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_RetardoOperaciones_Editar" Method="uspOyDNet_RetardoOperaciones_Editar" Id="UpdateRetardoOperaciones" >
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_RetardoOperacionesDetalle_Editar" Method="uspOyDNet_RetardoOperacionesDetalle_Editar" Id="UpdateRetardoOperacionesDetalle" >
    <Return Type="System.Int32" />
  </Function>
</Database>