'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblBcoRepublicaF3
    Public Property TIPO_DECLARACION As String
    Public Property NIT_IMC As String
    Public Property FECHA_DECLARACION As String
    Public Property NUMERO_DECLARACION As String
    Public Property TIPO_REGISTRO As String
    Public Property TIPO_OPERACION As String
    Public Property INGRESO_EGRESO_I_E As String
    Public Property NIT_IMC_ANT As String
    Public Property FECHA_DECL_ANT As String
    Public Property NUMERO_DECL_ANT As String
    Public Property NUM_PRESTAMO As String
    Public Property TIPO_IDENT_REGISTRADO As String
    Public Property NUM_IDENT_REG_DVREGISTRADO As String
    Public Property COD_MONEDA_CONTRAT As String
    Public Property VALOR_TOTAL_MON_CONTRAT As String
    Public Property COD_MONEDA_NEGOCIACION As String
    Public Property VALOR_TOTAL_MON_NEGOCIACION As String
    Public Property BASE_INTERES_360_365 As String
    Public Property TIPO_CAM_MON_NEG_A_USD As String
    Public Property VALOR_TOTALUSD As String
    Public Property NUM_DETALLES As String
    Public Property CORRECION_S_N As String
    Public Property ENVIADO As Nullable(Of Boolean)
    Public Property EXPORTAR As Nullable(Of Boolean)

End Class
