'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_NumeralesCambiarios
    Public Property intIDFormulario As Integer
    Public Property intIDNumeral As Integer
    Public Property strDescripcion As String
    Public Property strConcatenacion As String
    Public Property strtipoClasificacion As String
    Public Property strRepresenta As String
    Public Property strDianSoN As String
    Public Property strAplicaReteFte As String
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String
    Public Property strBalanzaCambiaria As String
    Public Property logActivo As Boolean

End Class
