'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_FormatosDianXML
    Public Property intNroRegPorArchivo As Nullable(Of Integer)
    Public Property strNombreInicial As String
    Public Property strConcepto As String
    Public Property strFormato As String
    Public Property strVersionFormato As String
    Public Property strConsecutivo As String
    Public Property strFechaEnvio As String
    Public Property strDescripcion As String
    Public Property strTipo As String

End Class
