'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_ReporteUIAF
    Public Property Consecutivo As String
    Public Property CodigoEntidad As String
    Public Property FechaCorte As String
    Public Property NumeroTotalOperacionesReportadas As String
    Public Property FinRegistro As String
    Public Property ConsecutivoNumeroRegistroDet As String
    Public Property CodigoSucursal As String
    Public Property FechaOperacion As String
    Public Property TipoOperacion As String
    Public Property Devolucion As String
    Public Property ValorOperacion As String
    Public Property TipoDivisa As String
    Public Property FormaPago As String
    Public Property TipoProducto As String
    Public Property NumeroProducto As String
    Public Property TipoIdentificacion As String
    Public Property NumeroDocumentoIdentificacion As String
    Public Property Digitoverificacion As String
    Public Property Nombre As String
    Public Property Direccion As String
    Public Property DepartamentoMunicipio As String
    Public Property Telefono As String
    Public Property TipoIdentificacionDesc As String
    Public Property NumeroDocumentoIdentificacion1 As String
    Public Property DigitoverificacionDesc As String
    Public Property Nombreremitentebeneficiario As String
    Public Property EntidadTramitaGiro As String
    Public Property PaisCiudadEntidadTramitaGiro As String
    Public Property Ciudad As String
    Public Property Intermedario As String
    Public Property PaisIntermedario As String
    Public Property CiudadIntermedario As String
    Public Property Entidad As String
    Public Property PaisEntidad As String
    Public Property CiudadEntidad As String

End Class
