'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_Formulario3
    Public Property intNumeroDecl As Integer
    Public Property intFormulario As Integer
    Public Property strCondicionNegocio As String
    Public Property intTipoOperacion As Nullable(Of Short)
    Public Property intCiudad As Nullable(Of Integer)
    Public Property strNit As String
    Public Property dtmFecha As Date
    Public Property strNitAnterior As String
    Public Property dtmFechaAnterior As Nullable(Of Date)
    Public Property intNumeroDeclAnterior As Nullable(Of Integer)
    Public Property strTipoDocumento As String
    Public Property intNumeroidentificacion As String
    Public Property intDigitoVerificacion As String
    Public Property strRazonSocial As String
    Public Property intCiudadDomicilio As Nullable(Of Integer)
    Public Property strCondiccionespago As String
    Public Property strCondiccionesDespacho As String
    Public Property strNombreDeclarante As String
    Public Property strNumeroIdentDeclarante As String
    Public Property logEnviado As Nullable(Of Boolean)
    Public Property strObservaciones As String
    Public Property dblTotalvalorFOB As Nullable(Of Decimal)
    Public Property dblTotalGastosExportacion As Nullable(Of Decimal)
    Public Property dblDeducciones As Nullable(Of Decimal)
    Public Property dblReintegroNeto As Nullable(Of Decimal)
    Public Property strTelefono As String
    Public Property strDireccion As String
    Public Property strCodigoMoneda1 As String
    Public Property dblTipoCambioMoneda1 As Nullable(Of Decimal)
    Public Property intNumeralcambiario1 As Nullable(Of Integer)
    Public Property dblValormoneda1 As Nullable(Of Decimal)
    Public Property dblValorUSD1 As Nullable(Of Decimal)
    Public Property strCodigoMoneda2 As String
    Public Property dblTipoCambioMoneda2 As Nullable(Of Decimal)
    Public Property intNumeralcambiario2 As Nullable(Of Integer)
    Public Property dblValormoneda2 As Nullable(Of Decimal)
    Public Property dblValorUSD2 As Nullable(Of Decimal)
    Public Property strGlobal As String
    Public Property strCorreccion As String
    Public Property strIngresoEgreso As String
    Public Property intIDOperacion As Nullable(Of Integer)
    Public Property strNombreDeclaranteFirma As String
    Public Property intNumeroDeclAnteriorFirma As String
    Public Property strEstado As String
    Public Property strTipoReferencia As String
    Public Property dtmFechaActualizacion As Date
    Public Property strUsuario As String
    Public Property logEnviadoDian As Boolean
    Public Property strCorreoElectronicoDecl As String
    Public Property strCodigoCiudadDecl As String
    Public Property logFirmaFormPend As Nullable(Of Boolean)
    Public Property intDeclaracionConsolidado As Nullable(Of Integer)
    Public Property intNumeroBcoRep As Nullable(Of Integer)
    Public Property dtmFechaBcoRep As Nullable(Of Date)
    Public Property intConsecutivo As Long
    Public Property strNumeroPrestamoOp As String
    Public Property strTipoDocumentoOp As String
    Public Property lngNumeroidentificacionOp As String
    Public Property lngDigitoVerificacionEmpOp As String
    Public Property strNombreOperacion As String
    Public Property strNombreAcreedor As String

End Class
