'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblBcoRepublicaF2
    Public Property TIPO_DECLARACION As String
    Public Property NIT_IMC As String
    Public Property FECHA_DECLARACION As String
    Public Property NUMERO_DECLARACION As String
    Public Property TIPO_REGISTRO As String
    Public Property TIPO_OPERACION As String
    Public Property NIT_IMC_ANT As String
    Public Property FECHA_DECL_ANT As String
    Public Property NUMERO_DECL_ANT As String
    Public Property TIPO_IDENT_EXP As String
    Public Property NUM_IDENT_IMP_DVIMPORTADOR As String
    Public Property DVIMPORTADOR As String
    Public Property NOM_EXPORTADOR As String
    Public Property COD_MONEDA_REINT As String
    Public Property VALOR_MONEDA_REINT As String
    Public Property TIPO_CAMBIO_MON_A_USD As String
    Public Property VALOR_FOB As String
    Public Property VLR_REINT_X_REEMB_USD As String
    Public Property VLR_DEDUCCIONES As String
    Public Property VLR_REINT_NETO_USD As String
    Public Property ES_GLOBAL_S_N As String
    Public Property NUM_DETALLES As String
    Public Property CORRECION_S_N As String
    Public Property ENVIADO As Nullable(Of Boolean)
    Public Property EXPORTAR As Nullable(Of Boolean)

End Class
