'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblValidacionesGenerales
    Public Property dtmRegistro As Nullable(Of Date)
    Public Property intIdRegistro As Nullable(Of Integer)
    Public Property intIdValidacion As Integer
    Public Property intOrden As Short
    Public Property logInconsitencia As Boolean
    Public Property strCampo As String
    Public Property strCodMensaje As String
    Public Property strMensaje As String
    Public Property strTipoMensaje As String

End Class
