'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblFormularioEndeudamientoExterno
    Public Property intID As Integer
    Public Property intFormulario As Short
    Public Property intTipoOperacion As Short
    Public Property dtmFecha As Date
    Public Property intNumeroPrestamo As Nullable(Of Integer)
    Public Property strNumeroIdentifiacion As String
    Public Property logDesembolso As Nullable(Of Boolean)
    Public Property intNumeroDeclaracion As Nullable(Of Integer)
    Public Property intNumeral As Nullable(Of Integer)
    Public Property intIDMoneda As Nullable(Of Integer)
    Public Property dblValorMonedaNegociada As Nullable(Of Decimal)
    Public Property dblValorUSD As Nullable(Of Decimal)
    Public Property strNumeroIdentificacionDeudor As String
    Public Property intDigitoVerificacionDeudor As Nullable(Of Short)
    Public Property strNombreDeudor As String
    Public Property intIDCiudadDeudor As Nullable(Of Integer)
    Public Property strDireccionDeudor As String
    Public Property strTelefonoDeudor As String
    Public Property strEmailDeudor As String
    Public Property strIDCodigoCIIUDeudor As String
    Public Property strCodigoBanRepAcreedor As String
    Public Property strNombreAcreedor As String
    Public Property strTipoAcreedor As String
    Public Property intIDMonedaPrestamo As Nullable(Of Integer)
    Public Property dblMontoContratado As Nullable(Of Decimal)
    Public Property dblSpreadValorInteres As Nullable(Of Double)
    Public Property logIndexacion As Nullable(Of Boolean)
    Public Property intIDMonedaIndexacion As Nullable(Of Integer)
    Public Property logSustitucion As Nullable(Of Boolean)
    Public Property logFraccionamiento As Nullable(Of Boolean)
    Public Property logConsolidacion As Nullable(Of Boolean)
    Public Property intNUmeroIDCreditoAnterior1 As Nullable(Of Integer)
    Public Property intIDMonedaAnterior1 As Nullable(Of Integer)
    Public Property dblValorAnterior1 As Nullable(Of Double)
    Public Property intNUmeroIDCreditoAnterior2 As Nullable(Of Integer)
    Public Property intIDMonedaAnterior2 As Nullable(Of Integer)
    Public Property dblValorAnterior2 As Nullable(Of Double)
    Public Property strNombre As String
    Public Property strNumeroIDDeclarante As String
    Public Property strFirma As String
    Public Property dtmActualizacion As Date
    Public Property strUsuario As String
    Public Property logEnviado As Boolean
    Public Property strTipoIdentificacionDeudor As String
    Public Property strPais As String
    Public Property strCodigoPropositoPrestamo As String
    Public Property strTasaInteres As String
    Public Property strNumeroDepositoFinan As String
    Public Property logAnulado As Nullable(Of Boolean)

End Class
