'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblBcoRepublicaF3_Detalle1
    Public Property NUMERAL_CAMB As String
    Public Property VALOR_MONEDA_NEG As String
    Public Property VALOR_MONEDA_CONTRAT As String
    Public Property VALOR_USD As String
    Public Property Blancos As String
    Public Property VLR_BASE_MONEDA_CONTR As String
    Public Property FECHA_INICIAL As String
    Public Property FECHA_FINAL As String
    Public Property NRO_DIAS As String
    Public Property TASA_INTERES As String
    Public Property NUMERO_DECLARACION As String

End Class
