'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_FORMATO_102
    Public Property TIPO As String
    Public Property COLUMNA As String
    Public Property UNIDADCAPTURA As String
    Public Property SUBCUENTA As String
    Public Property VALOR As Nullable(Of Double)
    Public Property FLIQUIDACION As Nullable(Of Date)
    Public Property TIPOENTIDAD As String
    Public Property CODIGOENTIDAD As String

End Class
