'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblBcoRepublicaF4
    Public Property TIPO_DECLARACION As String
    Public Property NIT_IMC As String
    Public Property FECHA_DECLARACION As String
    Public Property NUMERO_DECLARACION As String
    Public Property TIPO_REGISTRO As String
    Public Property TIPO_OPERACION As String
    Public Property INGRESO_EGRESO_I_E As String
    Public Property NIT_IMC_ANT As String
    Public Property FECHA_DECL_ANT As String
    Public Property NUMERO_DECL_ANT As String
    Public Property TIPO_IDENT_DECLARANTE As String
    Public Property NUM_IDENT_DEC_DVDECLARANTE As String
    Public Property NOMBRE_DECLARANTE As String
    Public Property TELEFONO_DECLARANTE As String
    Public Property DIRECCION_DECLARANTE As String
    Public Property CODIGO_CIUDAD_DECLARANTE As String
    Public Property CORREO_ELECTRONICO As String
    Public Property TIPO_IDENT_EMPRESA_RECEPTORA As String
    Public Property NIT_EMPRESA_RECEPTORA_DV_RECEPTORA As String
    Public Property NOMBRE_EMP_RECEP_FONDO As String
    Public Property CODIGO_PAIS_EMP_REC As String
    Public Property CODIGO_CIUDAD_EMPR_RECEP_FONDO As String
    Public Property TELEFONO_EMPR_RECEP_FONDO As String
    Public Property CODIGO_CIIU_EMPR_RECEP_FONDO As String
    Public Property TIPO_IDENT_INVERSIONISTA As String
    Public Property NIT_INVERSIONISTA_DV_INVERSIONISTA As String
    Public Property NOMBRE_INVERSIONISTA As String
    Public Property CODIGO_PAIS_INVERSIONISTA As String
    Public Property CODIGO_CIIU_INVERSIONISTA As String
    Public Property NUMERAL_CAMB As String
    Public Property COD_MONEDA_GIRO_REINT As String
    Public Property VALOR_MONEDA_GIRO_REINT As String
    Public Property NUMERO_ACCIONES As String
    Public Property INVERSION_PLAZOS As String
    Public Property TIPO_CAMBIO_DIV_USD As String
    Public Property VALOR_USD As String
    Public Property TIPO_CAMBIO_USD_COP As String
    Public Property VALOR_PESOS As String
    Public Property DESTINO_INVERSION As String
    Public Property CORRECION_S_N As String
    Public Property ENVIADO As Nullable(Of Boolean)
    Public Property EXPORTAR As Nullable(Of Boolean)

End Class
