'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblDetalle1FormulariosBcoRepublica
    Public Property lnNumeroDecl As Nullable(Of Integer)
    Public Property lngFormulario As Integer
    Public Property intSecuencia As Integer
    Public Property lngNumeralCambiario As Integer
    Public Property dtmFecha As Nullable(Of Date)
    Public Property strTipoDocumentoOp As String
    Public Property lngNumeroidentificacionOp As String
    Public Property lngDigitoVerificacionEmpOp As String
    Public Property strNombreOperacion As String
    Public Property dblValorMonedaNegociacion As Nullable(Of Decimal)
    Public Property dblValorMonedaContratada As Nullable(Of Decimal)
    Public Property dblValorUSD As Nullable(Of Decimal)
    Public Property dblValorbaseContratada As Nullable(Of Decimal)
    Public Property dblFechaInicio As Nullable(Of Date)
    Public Property dblFechaFinal As Nullable(Of Date)
    Public Property intDias As Nullable(Of Integer)
    Public Property dblTasa As Nullable(Of Decimal)
    Public Property strNumeroPrestamoOp As String
    Public Property strCodigoMonedaNeg1 As String
    Public Property strCodigoMonedaNeg2 As String
    Public Property dblValorTotalNeg1 As Nullable(Of Decimal)
    Public Property dblValorTotalNeg2 As Nullable(Of Decimal)
    Public Property baseInteres As String
    Public Property dtmFechaActualizacion As Date
    Public Property strUsuario As String

End Class
