'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblDetalle5FormulariosBcoRepublica
    Public Property lngIDComisionista As Integer
    Public Property lngIDSucComisionista As Integer
    Public Property lngNumeroDecl As Integer
    Public Property lngFormulario As Integer
    Public Property dtmFechaDecl As Date
    Public Property strNumeroPrestamoOp As String
    Public Property strTipoDocumentoOp As String
    Public Property lngNumeroidentificacionOp As String
    Public Property lngDigitoVerificacionEmpOp As String
    Public Property strNombreOperacion As String
    Public Property strCodigoMonedaCon1 As String
    Public Property strCodigoMonedaCon2 As String
    Public Property dblValorMonedaCon1 As Nullable(Of Decimal)
    Public Property dblValorMonedaCon2 As Nullable(Of Decimal)
    Public Property strCodigoMonedaNeg1 As String
    Public Property strCodigoMonedaNeg2 As String
    Public Property dblValorTotalNeg1 As Nullable(Of Decimal)
    Public Property dblValorTotalNeg2 As Nullable(Of Decimal)
    Public Property baseInteres As Nullable(Of Integer)
    Public Property dblTipoCambioMonedaNeg As Nullable(Of Decimal)
    Public Property dblValorDolares As Nullable(Of Decimal)
    Public Property strNombreAcreedor As String
    Public Property dtmFechaActualizacion As Date
    Public Property strUsuario As String

End Class
