'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_TransaccionesConsolidado_EXCEL
    Public Property intConsecutivo As String
    Public Property TipoRegistro As String
    Public Property campo3 As String
    Public Property campo4 As String
    Public Property campo5 As String
    Public Property campo6 As String
    Public Property campo7 As String
    Public Property campo8 As String
    Public Property campo9 As String

End Class
