'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblDetalleFormulario2DIAN
    Public Property intID As Integer
    Public Property lnNumeroDecl As Integer
    Public Property dtmFecha As Nullable(Of Date)
    Public Property intCiudad As Nullable(Of Integer)
    Public Property lngNumero As String
    Public Property dtmFechaPresentacion As Nullable(Of Date)
    Public Property dtmFechaActualizacion As Date
    Public Property strUsuario As String
    Public Property intNumeral As Integer
    Public Property dblValor As Double

End Class
