'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_ArchivosLegalesDIAN_Formato1062
    Public Property ano As Nullable(Of Integer)
    Public Property FORMATO As String
    Public Property tinf As Integer
    Public Property top As Integer
    Public Property ccom As Nullable(Of Integer)
    Public Property fdec As String
    Public Property ndec As String
    Public Property fdeca As String
    Public Property ndeca As String
    Public Property tdoc As Integer
    Public Property nid As String
    Public Property dv As String
    Public Property apl1 As String
    Public Property apl2 As String
    Public Property nom1 As String
    Public Property nom2 As String
    Public Property raz As String
    Public Property dir As String
    Public Property mun As String
    Public Property ciud As String
    Public Property cmon As String
    Public Property vmon As Nullable(Of Decimal)
    Public Property vtusd As Nullable(Of Decimal)
    Public Property Row_Number As Nullable(Of Long)
    Public Property intNumeral As Nullable(Of Integer)
    Public Property dtmfechaDecl As Date

End Class
