'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_FORMATO395_Validar
    Public Property dtmNoHabil As Nullable(Of Integer)
    Public Property strTipoEntidad As String
    Public Property strCodigoEntidad As String
    Public Property strNitComisionista As String
    Public Property strNombreCompleto As String
    Public Property strPalabraClave As String

End Class
