'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_ArchivosLegalesDIAN_Formato1064
    Public Property ano As Nullable(Of Integer)
    Public Property FORMATO As String
    Public Property top As Integer
    Public Property fec As Date
    Public Property npres As String
    Public Property ndec As String
    Public Property num As Nullable(Of Integer)
    Public Property cmonn As String
    Public Property vtmon As Nullable(Of Decimal)
    Public Property vusd As Nullable(Of Decimal)
    Public Property tdoc As Nullable(Of Integer)
    Public Property nid As String
    Public Property dv As String
    Public Property apl1 As String
    Public Property apl2 As String
    Public Property nom1 As String
    Public Property nom2 As String
    Public Property raz As String
    Public Property mun As String
    Public Property dir As String
    Public Property apl1a As String
    Public Property apl2a As String
    Public Property nom1a As String
    Public Property nom2a As String
    Public Property raza As String
    Public Property cpre As Nullable(Of Integer)
    Public Property cmon As String
    Public Property monc As Nullable(Of Decimal)
    Public Property Row_Number As Nullable(Of Long)

End Class
