'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblDetalle4FormulariosBcoRepublica
    Public Property lngNumeroDecl As Integer
    Public Property lngFormulario As Integer
    Public Property dtmFechaDecl As Date
    Public Property strTipoDocumentoEmpRec As String
    Public Property lngNumeroidentificacionEmpRec As String
    Public Property lngDigitoVerificacionEmpRec As String
    Public Property strNombreEmpRec As String
    Public Property intPaisEmpReceptora As Nullable(Of Integer)
    Public Property strTipoDocumentoInv As String
    Public Property lngNumeroidentificacionInv As String
    Public Property lngDigitoVerificacionInv As String
    Public Property strNombreInversionista As String
    Public Property strEntidadInversionista As String
    Public Property intPaisInversionista As Nullable(Of Integer)
    Public Property dtmFechaInversionista As Nullable(Of Date)
    Public Property lngNumeroInversionista As String
    Public Property lngNumeralcambiarioOperacion As Nullable(Of Integer)
    Public Property strCodigoMonedaOperacion As String
    Public Property dblValorMonedaGiroOperacion As Nullable(Of Decimal)
    Public Property dblTipoCambioUSDOperacion As Nullable(Of Decimal)
    Public Property dblValorUSDOperacion As Nullable(Of Decimal)
    Public Property dblTipoCambioPesosOperacion As Nullable(Of Decimal)
    Public Property dblValorPesosOperacion As Nullable(Of Decimal)
    Public Property strDestinoOperacion As Nullable(Of Integer)
    Public Property strCodigoPaisInversionista As String
    Public Property strCodigociiuInversionista As String
    Public Property strCodigoPaisEmpRec As String
    Public Property strCodigociiuEmpRec As String
    Public Property strAccionesOCuotas As String
    Public Property strInversionAPlazos As String
    Public Property strCodigoCiudadEmpRec As String
    Public Property strTelefonoEmpRec As String
    Public Property dtmFechaActualizacion As Date
    Public Property strUsuario As String

End Class
