'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFormulariosBcoRepublica
    Public Property lngIDComisionista As Integer
    Public Property lngIDSucComisionista As Integer
    Public Property lngNumeroDecl As Integer
    Public Property lngFormulario As Integer
    Public Property strCondicionNegocio As String
    Public Property intTipoOperacion As Nullable(Of Short)
    Public Property lngCiudad As Nullable(Of Integer)
    Public Property lngNit As String
    Public Property dtmFecha As Date
    Public Property lngNitAnterior As String
    Public Property dtmFechaAnterior As Nullable(Of Date)
    Public Property lngNumeroDeclAnterior As Nullable(Of Integer)
    Public Property strTipoDocumento As String
    Public Property lngNumeroidentificacion As String
    Public Property lngDigitoVerificacion As String
    Public Property RazonSocial As String
    Public Property lngCiudadDomicilio As Nullable(Of Integer)
    Public Property strCondiccionespago As String
    Public Property strCondiccionesDespacho As String
    Public Property strNombreDeclarante As String
    Public Property lngNumeroIdentDeclarante As String
    Public Property blnEnviado As Nullable(Of Boolean)
    Public Property strObservaciones As String
    Public Property dblTotalvalorFOB As Nullable(Of Decimal)
    Public Property dblTotalGastosExportacion As Nullable(Of Decimal)
    Public Property dblDeducciones As Nullable(Of Decimal)
    Public Property dblReintegroNeto As Nullable(Of Decimal)
    Public Property strTelefono As String
    Public Property strDireccion As String
    Public Property strCodigoMoneda1 As String
    Public Property dblTipoCambioMoneda1 As Nullable(Of Decimal)
    Public Property lngNumeralcambiario1 As Nullable(Of Integer)
    Public Property dblValormoneda1 As Nullable(Of Decimal)
    Public Property dblValorUSD1 As Nullable(Of Decimal)
    Public Property strCodigoMoneda2 As String
    Public Property dblTipoCambioMoneda2 As Nullable(Of Decimal)
    Public Property lngNumeralcambiario2 As Nullable(Of Integer)
    Public Property dblValormoneda2 As Nullable(Of Decimal)
    Public Property dblValorUSD2 As Nullable(Of Decimal)
    Public Property strGlobal As String
    Public Property strCorreccion As String
    Public Property strIngresoEgreso As String
    Public Property lngIDOperacion As Nullable(Of Integer)
    Public Property strNombreDeclaranteFirma As String
    Public Property lngNumeroDeclAnteriorFirma As String
    Public Property strEstado As String
    Public Property strTipoReferencia As String
    Public Property dtmFechaActualizacion As Date
    Public Property strUsuario As String
    Public Property blnEnviadoDian As Boolean
    Public Property strCorreoElectronicoDecl As String
    Public Property strCodigoCiudadDecl As String
    Public Property logFirmaFormPend As Nullable(Of Boolean)
    Public Property lngDeclaracionConsolidado As Nullable(Of Integer)
    Public Property intNumeroBcoRepAnterior As Nullable(Of Integer)
    Public Property intNumeroBcoRep As Nullable(Of Integer)
    Public Property dtmFechaBcoRep As Nullable(Of Date)
    Public Property dtmFechaBcoRepAnterior As Nullable(Of Date)

End Class
