<?xml version="1.0" encoding="utf-8"?>
<Database Name="dbOYDPlus" Class="OyD_OTCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.tblLiquidaciones_OTC" Member="Liquidaciones_OTC">
    <Type Name="Liquidaciones_OT" Id="ID1">
      <Column Name="LNGID" Member="ID" Type="System.int32" DbType="Int Not Null" CanBeNull="false" />
      <Column Name="LNGVERSION" Member="VERSION" Type="System.Nullable(Of System.int32)" DbType="Int" CanBeNull="true" />
      <Column Name="STRNOMBRESISTEMA" Member="NOMBRESISTEMA" Type="System.String" DbType="Varchar(15)" CanBeNull="true" />
      <Column Name="LNGNUMEROOPERACION" Member="NUMEROOPERACION" Type="System.Nullable(Of System.int32)" DbType="Int" CanBeNull="true" />
      <Column Name="DTMOPERACION" Member="OPERACION" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="STRTIPOOPERACION" Member="TIPOOPERACION" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="strMercado" Member="Mercado" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="STRTIPONEGOCIACION" Member="TIPONEGOCIACION" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="STRREGISTROOPERACION" Member="REGISTROOPERACION" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="STRTIPOPAGOOPERACION" Member="TIPOPAGOOPERACION" Type="System.String" DbType="Varchar(2)" CanBeNull="true" />
      <Column Name="STRIDESPECIE" Member="IDESPECIE" Type="System.String" DbType="Varchar(15)" CanBeNull="true" />
      <Column Name="DBLCANTIDADNEGOCIADA" Member="CANTIDADNEGOCIADA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DTMEMISION" Member="EMISION" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="DTMCUMPLIMIENTO" Member="CUMPLIMIENTO" Type="System.DateTime" DbType="Datetime" CanBeNull="false" />
      <Column Name="DTMVENCIMIENTO" Member="VENCIMIENTO" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="LNGDIASALVENCIMIENTOTITULO" Member="DIASALVENCIMIENTOTITULO" Type="System.Nullable(Of System.int32)" DbType="Int" CanBeNull="true" />
      <Column Name="DBLTASAINTERESNOMINAL" Member="TASAINTERESNOMINAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="STRMODALIDADTASANOMINAL" Member="MODALIDADTASANOMINAL" Type="System.String" DbType="Varchar(2)" CanBeNull="true" />
      <Column Name="DBLTASAEFECTIVAANUAL" Member="TASAEFECTIVAANUAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DBLPRECIO" Member="PRECIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DBLMONTO" Member="MONTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="STRIDREPRESENTANTELEGAL" Member="IDREPRESENTANTELEGAL" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
      <Column Name="LNGIDCOMITENTE" Member="IDCOMITENTE" Type="System.String" DbType="Char(17)" CanBeNull="true" />
      <Column Name="STRNROTITULO" Member="NROTITULO" Type="System.String" DbType="Varchar(25)" CanBeNull="true" />
      <Column Name="STRINDICADOR" Member="INDICADOR" Type="System.String" DbType="Varchar(10)" CanBeNull="true" />
      <Column Name="LNGPUNTOSINDICADOR" Member="PUNTOSINDICADOR" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="LOGRENTAFIJA" Member="RENTAFIJA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="STRPREFIJO" Member="PREFIJO" Type="System.String" DbType="Varchar(5)" CanBeNull="true" />
      <Column Name="LNGIDFACTURA" Member="IDFACTURA" Type="System.Nullable(Of System.int32)" DbType="Int" CanBeNull="true" />
      <Column Name="STRFACTURADA" Member="FACTURADA" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="STRNOMBRECLIENTE" Member="NOMBRECLIENTE" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
      <Column Name="STRNOMBREREPRESENTANTE" Member="NOMBREREPRESENTANTE" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
      <Column Name="STRNOMBREESPECIE" Member="NOMBREESPECIE" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
      <Column Name="strFormaPago" Member="FormaPago" Type="System.String" DbType="Varchar(150)" CanBeNull="true" />
      <Column Name="STRESTADO" Member="ESTADO" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="intNroLote" Member="NroLote" Type="System.Nullable(Of System.int32)" DbType="Int" CanBeNull="true" />
      <Column Name="DTMACTUALIZACION" Member="ACTUALIZACION" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="STRUSUARIO" Member="USUARIO" Type="System.String" DbType="Varchar(60)" CanBeNull="true" />
      <Column Name="intNroLoteENC" Member="NroLoteENC" Type="System.Nullable(Of System.int32)" DbType="Int" CanBeNull="true" />
      <Column Name="dtmContabilidadENC" Member="ContabilidadENC" Type="System.DateTime" DbType="Datetime" CanBeNull="true" />
      <Column Name="ESPECIE_ESACCION" Type="System.String" DbType="Varchar(1)" CanBeNull="true" />
      <Column Name="intIdLiquidaciones_OTC" Member="IdLiquidaciones_OTC" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InfoSesion" Type="System.String" DbType="Varchar(1000)" CanBeNull="true" />
      <Column Name="logCargado" Member="Cargado" Type="System.Nullable(Of System.Boolean)" DbType="Bit NULL" CanBeNull="true" />
      <Association Name="Liquidaciones_OT_ReceptoresOT" Member="ReceptoresOTs" ThisKey="ID" OtherKey="Id" Type="ReceptoresOT" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId1">
      <Argument Parameter="pLNGID" Member="ID" />
      <Argument Parameter="pSTRNOMBRESISTEMA" Member="NOMBRESISTEMA" />
      <Argument Parameter="pLNGNUMEROOPERACION" Member="NUMEROOPERACION" />
      <Argument Parameter="pDTMOPERACION" Member="OPERACION" />
      <Argument Parameter="pSTRTIPOOPERACION" Member="TIPOOPERACION" />
      <Argument Parameter="pstrMercado" Member="Mercado" />
      <Argument Parameter="pSTRTIPONEGOCIACION" Member="TIPONEGOCIACION" />
      <Argument Parameter="pSTRREGISTROOPERACION" Member="REGISTROOPERACION" />
      <Argument Parameter="pSTRTIPOPAGOOPERACION" Member="TIPOPAGOOPERACION" />
      <Argument Parameter="pSTRIDESPECIE" Member="IDESPECIE" />
      <Argument Parameter="pDBLCANTIDADNEGOCIADA" Member="CANTIDADNEGOCIADA" />
      <Argument Parameter="pDTMEMISION" Member="EMISION" />
      <Argument Parameter="pDTMCUMPLIMIENTO" Member="CUMPLIMIENTO" />
      <Argument Parameter="pDTMVENCIMIENTO" Member="VENCIMIENTO" />
      <Argument Parameter="pLNGDIASALVENCIMIENTOTITULO" Member="DIASALVENCIMIENTOTITULO" />
      <Argument Parameter="pDBLTASAINTERESNOMINAL" Member="TASAINTERESNOMINAL" />
      <Argument Parameter="pSTRMODALIDADTASANOMINAL" Member="MODALIDADTASANOMINAL" />
      <Argument Parameter="pDBLTASAEFECTIVAANUAL" Member="TASAEFECTIVAANUAL" />
      <Argument Parameter="pDBLPRECIO" Member="PRECIO" />
      <Argument Parameter="pDBLMONTO" Member="MONTO" />
      <Argument Parameter="pSTRIDREPRESENTANTELEGAL" Member="IDREPRESENTANTELEGAL" />
      <Argument Parameter="pLNGIDCOMITENTE" Member="IDCOMITENTE" />
      <Argument Parameter="pSTRNROTITULO" Member="NROTITULO" />
      <Argument Parameter="pSTRINDICADOR" Member="INDICADOR" />
      <Argument Parameter="pLNGPUNTOSINDICADOR" Member="PUNTOSINDICADOR" />
      <Argument Parameter="pLOGRENTAFIJA" Member="RENTAFIJA" />
      <Argument Parameter="pSTRPREFIJO" Member="PREFIJO" />
      <Argument Parameter="pLNGIDFACTURA" Member="IDFACTURA" />
      <Argument Parameter="pSTRESTADO" Member="ESTADO" />
      <Argument Parameter="pSTRUSUARIO" Member="USUARIO" />
      <Argument Parameter="pintIdLiquidaciones_OTC" Member="IdLiquidaciones_OTC" />
      <Argument Parameter="infosesion" Member="InfoSesion" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId1">
      <Argument Parameter="pLNGID" Member="ID" />
      <Argument Parameter="pSTRNOMBRESISTEMA" Member="NOMBRESISTEMA" />
      <Argument Parameter="pLNGNUMEROOPERACION" Member="NUMEROOPERACION" />
      <Argument Parameter="pDTMOPERACION" Member="OPERACION" />
      <Argument Parameter="pSTRTIPOOPERACION" Member="TIPOOPERACION" />
      <Argument Parameter="pstrMercado" Member="Mercado" />
      <Argument Parameter="pSTRTIPONEGOCIACION" Member="TIPONEGOCIACION" />
      <Argument Parameter="pSTRREGISTROOPERACION" Member="REGISTROOPERACION" />
      <Argument Parameter="pSTRTIPOPAGOOPERACION" Member="TIPOPAGOOPERACION" />
      <Argument Parameter="pSTRIDESPECIE" Member="IDESPECIE" />
      <Argument Parameter="pDBLCANTIDADNEGOCIADA" Member="CANTIDADNEGOCIADA" />
      <Argument Parameter="pDTMEMISION" Member="EMISION" />
      <Argument Parameter="pDTMCUMPLIMIENTO" Member="CUMPLIMIENTO" />
      <Argument Parameter="pDTMVENCIMIENTO" Member="VENCIMIENTO" />
      <Argument Parameter="pLNGDIASALVENCIMIENTOTITULO" Member="DIASALVENCIMIENTOTITULO" />
      <Argument Parameter="pDBLTASAINTERESNOMINAL" Member="TASAINTERESNOMINAL" />
      <Argument Parameter="pSTRMODALIDADTASANOMINAL" Member="MODALIDADTASANOMINAL" />
      <Argument Parameter="pDBLTASAEFECTIVAANUAL" Member="TASAEFECTIVAANUAL" />
      <Argument Parameter="pDBLPRECIO" Member="PRECIO" />
      <Argument Parameter="pDBLMONTO" Member="MONTO" />
      <Argument Parameter="pSTRIDREPRESENTANTELEGAL" Member="IDREPRESENTANTELEGAL" />
      <Argument Parameter="pLNGIDCOMITENTE" Member="IDCOMITENTE" />
      <Argument Parameter="pSTRNROTITULO" Member="NROTITULO" />
      <Argument Parameter="pSTRINDICADOR" Member="INDICADOR" />
      <Argument Parameter="pLNGPUNTOSINDICADOR" Member="PUNTOSINDICADOR" />
      <Argument Parameter="pLOGRENTAFIJA" Member="RENTAFIJA" />
      <Argument Parameter="pSTRPREFIJO" Member="PREFIJO" />
      <Argument Parameter="pLNGIDFACTURA" Member="IDFACTURA" />
      <Argument Parameter="pSTRESTADO" Member="ESTADO" />
      <Argument Parameter="pSTRUSUARIO" Member="USUARIO" />
      <Argument Parameter="pintIdLiquidaciones_OTC" Member="IdLiquidaciones_OTC" />
      <Argument Parameter="infosesion" Member="InfoSesion" />
    </UpdateFunction>
  </Table>
  <Table Name="dbo.tblReceptoresOTC" Member="ReceptoresOTC">
    <Type Name="ReceptoresOT" Id="ID2">
      <Column Name="intIDReceptoresOTC" Member="IDReceptoresOTC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lngId" Member="Id" Type="System.int32" DbType="Int" CanBeNull="true" />
      <Column Name="strIDReceptor" Member="IDReceptor" Type="System.String" DbType="Varchar(4)" CanBeNull="true" />
      <Column Name="logLider" Member="Lider" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="dblPorcentaje" Member="Porcentaje" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="strReceptor" Member="NombreReceptor" Type="System.String" DbType="Varchar(50)" CanBeNull="true" />
      <Column Name="dtmActualizacion" Member="Actualizacion" Type="System.DateTime" DbType="Datetime NOT NULL" CanBeNull="false" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="false" />
      <Column Name="InfoSesion" Type="System.String" DbType="Varchar(1000)" CanBeNull="true" />
      <Association Name="Liquidaciones_OT_ReceptoresOT" Member="Liquidaciones_OT" ThisKey="Id" OtherKey="ID" Type="Liquidaciones_OT" IsForeignKey="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId2">
      <Argument Parameter="pintIDReceptoresOTC" Member="IDReceptoresOTC" />
      <Argument Parameter="plngId" Member="Id" />
      <Argument Parameter="pstrIDReceptor" Member="IDReceptor" />
      <Argument Parameter="plogLider" Member="Lider" />
      <Argument Parameter="pdblPorcentaje" Member="Porcentaje" />
      <Argument Parameter="pstrUsuario" Member="Usuario" />
      <Argument Parameter="infosesion" Member="InfoSesion" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId2">
      <Argument Parameter="pintIDReceptoresOTC" Member="IDReceptoresOTC" />
      <Argument Parameter="plngId" Member="Id" />
      <Argument Parameter="pstrIDReceptor" Member="IDReceptor" />
      <Argument Parameter="plogLider" Member="Lider" />
      <Argument Parameter="pdblPorcentaje" Member="Porcentaje" />
      <Argument Parameter="pstrUsuario" Member="Usuario" />
      <Argument Parameter="infosesion" Member="InfoSesion" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId3">
      <Argument Parameter="plngId" Member="Id" />
      <Argument Parameter="pstrIDReceptor" Member="IDReceptor" />
      <Argument Parameter="infosesion" Member="InfoSesion" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.tblFacturas_OTC" Member="Facturas_OTC">
    <Type Name="Factura_OTC" Id="ID3">
      <Column Name="lngIDComisionista" Member="IDComisionista" Type="System.int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lngIDSucComisionista" Member="IDSucComisionista" Type="System.int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strPrefijo" Member="Prefijo" Type="System.String" DbType="Varchar(5) NOT NULL" CanBeNull="false" />
      <Column Name="lngID" Member="Numero" Type="System.int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Prefijo_Numero" Type="System.String" DbType="Varchar(30) NOT NULL" CanBeNull="true" />
      <Column Name="lngIDComitente" Member="Comitente" Type="System.String" DbType="Char(17) NOT NULL" CanBeNull="false" />
      <Column Name="strNombre" Member="Nombre" Type="System.String" DbType="Varchar(250) NOT NULL" CanBeNull="false" />
      <Column Name="dtmDocumento" Member="Fecha_Documento" Type="System.DateTime" DbType="Datetime NOT NULL" CanBeNull="false" />
      <Column Name="strEstado" Member="Estado" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="dtmEstado" Member="Fecha_Estado" Type="System.DateTime" DbType="Datetime NOT NULL" CanBeNull="false" />
      <Column Name="lngImpresiones" Member="Impresiones" Type="System.int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtmActualizacion" Member="Actualizacion" Type="System.DateTime" DbType="Datetime NOT NULL" CanBeNull="false" />
      <Column Name="strUsuario" Member="Usuario" Type="System.String" DbType="Varchar(60) NOT NULL" CanBeNull="false" />
      <Column Name="lngIDCodigoResolucion" Member="IDCodigoResolucion" Type="System.int32" DbType="Int" CanBeNull="true" />
      <Column Name="intIDfacturas" Member="IDfacturas" Type="System.int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InfoSesion" Type="System.String" DbType="Varchar(1000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId3">
      <Argument Parameter="plngId" Member="Numero" />
      <Argument Parameter="pstrUsuario" Member="Usuario" />
      <Argument Parameter="infosesion" Member="InfoSesion" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId3">
      <Argument Parameter="plngId" Member="Numero" />
      <Argument Parameter="pstrUsuario" Member="Usuario" />
      <Argument Parameter="infosesion" Member="InfoSesion" />
    </UpdateFunction>
    <DeleteFunction FunctionId="FunctionId3">
      <Argument Parameter="pstrUsuario" Member="Usuario" />
      <Argument Parameter="infosesion" Member="InfoSesion" />
    </DeleteFunction>
  </Table>
  <Table Name="dbo.tmpResultado" Member="tmpResultados">
    <Type Name="tmpResultado" Id ="ID7">
      <Column Name="lngID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lngIDOperacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intResultado" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="strMensaje" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblImportacionLiqSEN" Member="tblImportacionLiqSENs">
    <Type Name="tblImportacionLiqSEN">
      <Column Name="lngID" Type="System.Int32" Member ="lngID" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dtmFechaImportacion" Member ="dtmFechaImportacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dtmHoraImportacion" Member ="dtmHoraImportacion" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="lngIDOperacion" Member ="lngIDOperacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="strTipo" Member ="strTipo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="strEspecie" Member ="strEspecie" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="dblCantidad" Member ="dblCantidad" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lngDiasVencimiento" Member="lngDiasVencimiento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="curEquivalente" Member ="curEquivalente" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curTotal" Member="curTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="curPrecio" Member ="curPrecio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dtmEmision" Member="dtmEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dtmVencimiento" Member ="dtmVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dtmLiquidacion" Member ="dtmLiquidacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="strTipoNegociacion" Member ="strTipoNegociacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strISIN" Member ="strISIN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="strUsuario" Member ="strUsuario" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="dtmActualizacion" Member ="dtmActualizacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="intResultado" Member ="intResultado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ListaComentario" Member ="ListaComentario" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="lngIdComitente" Member ="lngIdComitente" Type="System.String" DbType="Char(17)" CanBeNull="true" />
      <Column Name="dblCantidadGarantia" Member ="dblCantidadGarantia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strRueda" Member ="strRueda" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="pstrUsuarioConexion" Type="System.String" DbType="Varchar(100)" CanBeNull="true" />
      <Column Name="pstrInfoConexion" Type="System.String" DbType="Varchar(8000)" CanBeNull="true" />
    </Type>

  </Table>
  <Function Id="FunctionId1" Name="dbo.uspOyDNet_OTC_Liquidaciones_OTC_Actualizar" Method="uspOyDNet_OTC_Liquidaciones_OTC_Actualizar">
    <Parameter Name="pLNGID" Type="System.int32" DbType="int" Direction="InOut" />
    <Parameter Name="pSTRNOMBRESISTEMA" Type="System.String" DbType="varchar(15)" />
    <Parameter Name="pLNGNUMEROOPERACION" Type="System.Nullable(Of System.int32)" DbType="int" />
    <Parameter Name="pDTMOPERACION" Type="System.DateTime" DbType="datetime" />
    <Parameter Name="pSTRTIPOOPERACION" Type="System.String" DbType="varchar(1)" />
    <Parameter Name="pstrMercado" Type="System.String" DbType="varchar(1)" />
    <Parameter Name="pSTRTIPONEGOCIACION" Type="System.String" DbType="varchar(1)" />
    <Parameter Name="pSTRREGISTROOPERACION" Type="System.String" DbType="varchar(1)" />
    <Parameter Name="pSTRTIPOPAGOOPERACION" Type="System.String" DbType="varchar(2)" />
    <Parameter Name="pSTRIDESPECIE" Type="System.String" DbType="varchar(15)" />
    <Parameter Name="pDBLCANTIDADNEGOCIADA" Type="System.Double" DbType="float" />
    <Parameter Name="pDTMEMISION" Type="System.DateTime" DbType="datetime" />
    <Parameter Name="pDTMCUMPLIMIENTO" Type="System.DateTime" DbType="datetime" />
    <Parameter Name="pDTMVENCIMIENTO" Type="System.DateTime" DbType="datetime" />
    <Parameter Name="pLNGDIASALVENCIMIENTOTITULO" Type="System.Nullable(Of System.int32)" DbType="int" />
    <Parameter Name="pDBLTASAINTERESNOMINAL" Type="System.Double" DbType="float" />
    <Parameter Name="pSTRMODALIDADTASANOMINAL" Type="System.String" DbType="varchar(2)" />
    <Parameter Name="pDBLTASAEFECTIVAANUAL" Type="System.Double" DbType="float" />
    <Parameter Name="pDBLPRECIO" Type="System.Double" DbType="float" />
    <Parameter Name="pDBLMONTO" Type="System.Double" DbType="float" />
    <Parameter Name="pSTRIDREPRESENTANTELEGAL" Type="System.String" DbType="varchar(50)" />
    <Parameter Name="pLNGIDCOMITENTE" Type="System.String" DbType="char(17)" />
    <Parameter Name="pSTRNROTITULO" Type="System.String" DbType="varchar(25)" />
    <Parameter Name="pSTRINDICADOR" Type="System.String" DbType="varchar(10)" />
    <Parameter Name="pLNGPUNTOSINDICADOR" Type="System.Single" DbType="real" />
    <Parameter Name="pLOGRENTAFIJA" Type="System.Boolean" DbType="bit" />
    <Parameter Name="pSTRPREFIJO" Type="System.String" DbType="varchar(5)" />
    <Parameter Name="pLNGIDFACTURA" Type="System.Nullable(Of System.int32)" DbType="int" />
    <Parameter Name="pSTRESTADO" Type="System.String" DbType="varchar(1)" />
    <Parameter Name="pSTRUSUARIO" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="pintIdLiquidaciones_OTC" Type="System.int32" DbType="int" Direction="InOut" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />


  </Function>
  <Function Name="dbo.uspOyDNet_OTC_Liquidaciones_OTC_Eliminar" Method="uspOyDNet_OTC_Liquidaciones_OTC_Eliminar">
    <Parameter Name="pLNGID" Type="System.int32" DbType="int" />
    <Parameter Name="pSTRUSUARIO" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_Liquidaciones_OTC_Consultar" Method="uspOyDNet_OTC_Liquidaciones_OTC_Consultar">
    <Parameter Name="pLNGID" Type="System.Nullable(Of System.int32)" DbType="int" />
    <Parameter Name="pLNGNUMEROOPERACION" Type="System.Nullable(Of System.int32)" DbType="int" />
    <Parameter Name="pDTMOPERACION" Type="System.Nullable(Of System.DateTime)" DbType="datetime" />
    <Parameter Name="pDTMCUMPLIMIENTO" Type="System.Nullable(Of System.DateTime)" DbType="datetime" />
    <Parameter Name="pLNGIDCOMITENTE" Type="System.String" DbType="char(17)" />
    <Parameter Name="pSTRIDESPECIE" Type="System.String" DbType="varchar(15)" />
    <Parameter Name="pSTRUSUARIO" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_Liquidaciones_OTC_Filtrar" Method="uspOyDNet_OTC_Liquidaciones_OTC_Filtrar">
    <Parameter Name="pstrfiltro" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Id="FunctionId2" Name="dbo.uspOyDNet_OTC_ReceptoresOTC_Actualizar" Method="uspOyDNet_OTC_ReceptoresOTC_Actualizar">
    <Parameter Name="pintIDReceptoresOTC" Type="System.Int32" DbType="Int NOT NULL" Direction="InOut" />
    <Parameter Name="plngId" Type="System.int32" DbType="int" />
    <Parameter Name="pstrIDReceptor" Type="System.String" DbType="varchar(4)" />
    <Parameter Name="plogLider" Type="System.Boolean" DbType="bit" />
    <Parameter Name="pdblPorcentaje" Type="System.Double" DbType="float" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId3" Name="dbo.uspOyDNet_OTC_ReceptoresOTC_Eliminar" Method="uspOyDNet_OTC_ReceptoresOTC_Eliminar">
    <Parameter Name="plngId" Type="System.int32" DbType="int" />
    <Parameter Name="pstrIDReceptor" Type="System.String" DbType="varchar(4)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_ReceptoresOTC_Consultar" Method="uspOyDNet_OTC_ReceptoresOTC_Consultar">
    <Parameter Name="plngId" Type="System.int32" DbType="int" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_tblFacturasOTC_Consultar" Method="uspOyDNet_OTC_tblFacturasOTC_Consultar">
    <Parameter Name="plngID" Parameter="lngID" Type="System.Nullable(Of System.int32)" DbType="int" />
    <Parameter Name="plngIDComitente" Parameter="lngIDComitente" Type="System.String" DbType="char(17)" />
    <Parameter Name="pdtmDocumento" Parameter="dtmDocumento" Type="System.Nullable(Of System.DateTime)" DbType="DateTime" />
    <Parameter Name="pstrNombreComitente" Parameter="strNombreComitente" Type="System.String" DbType="Varchar(50)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_FacturarOTC_Filtrar" Method="uspOyDNet_OTC_FacturarOTC_Filtrar">
    <Parameter Name="pstrfiltro" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_tblFacturasOTC_TotalFactura" Method="uspOyDNet_OTC_tblFacturasOTC_TotalFactura">
    <Parameter Name="lngIDFactura" Type="System.Int32" DbType="Int" />
    <Parameter Name="strPrefijo" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="curTotalFactura" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_Liquidaciones_OTC_Factura_Consultar" Method="uspOyDNet_OTC_Liquidaciones_OTC_Factura_Consultar">
    <Parameter Name="pLNGIDFACTURA" Type="System.int32" DbType="int" />
    <Parameter Name="pstrPrefijo" Parameter="strPrefijo" Type="System.String" DbType="varchar(5)" />
    <Parameter Name="pSTRUSUARIO" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_FacturarOTC_Eliminar" Method="uspOyDNet_OTC_FacturarOTC_Eliminar">
    <Parameter Name="pintIDfacturas" Type="System.int32" DbType="int" />
    <Parameter Name="plngID" Parameter="lngID" Type="System.int32" DbType="int" />
    <Parameter Name="pstrPrefijo" Type="System.String" DbType="varchar(5)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_sprptConstanciaOperacionOTC" Method="uspOyDNet_OTC_sprptConstanciaOperacionOTC">
    <Parameter Name="plngIDInicial" Parameter="lngIDInicial" Type="System.int32" DbType="int" />
    <Parameter Name="plngIDFinal" Parameter="lngIDFinal" Type="System.int32" DbType="int" />
    <Parameter Name="pdtmFechaIni" Parameter="dtmFechaIni" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="pdtmFechaFin" Parameter="dtmFechaFin" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_rptPlantillaConstanciaOperacionOTC" Method="uspOyDNet_OTC_rptPlantillaConstanciaOperacionOTC">
    <Parameter Name="plngIDInicial" Parameter="lngIDInicial" Type="System.int32" DbType="int" />
    <Parameter Name="plngIDFinal" Parameter="lngIDFinal" Type="System.int32" DbType="int" />
    <Parameter Name="pdtmFechaIni" Parameter="dtmFechaIni" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="pdtmFechaFin" Parameter="dtmFechaFin" Type="System.DateTime" DbType="Datetime" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="pstrHTMLPlantillaOTC" Type="System.String" DbType="VarChar(120000)" Direction="InOut" />
    <Return Type="System.Int32"/>
  </Function>
  <Function Name="dbo.uspOyDNet_OTC_sprptConstanciaOperacionReceptoresOTC" Method="uspOyDNet_OTC_sprptConstanciaOperacionReceptoresOTC">
    <Parameter Name="plngIDOperacion" Parameter="lngIDOperacion" Type="System.int32" DbType="int" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="varchar(60)" />
    <Parameter Name="infosesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.ufnOYDNet_Accion_Actualizar" Method="ufnOYDNet_Accion_Actualizar" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.ufnOYDNet_Accion_Validar" Method="ufnOYDNet_Accion_Validar" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Id="FunctionID5" Name="dbo.uspOyDNet_OTC_Liquidaciones_SEN_Importar" Method="uspOyDNet_OTC_Liquidaciones_SEN_Importar">
    <Parameter Name="pstrMetodo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pdtmFechaImportacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pdtmHoraImportacion" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="plngIDOperacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="plngIdComitente" Type="System.String" DbType="Char(17)" />
    <Parameter Name="pstrTipo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="pstrEspecie" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="pdblCantidad" Type="System.Double" DbType="Float" />
    <Parameter Name="plngDiasVencimiento" Type="System.Int32" DbType="Int" />
    <Parameter Name="pcurEquivalente" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurTotal" Type="System.Double" DbType="Float" />
    <Parameter Name="pcurPrecio" Type="System.Double" DbType="Float" />
    <Parameter Name="pdtmFechaEmision" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pdtmFechaVencimiento" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pdtmFechaLiquidacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pstrTipoNegociacion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pstrISINTitulo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pdblCantidadGarantia" Type="System.Double" DbType="Float" />
    <Parameter Name="pstrRueda" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID7" />
  </Function>
  <Function Id="FunctionID6" Name="dbo.uspOyDNet_OTC_Liquidaciones_SEN_ImportarMasivo" Method="uspOyDNet_OTC_Liquidaciones_SEN_ImportarMasivo">
    <Parameter Name="pstrMetodo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pstrRegistros" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="pstrUsuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pstrInfoSesion" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="pintErrorPersonalizado" Type="System.Byte" DbType="TinyInt" />
    <ElementType IdRef="ID7" />
  </Function>
</Database>