'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblParametrizacionTributaria
    Public Property intID As Nullable(Of Integer)
    Public Property strNombre As String
    Public Property strDescripcionModulo As String
    Public Property strDescripcionFuncionalidad As String
    Public Property strNombrePais As String
    Public Property strNombreCiudad As String
    Public Property strEstado As String

End Class
