'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CPX_tblPais
    Public Property intID As Nullable(Of Integer)
    Public Property strNombre As String
    Public Property strCodigoISOAlfa2 As String
    Public Property strCodigoISOAlfa3 As String
    Public Property strCodigoISONumerico As String
    Public Property strEstado As String

End Class
