'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPais
    Public Property intID As Integer
    Public Property strNombre As String
    Public Property strCodigoISOAlfa2 As String
    Public Property strCodigoISOAlfa3 As String
    Public Property strCodigoISONumerico As String
    Public Property logActivo As Boolean
    Public Property strUsuario As String
    Public Property dtmActualizacion As Date
    Public Property strUsuarioInsercion As String

    Public Overridable Property tblPais_Estado As ICollection(Of tblPais_Estado) = New HashSet(Of tblPais_Estado)
    Public Overridable Property tblPais_Moneda As ICollection(Of tblPais_Moneda) = New HashSet(Of tblPais_Moneda)
    Public Overridable Property tblParametrizacionTributaria As ICollection(Of tblParametrizacionTributaria) = New HashSet(Of tblParametrizacionTributaria)

End Class
