'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPais_Moneda
    Public Property intID As Integer
    Public Property intIDPais As Integer
    Public Property strUsuario As String
    Public Property dtmActualizacion As Date
    Public Property strUsuarioInsercion As String
    Public Property strCodigoMoneda As String

    Public Overridable Property tblPais As tblPais

End Class
