'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblParametrizacionTributaria
    Public Property intID As Integer
    Public Property strNombre As String
    Public Property dblTasaImpositiva As Double
    Public Property strModulo As String
    Public Property strFuncionalidad As String
    Public Property intIDPais As Integer
    Public Property intIDCiudad As Integer
    Public Property logActivo As Boolean
    Public Property strUsuario As String
    Public Property dtmActualizacion As Date
    Public Property strUsuarioInsercion As String

    Public Overridable Property tblPais As tblPais

End Class
